/*
 * Copyright 2015, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY apic. DO NOT EDIT.
 */

#include "common/get_gfx_proc_address.h"
#include "gles_imports.h"

namespace gapii {

void GlesImports::Resolve() {
    using namespace gapic;
    eglCreateContext = reinterpret_cast<PFNEGLCREATECONTEXT>(GetGfxProcAddress("eglCreateContext"));
    eglMakeCurrent = reinterpret_cast<PFNEGLMAKECURRENT>(GetGfxProcAddress("eglMakeCurrent"));
    eglSwapBuffers = reinterpret_cast<PFNEGLSWAPBUFFERS>(GetGfxProcAddress("eglSwapBuffers"));
    wglSwapBuffers = reinterpret_cast<PFNWGLSWAPBUFFERS>(GetGfxProcAddress("wglSwapBuffers"));
    glEnableClientState =
            reinterpret_cast<PFNGLENABLECLIENTSTATE>(GetGfxProcAddress("glEnableClientState"));
    glDisableClientState =
            reinterpret_cast<PFNGLDISABLECLIENTSTATE>(GetGfxProcAddress("glDisableClientState"));
    glGetProgramBinaryOES =
            reinterpret_cast<PFNGLGETPROGRAMBINARYOES>(GetGfxProcAddress("glGetProgramBinaryOES"));
    glProgramBinaryOES =
            reinterpret_cast<PFNGLPROGRAMBINARYOES>(GetGfxProcAddress("glProgramBinaryOES"));
    glStartTilingQCOM =
            reinterpret_cast<PFNGLSTARTTILINGQCOM>(GetGfxProcAddress("glStartTilingQCOM"));
    glEndTilingQCOM = reinterpret_cast<PFNGLENDTILINGQCOM>(GetGfxProcAddress("glEndTilingQCOM"));
    glDiscardFramebufferEXT = reinterpret_cast<PFNGLDISCARDFRAMEBUFFEREXT>(
            GetGfxProcAddress("glDiscardFramebufferEXT"));
    glInsertEventMarkerEXT = reinterpret_cast<PFNGLINSERTEVENTMARKEREXT>(
            GetGfxProcAddress("glInsertEventMarkerEXT"));
    glPushGroupMarkerEXT =
            reinterpret_cast<PFNGLPUSHGROUPMARKEREXT>(GetGfxProcAddress("glPushGroupMarkerEXT"));
    glPopGroupMarkerEXT =
            reinterpret_cast<PFNGLPOPGROUPMARKEREXT>(GetGfxProcAddress("glPopGroupMarkerEXT"));
    glTexStorage1DEXT =
            reinterpret_cast<PFNGLTEXSTORAGE1DEXT>(GetGfxProcAddress("glTexStorage1DEXT"));
    glTexStorage2DEXT =
            reinterpret_cast<PFNGLTEXSTORAGE2DEXT>(GetGfxProcAddress("glTexStorage2DEXT"));
    glTexStorage3DEXT =
            reinterpret_cast<PFNGLTEXSTORAGE3DEXT>(GetGfxProcAddress("glTexStorage3DEXT"));
    glTextureStorage1DEXT =
            reinterpret_cast<PFNGLTEXTURESTORAGE1DEXT>(GetGfxProcAddress("glTextureStorage1DEXT"));
    glTextureStorage2DEXT =
            reinterpret_cast<PFNGLTEXTURESTORAGE2DEXT>(GetGfxProcAddress("glTextureStorage2DEXT"));
    glTextureStorage3DEXT =
            reinterpret_cast<PFNGLTEXTURESTORAGE3DEXT>(GetGfxProcAddress("glTextureStorage3DEXT"));
    glGenVertexArraysOES =
            reinterpret_cast<PFNGLGENVERTEXARRAYSOES>(GetGfxProcAddress("glGenVertexArraysOES"));
    glBindVertexArrayOES =
            reinterpret_cast<PFNGLBINDVERTEXARRAYOES>(GetGfxProcAddress("glBindVertexArrayOES"));
    glDeleteVertexArraysOES = reinterpret_cast<PFNGLDELETEVERTEXARRAYSOES>(
            GetGfxProcAddress("glDeleteVertexArraysOES"));
    glIsVertexArrayOES =
            reinterpret_cast<PFNGLISVERTEXARRAYOES>(GetGfxProcAddress("glIsVertexArrayOES"));
    glEGLImageTargetTexture2DOES = reinterpret_cast<PFNGLEGLIMAGETARGETTEXTURE2DOES>(
            GetGfxProcAddress("glEGLImageTargetTexture2DOES"));
    glEGLImageTargetRenderbufferStorageOES =
            reinterpret_cast<PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOES>(
                    GetGfxProcAddress("glEGLImageTargetRenderbufferStorageOES"));
    glGetGraphicsResetStatusEXT = reinterpret_cast<PFNGLGETGRAPHICSRESETSTATUSEXT>(
            GetGfxProcAddress("glGetGraphicsResetStatusEXT"));
    glBindAttribLocation =
            reinterpret_cast<PFNGLBINDATTRIBLOCATION>(GetGfxProcAddress("glBindAttribLocation"));
    glBlendFunc = reinterpret_cast<PFNGLBLENDFUNC>(GetGfxProcAddress("glBlendFunc"));
    glBlendFuncSeparate =
            reinterpret_cast<PFNGLBLENDFUNCSEPARATE>(GetGfxProcAddress("glBlendFuncSeparate"));
    glBlendEquation = reinterpret_cast<PFNGLBLENDEQUATION>(GetGfxProcAddress("glBlendEquation"));
    glBlendEquationSeparate = reinterpret_cast<PFNGLBLENDEQUATIONSEPARATE>(
            GetGfxProcAddress("glBlendEquationSeparate"));
    glBlendColor = reinterpret_cast<PFNGLBLENDCOLOR>(GetGfxProcAddress("glBlendColor"));
    glEnableVertexAttribArray = reinterpret_cast<PFNGLENABLEVERTEXATTRIBARRAY>(
            GetGfxProcAddress("glEnableVertexAttribArray"));
    glDisableVertexAttribArray = reinterpret_cast<PFNGLDISABLEVERTEXATTRIBARRAY>(
            GetGfxProcAddress("glDisableVertexAttribArray"));
    glVertexAttribPointer =
            reinterpret_cast<PFNGLVERTEXATTRIBPOINTER>(GetGfxProcAddress("glVertexAttribPointer"));
    glGetActiveAttrib =
            reinterpret_cast<PFNGLGETACTIVEATTRIB>(GetGfxProcAddress("glGetActiveAttrib"));
    glGetActiveUniform =
            reinterpret_cast<PFNGLGETACTIVEUNIFORM>(GetGfxProcAddress("glGetActiveUniform"));
    glGetError = reinterpret_cast<PFNGLGETERROR>(GetGfxProcAddress("glGetError"));
    glGetProgramiv = reinterpret_cast<PFNGLGETPROGRAMIV>(GetGfxProcAddress("glGetProgramiv"));
    glGetShaderiv = reinterpret_cast<PFNGLGETSHADERIV>(GetGfxProcAddress("glGetShaderiv"));
    glGetUniformLocation =
            reinterpret_cast<PFNGLGETUNIFORMLOCATION>(GetGfxProcAddress("glGetUniformLocation"));
    glGetAttribLocation =
            reinterpret_cast<PFNGLGETATTRIBLOCATION>(GetGfxProcAddress("glGetAttribLocation"));
    glPixelStorei = reinterpret_cast<PFNGLPIXELSTOREI>(GetGfxProcAddress("glPixelStorei"));
    glTexParameteri = reinterpret_cast<PFNGLTEXPARAMETERI>(GetGfxProcAddress("glTexParameteri"));
    glTexParameterf = reinterpret_cast<PFNGLTEXPARAMETERF>(GetGfxProcAddress("glTexParameterf"));
    glGetTexParameteriv =
            reinterpret_cast<PFNGLGETTEXPARAMETERIV>(GetGfxProcAddress("glGetTexParameteriv"));
    glGetTexParameterfv =
            reinterpret_cast<PFNGLGETTEXPARAMETERFV>(GetGfxProcAddress("glGetTexParameterfv"));
    glUniform1i = reinterpret_cast<PFNGLUNIFORM1I>(GetGfxProcAddress("glUniform1i"));
    glUniform2i = reinterpret_cast<PFNGLUNIFORM2I>(GetGfxProcAddress("glUniform2i"));
    glUniform3i = reinterpret_cast<PFNGLUNIFORM3I>(GetGfxProcAddress("glUniform3i"));
    glUniform4i = reinterpret_cast<PFNGLUNIFORM4I>(GetGfxProcAddress("glUniform4i"));
    glUniform1iv = reinterpret_cast<PFNGLUNIFORM1IV>(GetGfxProcAddress("glUniform1iv"));
    glUniform2iv = reinterpret_cast<PFNGLUNIFORM2IV>(GetGfxProcAddress("glUniform2iv"));
    glUniform3iv = reinterpret_cast<PFNGLUNIFORM3IV>(GetGfxProcAddress("glUniform3iv"));
    glUniform4iv = reinterpret_cast<PFNGLUNIFORM4IV>(GetGfxProcAddress("glUniform4iv"));
    glUniform1f = reinterpret_cast<PFNGLUNIFORM1F>(GetGfxProcAddress("glUniform1f"));
    glUniform2f = reinterpret_cast<PFNGLUNIFORM2F>(GetGfxProcAddress("glUniform2f"));
    glUniform3f = reinterpret_cast<PFNGLUNIFORM3F>(GetGfxProcAddress("glUniform3f"));
    glUniform4f = reinterpret_cast<PFNGLUNIFORM4F>(GetGfxProcAddress("glUniform4f"));
    glUniform1fv = reinterpret_cast<PFNGLUNIFORM1FV>(GetGfxProcAddress("glUniform1fv"));
    glUniform2fv = reinterpret_cast<PFNGLUNIFORM2FV>(GetGfxProcAddress("glUniform2fv"));
    glUniform3fv = reinterpret_cast<PFNGLUNIFORM3FV>(GetGfxProcAddress("glUniform3fv"));
    glUniform4fv = reinterpret_cast<PFNGLUNIFORM4FV>(GetGfxProcAddress("glUniform4fv"));
    glUniformMatrix2fv =
            reinterpret_cast<PFNGLUNIFORMMATRIX2FV>(GetGfxProcAddress("glUniformMatrix2fv"));
    glUniformMatrix3fv =
            reinterpret_cast<PFNGLUNIFORMMATRIX3FV>(GetGfxProcAddress("glUniformMatrix3fv"));
    glUniformMatrix4fv =
            reinterpret_cast<PFNGLUNIFORMMATRIX4FV>(GetGfxProcAddress("glUniformMatrix4fv"));
    glGetUniformfv = reinterpret_cast<PFNGLGETUNIFORMFV>(GetGfxProcAddress("glGetUniformfv"));
    glGetUniformiv = reinterpret_cast<PFNGLGETUNIFORMIV>(GetGfxProcAddress("glGetUniformiv"));
    glVertexAttrib1f = reinterpret_cast<PFNGLVERTEXATTRIB1F>(GetGfxProcAddress("glVertexAttrib1f"));
    glVertexAttrib2f = reinterpret_cast<PFNGLVERTEXATTRIB2F>(GetGfxProcAddress("glVertexAttrib2f"));
    glVertexAttrib3f = reinterpret_cast<PFNGLVERTEXATTRIB3F>(GetGfxProcAddress("glVertexAttrib3f"));
    glVertexAttrib4f = reinterpret_cast<PFNGLVERTEXATTRIB4F>(GetGfxProcAddress("glVertexAttrib4f"));
    glVertexAttrib1fv =
            reinterpret_cast<PFNGLVERTEXATTRIB1FV>(GetGfxProcAddress("glVertexAttrib1fv"));
    glVertexAttrib2fv =
            reinterpret_cast<PFNGLVERTEXATTRIB2FV>(GetGfxProcAddress("glVertexAttrib2fv"));
    glVertexAttrib3fv =
            reinterpret_cast<PFNGLVERTEXATTRIB3FV>(GetGfxProcAddress("glVertexAttrib3fv"));
    glVertexAttrib4fv =
            reinterpret_cast<PFNGLVERTEXATTRIB4FV>(GetGfxProcAddress("glVertexAttrib4fv"));
    glGetShaderPrecisionFormat = reinterpret_cast<PFNGLGETSHADERPRECISIONFORMAT>(
            GetGfxProcAddress("glGetShaderPrecisionFormat"));
    glDepthMask = reinterpret_cast<PFNGLDEPTHMASK>(GetGfxProcAddress("glDepthMask"));
    glDepthFunc = reinterpret_cast<PFNGLDEPTHFUNC>(GetGfxProcAddress("glDepthFunc"));
    glDepthRangef = reinterpret_cast<PFNGLDEPTHRANGEF>(GetGfxProcAddress("glDepthRangef"));
    glColorMask = reinterpret_cast<PFNGLCOLORMASK>(GetGfxProcAddress("glColorMask"));
    glStencilMask = reinterpret_cast<PFNGLSTENCILMASK>(GetGfxProcAddress("glStencilMask"));
    glStencilMaskSeparate =
            reinterpret_cast<PFNGLSTENCILMASKSEPARATE>(GetGfxProcAddress("glStencilMaskSeparate"));
    glStencilFuncSeparate =
            reinterpret_cast<PFNGLSTENCILFUNCSEPARATE>(GetGfxProcAddress("glStencilFuncSeparate"));
    glStencilOpSeparate =
            reinterpret_cast<PFNGLSTENCILOPSEPARATE>(GetGfxProcAddress("glStencilOpSeparate"));
    glFrontFace = reinterpret_cast<PFNGLFRONTFACE>(GetGfxProcAddress("glFrontFace"));
    glViewport = reinterpret_cast<PFNGLVIEWPORT>(GetGfxProcAddress("glViewport"));
    glScissor = reinterpret_cast<PFNGLSCISSOR>(GetGfxProcAddress("glScissor"));
    glActiveTexture = reinterpret_cast<PFNGLACTIVETEXTURE>(GetGfxProcAddress("glActiveTexture"));
    glGenTextures = reinterpret_cast<PFNGLGENTEXTURES>(GetGfxProcAddress("glGenTextures"));
    glDeleteTextures = reinterpret_cast<PFNGLDELETETEXTURES>(GetGfxProcAddress("glDeleteTextures"));
    glIsTexture = reinterpret_cast<PFNGLISTEXTURE>(GetGfxProcAddress("glIsTexture"));
    glBindTexture = reinterpret_cast<PFNGLBINDTEXTURE>(GetGfxProcAddress("glBindTexture"));
    glTexImage2D = reinterpret_cast<PFNGLTEXIMAGE2D>(GetGfxProcAddress("glTexImage2D"));
    glTexSubImage2D = reinterpret_cast<PFNGLTEXSUBIMAGE2D>(GetGfxProcAddress("glTexSubImage2D"));
    glCopyTexImage2D = reinterpret_cast<PFNGLCOPYTEXIMAGE2D>(GetGfxProcAddress("glCopyTexImage2D"));
    glCopyTexSubImage2D =
            reinterpret_cast<PFNGLCOPYTEXSUBIMAGE2D>(GetGfxProcAddress("glCopyTexSubImage2D"));
    glCompressedTexImage2D = reinterpret_cast<PFNGLCOMPRESSEDTEXIMAGE2D>(
            GetGfxProcAddress("glCompressedTexImage2D"));
    glCompressedTexSubImage2D = reinterpret_cast<PFNGLCOMPRESSEDTEXSUBIMAGE2D>(
            GetGfxProcAddress("glCompressedTexSubImage2D"));
    glGenerateMipmap = reinterpret_cast<PFNGLGENERATEMIPMAP>(GetGfxProcAddress("glGenerateMipmap"));
    glReadPixels = reinterpret_cast<PFNGLREADPIXELS>(GetGfxProcAddress("glReadPixels"));
    glGenFramebuffers =
            reinterpret_cast<PFNGLGENFRAMEBUFFERS>(GetGfxProcAddress("glGenFramebuffers"));
    glBindFramebuffer =
            reinterpret_cast<PFNGLBINDFRAMEBUFFER>(GetGfxProcAddress("glBindFramebuffer"));
    glCheckFramebufferStatus = reinterpret_cast<PFNGLCHECKFRAMEBUFFERSTATUS>(
            GetGfxProcAddress("glCheckFramebufferStatus"));
    glDeleteFramebuffers =
            reinterpret_cast<PFNGLDELETEFRAMEBUFFERS>(GetGfxProcAddress("glDeleteFramebuffers"));
    glIsFramebuffer = reinterpret_cast<PFNGLISFRAMEBUFFER>(GetGfxProcAddress("glIsFramebuffer"));
    glGenRenderbuffers =
            reinterpret_cast<PFNGLGENRENDERBUFFERS>(GetGfxProcAddress("glGenRenderbuffers"));
    glBindRenderbuffer =
            reinterpret_cast<PFNGLBINDRENDERBUFFER>(GetGfxProcAddress("glBindRenderbuffer"));
    glRenderbufferStorage =
            reinterpret_cast<PFNGLRENDERBUFFERSTORAGE>(GetGfxProcAddress("glRenderbufferStorage"));
    glDeleteRenderbuffers =
            reinterpret_cast<PFNGLDELETERENDERBUFFERS>(GetGfxProcAddress("glDeleteRenderbuffers"));
    glIsRenderbuffer = reinterpret_cast<PFNGLISRENDERBUFFER>(GetGfxProcAddress("glIsRenderbuffer"));
    glGetRenderbufferParameteriv = reinterpret_cast<PFNGLGETRENDERBUFFERPARAMETERIV>(
            GetGfxProcAddress("glGetRenderbufferParameteriv"));
    glGenBuffers = reinterpret_cast<PFNGLGENBUFFERS>(GetGfxProcAddress("glGenBuffers"));
    glBindBuffer = reinterpret_cast<PFNGLBINDBUFFER>(GetGfxProcAddress("glBindBuffer"));
    glBufferData = reinterpret_cast<PFNGLBUFFERDATA>(GetGfxProcAddress("glBufferData"));
    glBufferSubData = reinterpret_cast<PFNGLBUFFERSUBDATA>(GetGfxProcAddress("glBufferSubData"));
    glDeleteBuffers = reinterpret_cast<PFNGLDELETEBUFFERS>(GetGfxProcAddress("glDeleteBuffers"));
    glIsBuffer = reinterpret_cast<PFNGLISBUFFER>(GetGfxProcAddress("glIsBuffer"));
    glGetBufferParameteriv = reinterpret_cast<PFNGLGETBUFFERPARAMETERIV>(
            GetGfxProcAddress("glGetBufferParameteriv"));
    glCreateShader = reinterpret_cast<PFNGLCREATESHADER>(GetGfxProcAddress("glCreateShader"));
    glDeleteShader = reinterpret_cast<PFNGLDELETESHADER>(GetGfxProcAddress("glDeleteShader"));
    glShaderSource = reinterpret_cast<PFNGLSHADERSOURCE>(GetGfxProcAddress("glShaderSource"));
    glShaderBinary = reinterpret_cast<PFNGLSHADERBINARY>(GetGfxProcAddress("glShaderBinary"));
    glGetShaderInfoLog =
            reinterpret_cast<PFNGLGETSHADERINFOLOG>(GetGfxProcAddress("glGetShaderInfoLog"));
    glGetShaderSource =
            reinterpret_cast<PFNGLGETSHADERSOURCE>(GetGfxProcAddress("glGetShaderSource"));
    glReleaseShaderCompiler = reinterpret_cast<PFNGLRELEASESHADERCOMPILER>(
            GetGfxProcAddress("glReleaseShaderCompiler"));
    glCompileShader = reinterpret_cast<PFNGLCOMPILESHADER>(GetGfxProcAddress("glCompileShader"));
    glIsShader = reinterpret_cast<PFNGLISSHADER>(GetGfxProcAddress("glIsShader"));
    glCreateProgram = reinterpret_cast<PFNGLCREATEPROGRAM>(GetGfxProcAddress("glCreateProgram"));
    glDeleteProgram = reinterpret_cast<PFNGLDELETEPROGRAM>(GetGfxProcAddress("glDeleteProgram"));
    glAttachShader = reinterpret_cast<PFNGLATTACHSHADER>(GetGfxProcAddress("glAttachShader"));
    glDetachShader = reinterpret_cast<PFNGLDETACHSHADER>(GetGfxProcAddress("glDetachShader"));
    glGetAttachedShaders =
            reinterpret_cast<PFNGLGETATTACHEDSHADERS>(GetGfxProcAddress("glGetAttachedShaders"));
    glLinkProgram = reinterpret_cast<PFNGLLINKPROGRAM>(GetGfxProcAddress("glLinkProgram"));
    glGetProgramInfoLog =
            reinterpret_cast<PFNGLGETPROGRAMINFOLOG>(GetGfxProcAddress("glGetProgramInfoLog"));
    glUseProgram = reinterpret_cast<PFNGLUSEPROGRAM>(GetGfxProcAddress("glUseProgram"));
    glIsProgram = reinterpret_cast<PFNGLISPROGRAM>(GetGfxProcAddress("glIsProgram"));
    glValidateProgram =
            reinterpret_cast<PFNGLVALIDATEPROGRAM>(GetGfxProcAddress("glValidateProgram"));
    glClearColor = reinterpret_cast<PFNGLCLEARCOLOR>(GetGfxProcAddress("glClearColor"));
    glClearDepthf = reinterpret_cast<PFNGLCLEARDEPTHF>(GetGfxProcAddress("glClearDepthf"));
    glClearStencil = reinterpret_cast<PFNGLCLEARSTENCIL>(GetGfxProcAddress("glClearStencil"));
    glClear = reinterpret_cast<PFNGLCLEAR>(GetGfxProcAddress("glClear"));
    glCullFace = reinterpret_cast<PFNGLCULLFACE>(GetGfxProcAddress("glCullFace"));
    glPolygonOffset = reinterpret_cast<PFNGLPOLYGONOFFSET>(GetGfxProcAddress("glPolygonOffset"));
    glLineWidth = reinterpret_cast<PFNGLLINEWIDTH>(GetGfxProcAddress("glLineWidth"));
    glSampleCoverage = reinterpret_cast<PFNGLSAMPLECOVERAGE>(GetGfxProcAddress("glSampleCoverage"));
    glHint = reinterpret_cast<PFNGLHINT>(GetGfxProcAddress("glHint"));
    glFramebufferRenderbuffer = reinterpret_cast<PFNGLFRAMEBUFFERRENDERBUFFER>(
            GetGfxProcAddress("glFramebufferRenderbuffer"));
    glFramebufferTexture2D = reinterpret_cast<PFNGLFRAMEBUFFERTEXTURE2D>(
            GetGfxProcAddress("glFramebufferTexture2D"));
    glGetFramebufferAttachmentParameteriv =
            reinterpret_cast<PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIV>(
                    GetGfxProcAddress("glGetFramebufferAttachmentParameteriv"));
    glDrawElements = reinterpret_cast<PFNGLDRAWELEMENTS>(GetGfxProcAddress("glDrawElements"));
    glDrawArrays = reinterpret_cast<PFNGLDRAWARRAYS>(GetGfxProcAddress("glDrawArrays"));
    glFlush = reinterpret_cast<PFNGLFLUSH>(GetGfxProcAddress("glFlush"));
    glFinish = reinterpret_cast<PFNGLFINISH>(GetGfxProcAddress("glFinish"));
    glGetBooleanv = reinterpret_cast<PFNGLGETBOOLEANV>(GetGfxProcAddress("glGetBooleanv"));
    glGetFloatv = reinterpret_cast<PFNGLGETFLOATV>(GetGfxProcAddress("glGetFloatv"));
    glGetIntegerv = reinterpret_cast<PFNGLGETINTEGERV>(GetGfxProcAddress("glGetIntegerv"));
    glGetString = reinterpret_cast<PFNGLGETSTRING>(GetGfxProcAddress("glGetString"));
    glEnable = reinterpret_cast<PFNGLENABLE>(GetGfxProcAddress("glEnable"));
    glDisable = reinterpret_cast<PFNGLDISABLE>(GetGfxProcAddress("glDisable"));
    glIsEnabled = reinterpret_cast<PFNGLISENABLED>(GetGfxProcAddress("glIsEnabled"));
    glMapBufferRange = reinterpret_cast<PFNGLMAPBUFFERRANGE>(GetGfxProcAddress("glMapBufferRange"));
    glUnmapBuffer = reinterpret_cast<PFNGLUNMAPBUFFER>(GetGfxProcAddress("glUnmapBuffer"));
    glInvalidateFramebuffer = reinterpret_cast<PFNGLINVALIDATEFRAMEBUFFER>(
            GetGfxProcAddress("glInvalidateFramebuffer"));
    glRenderbufferStorageMultisample = reinterpret_cast<PFNGLRENDERBUFFERSTORAGEMULTISAMPLE>(
            GetGfxProcAddress("glRenderbufferStorageMultisample"));
    glBlitFramebuffer =
            reinterpret_cast<PFNGLBLITFRAMEBUFFER>(GetGfxProcAddress("glBlitFramebuffer"));
    glGenQueries = reinterpret_cast<PFNGLGENQUERIES>(GetGfxProcAddress("glGenQueries"));
    glBeginQuery = reinterpret_cast<PFNGLBEGINQUERY>(GetGfxProcAddress("glBeginQuery"));
    glEndQuery = reinterpret_cast<PFNGLENDQUERY>(GetGfxProcAddress("glEndQuery"));
    glDeleteQueries = reinterpret_cast<PFNGLDELETEQUERIES>(GetGfxProcAddress("glDeleteQueries"));
    glIsQuery = reinterpret_cast<PFNGLISQUERY>(GetGfxProcAddress("glIsQuery"));
    glGetQueryiv = reinterpret_cast<PFNGLGETQUERYIV>(GetGfxProcAddress("glGetQueryiv"));
    glGetQueryObjectuiv =
            reinterpret_cast<PFNGLGETQUERYOBJECTUIV>(GetGfxProcAddress("glGetQueryObjectuiv"));
    glGenQueriesEXT = reinterpret_cast<PFNGLGENQUERIESEXT>(GetGfxProcAddress("glGenQueriesEXT"));
    glBeginQueryEXT = reinterpret_cast<PFNGLBEGINQUERYEXT>(GetGfxProcAddress("glBeginQueryEXT"));
    glEndQueryEXT = reinterpret_cast<PFNGLENDQUERYEXT>(GetGfxProcAddress("glEndQueryEXT"));
    glDeleteQueriesEXT =
            reinterpret_cast<PFNGLDELETEQUERIESEXT>(GetGfxProcAddress("glDeleteQueriesEXT"));
    glIsQueryEXT = reinterpret_cast<PFNGLISQUERYEXT>(GetGfxProcAddress("glIsQueryEXT"));
    glQueryCounterEXT =
            reinterpret_cast<PFNGLQUERYCOUNTEREXT>(GetGfxProcAddress("glQueryCounterEXT"));
    glGetQueryivEXT = reinterpret_cast<PFNGLGETQUERYIVEXT>(GetGfxProcAddress("glGetQueryivEXT"));
    glGetQueryObjectivEXT =
            reinterpret_cast<PFNGLGETQUERYOBJECTIVEXT>(GetGfxProcAddress("glGetQueryObjectivEXT"));
    glGetQueryObjectuivEXT = reinterpret_cast<PFNGLGETQUERYOBJECTUIVEXT>(
            GetGfxProcAddress("glGetQueryObjectuivEXT"));
    glGetQueryObjecti64vEXT = reinterpret_cast<PFNGLGETQUERYOBJECTI64VEXT>(
            GetGfxProcAddress("glGetQueryObjecti64vEXT"));
    glGetQueryObjectui64vEXT = reinterpret_cast<PFNGLGETQUERYOBJECTUI64VEXT>(
            GetGfxProcAddress("glGetQueryObjectui64vEXT"));
}

}  // namespace gapii
