/*
 * Copyright 2015, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY apic. DO NOT EDIT.
 */

#ifndef GAPII_GLES_IMPORTS_H
#define GAPII_GLES_IMPORTS_H

#include "gles_types.h"

#include <gapic/target.h>  // STDCALL

namespace gapii {

struct GlesImports {
    void Resolve();

    typedef EGLBoolean(STDCALL *PFNEGLINITIALIZE)(EGLDisplay dpy, EGLint *major, EGLint *minor);
    typedef EGLContext(STDCALL *PFNEGLCREATECONTEXT)(EGLDisplay display, EGLConfig config,
                                                     EGLContext share_context,
                                                     const EGLint *attrib_list);
    typedef EGLBoolean(STDCALL *PFNEGLMAKECURRENT)(EGLDisplay display, EGLSurface draw,
                                                   EGLSurface read, EGLContext context);
    typedef EGLBoolean(STDCALL *PFNEGLSWAPBUFFERS)(EGLDisplay display, const void *surface);
    typedef EGLBoolean(STDCALL *PFNEGLQUERYSURFACE)(EGLDisplay display, EGLSurface surface,
                                                    EGLint attribute, EGLint *value);
    typedef GLXContext(STDCALL *PFNGLXCREATECONTEXT)(const void *dpy, const void *vis,
                                                     GLXContext shareList, bool direct);
    typedef GLXContext(STDCALL *PFNGLXCREATENEWCONTEXT)(const void *display, const void *fbconfig,
                                                        uint32_t type, GLXContext shared,
                                                        bool direct);
    typedef void(STDCALL *PFNGLXMAKECONTEXTCURRENT)(const void *display, GLXDrawable draw,
                                                    GLXDrawable read, GLXContext ctx);
    typedef void(STDCALL *PFNGLXSWAPBUFFERS)(const void *display, GLXDrawable drawable);
    typedef HGLRC(STDCALL *PFNWGLCREATECONTEXT)(HDC hdc);
    typedef HGLRC(STDCALL *PFNWGLCREATECONTEXTATTRIBSARB)(HDC hdc, HGLRC hShareContext,
                                                          const int *attribList);
    typedef BOOL(STDCALL *PFNWGLMAKECURRENT)(HDC hdc, HGLRC hglrc);
    typedef void(STDCALL *PFNWGLSWAPBUFFERS)(HDC hdc);
    typedef CGLError(STDCALL *PFNCGLCREATECONTEXT)(CGLPixelFormatObj pix, CGLContextObj share,
                                                   CGLContextObj *ctx);
    typedef CGLError(STDCALL *PFNCGLSETCURRENTCONTEXT)(CGLContextObj ctx);
    typedef void(STDCALL *PFNGLENABLECLIENTSTATE)(uint32_t type);
    typedef void(STDCALL *PFNGLDISABLECLIENTSTATE)(uint32_t type);
    typedef void(STDCALL *PFNGLGETPROGRAMBINARYOES)(ProgramId program, int32_t buffer_size,
                                                    int32_t *bytes_written, uint32_t *binary_format,
                                                    void *binary);
    typedef void(STDCALL *PFNGLPROGRAMBINARYOES)(ProgramId program, uint32_t binary_format,
                                                 const void *binary, int32_t binary_size);
    typedef void(STDCALL *PFNGLSTARTTILINGQCOM)(int32_t x, int32_t y, int32_t width, int32_t height,
                                                uint32_t preserveMask);
    typedef void(STDCALL *PFNGLENDTILINGQCOM)(uint32_t preserve_mask);
    typedef void(STDCALL *PFNGLDISCARDFRAMEBUFFEREXT)(uint32_t target, int32_t numAttachments,
                                                      const uint32_t *attachments);
    typedef void(STDCALL *PFNGLINSERTEVENTMARKEREXT)(int32_t length, const char *marker);
    typedef void(STDCALL *PFNGLPUSHGROUPMARKEREXT)(int32_t length, const char *marker);
    typedef void(STDCALL *PFNGLPOPGROUPMARKEREXT)();
    typedef void(STDCALL *PFNGLTEXSTORAGE1DEXT)(uint32_t target, int32_t levels, uint32_t format,
                                                int32_t width);
    typedef void(STDCALL *PFNGLTEXSTORAGE2DEXT)(uint32_t target, int32_t levels, uint32_t format,
                                                int32_t width, int32_t height);
    typedef void(STDCALL *PFNGLTEXSTORAGE3DEXT)(uint32_t target, int32_t levels, uint32_t format,
                                                int32_t width, int32_t height, int32_t depth);
    typedef void(STDCALL *PFNGLTEXTURESTORAGE1DEXT)(TextureId texture, uint32_t target,
                                                    int32_t levels, uint32_t format, int32_t width);
    typedef void(STDCALL *PFNGLTEXTURESTORAGE2DEXT)(TextureId texture, uint32_t target,
                                                    int32_t levels, uint32_t format, int32_t width,
                                                    int32_t height);
    typedef void(STDCALL *PFNGLTEXTURESTORAGE3DEXT)(TextureId texture, uint32_t target,
                                                    int32_t levels, uint32_t format, int32_t width,
                                                    int32_t height, int32_t depth);
    typedef void(STDCALL *PFNGLGENVERTEXARRAYSOES)(int32_t count, VertexArrayId *arrays);
    typedef void(STDCALL *PFNGLBINDVERTEXARRAYOES)(VertexArrayId array);
    typedef void(STDCALL *PFNGLDELETEVERTEXARRAYSOES)(int32_t count, const VertexArrayId *arrays);
    typedef bool(STDCALL *PFNGLISVERTEXARRAYOES)(VertexArrayId array);
    typedef void(STDCALL *PFNGLEGLIMAGETARGETTEXTURE2DOES)(uint32_t target, ImageOES image);
    typedef void(STDCALL *PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOES)(uint32_t target,
                                                                     TexturePointer image);
    typedef uint32_t(STDCALL *PFNGLGETGRAPHICSRESETSTATUSEXT)();
    typedef void(STDCALL *PFNGLBINDATTRIBLOCATION)(ProgramId program, AttributeLocation location,
                                                   const char *name);
    typedef void(STDCALL *PFNGLBLENDFUNC)(uint32_t src_factor, uint32_t dst_factor);
    typedef void(STDCALL *PFNGLBLENDFUNCSEPARATE)(uint32_t src_factor_rgb, uint32_t dst_factor_rgb,
                                                  uint32_t src_factor_alpha,
                                                  uint32_t dst_factor_alpha);
    typedef void(STDCALL *PFNGLBLENDEQUATION)(uint32_t equation);
    typedef void(STDCALL *PFNGLBLENDEQUATIONSEPARATE)(uint32_t rgb, uint32_t alpha);
    typedef void(STDCALL *PFNGLBLENDCOLOR)(float red, float green, float blue, float alpha);
    typedef void(STDCALL *PFNGLENABLEVERTEXATTRIBARRAY)(AttributeLocation location);
    typedef void(STDCALL *PFNGLDISABLEVERTEXATTRIBARRAY)(AttributeLocation location);
    typedef void(STDCALL *PFNGLVERTEXATTRIBPOINTER)(AttributeLocation location, int32_t size,
                                                    uint32_t type, bool normalized, int32_t stride,
                                                    VertexPointer data);
    typedef void(STDCALL *PFNGLGETACTIVEATTRIB)(ProgramId program, AttributeLocation location,
                                                int32_t buffer_size, int32_t *buffer_bytes_written,
                                                int32_t *vector_count, uint32_t *type, char *name);
    typedef void(STDCALL *PFNGLGETACTIVEUNIFORM)(ProgramId program, int32_t location,
                                                 int32_t buffer_size, int32_t *buffer_bytes_written,
                                                 int32_t *size, uint32_t *type, char *name);
    typedef uint32_t(STDCALL *PFNGLGETERROR)();
    typedef void(STDCALL *PFNGLGETPROGRAMIV)(ProgramId program, uint32_t parameter, int32_t *value);
    typedef void(STDCALL *PFNGLGETSHADERIV)(ShaderId shader, uint32_t parameter, int32_t *value);
    typedef UniformLocation(STDCALL *PFNGLGETUNIFORMLOCATION)(ProgramId program, const char *name);
    typedef AttributeLocation(STDCALL *PFNGLGETATTRIBLOCATION)(ProgramId program, const char *name);
    typedef void(STDCALL *PFNGLPIXELSTOREI)(uint32_t parameter, int32_t value);
    typedef void(STDCALL *PFNGLTEXPARAMETERI)(uint32_t target, uint32_t parameter, int32_t value);
    typedef void(STDCALL *PFNGLTEXPARAMETERF)(uint32_t target, uint32_t parameter, float value);
    typedef void(STDCALL *PFNGLGETTEXPARAMETERIV)(uint32_t target, uint32_t parameter,
                                                  int32_t *values);
    typedef void(STDCALL *PFNGLGETTEXPARAMETERFV)(uint32_t target, uint32_t parameter,
                                                  float *values);
    typedef void(STDCALL *PFNGLUNIFORM1I)(UniformLocation location, int32_t value);
    typedef void(STDCALL *PFNGLUNIFORM2I)(UniformLocation location, int32_t value0, int32_t value1);
    typedef void(STDCALL *PFNGLUNIFORM3I)(UniformLocation location, int32_t value0, int32_t value1,
                                          int32_t value2);
    typedef void(STDCALL *PFNGLUNIFORM4I)(UniformLocation location, int32_t value0, int32_t value1,
                                          int32_t value2, int32_t value3);
    typedef void(STDCALL *PFNGLUNIFORM1IV)(UniformLocation location, int32_t count,
                                           const int32_t *value);
    typedef void(STDCALL *PFNGLUNIFORM2IV)(UniformLocation location, int32_t count,
                                           const int32_t *value);
    typedef void(STDCALL *PFNGLUNIFORM3IV)(UniformLocation location, int32_t count,
                                           const int32_t *value);
    typedef void(STDCALL *PFNGLUNIFORM4IV)(UniformLocation location, int32_t count,
                                           const int32_t *value);
    typedef void(STDCALL *PFNGLUNIFORM1F)(UniformLocation location, float value);
    typedef void(STDCALL *PFNGLUNIFORM2F)(UniformLocation location, float value0, float value1);
    typedef void(STDCALL *PFNGLUNIFORM3F)(UniformLocation location, float value0, float value1,
                                          float value2);
    typedef void(STDCALL *PFNGLUNIFORM4F)(UniformLocation location, float value0, float value1,
                                          float value2, float value3);
    typedef void(STDCALL *PFNGLUNIFORM1FV)(UniformLocation location, int32_t count,
                                           const float *value);
    typedef void(STDCALL *PFNGLUNIFORM2FV)(UniformLocation location, int32_t count,
                                           const float *value);
    typedef void(STDCALL *PFNGLUNIFORM3FV)(UniformLocation location, int32_t count,
                                           const float *value);
    typedef void(STDCALL *PFNGLUNIFORM4FV)(UniformLocation location, int32_t count,
                                           const float *value);
    typedef void(STDCALL *PFNGLUNIFORMMATRIX2FV)(UniformLocation location, int32_t count,
                                                 bool transpose, const float *values);
    typedef void(STDCALL *PFNGLUNIFORMMATRIX3FV)(UniformLocation location, int32_t count,
                                                 bool transpose, const float *values);
    typedef void(STDCALL *PFNGLUNIFORMMATRIX4FV)(UniformLocation location, int32_t count,
                                                 bool transpose, const float *values);
    typedef void(STDCALL *PFNGLGETUNIFORMFV)(ProgramId program, UniformLocation location,
                                             const float *values);
    typedef void(STDCALL *PFNGLGETUNIFORMIV)(ProgramId program, UniformLocation location,
                                             const int32_t *values);
    typedef void(STDCALL *PFNGLVERTEXATTRIB1F)(AttributeLocation location, float value0);
    typedef void(STDCALL *PFNGLVERTEXATTRIB2F)(AttributeLocation location, float value0,
                                               float value1);
    typedef void(STDCALL *PFNGLVERTEXATTRIB3F)(AttributeLocation location, float value0,
                                               float value1, float value2);
    typedef void(STDCALL *PFNGLVERTEXATTRIB4F)(AttributeLocation location, float value0,
                                               float value1, float value2, float value3);
    typedef void(STDCALL *PFNGLVERTEXATTRIB1FV)(AttributeLocation location, const float *value);
    typedef void(STDCALL *PFNGLVERTEXATTRIB2FV)(AttributeLocation location, const float *value);
    typedef void(STDCALL *PFNGLVERTEXATTRIB3FV)(AttributeLocation location, const float *value);
    typedef void(STDCALL *PFNGLVERTEXATTRIB4FV)(AttributeLocation location, const float *value);
    typedef void(STDCALL *PFNGLGETSHADERPRECISIONFORMAT)(uint32_t shader_type,
                                                         uint32_t precision_type, int32_t *range,
                                                         int32_t *precision);
    typedef void(STDCALL *PFNGLDEPTHMASK)(bool enabled);
    typedef void(STDCALL *PFNGLDEPTHFUNC)(uint32_t function);
    typedef void(STDCALL *PFNGLDEPTHRANGEF)(float near, float far);
    typedef void(STDCALL *PFNGLCOLORMASK)(bool red, bool green, bool blue, bool alpha);
    typedef void(STDCALL *PFNGLSTENCILMASK)(uint32_t mask);
    typedef void(STDCALL *PFNGLSTENCILMASKSEPARATE)(uint32_t face, uint32_t mask);
    typedef void(STDCALL *PFNGLSTENCILFUNCSEPARATE)(uint32_t face, uint32_t function,
                                                    int32_t reference_value, int32_t mask);
    typedef void(STDCALL *PFNGLSTENCILOPSEPARATE)(uint32_t face, uint32_t stencil_fail,
                                                  uint32_t stencil_pass_depth_fail,
                                                  uint32_t stencil_pass_depth_pass);
    typedef void(STDCALL *PFNGLFRONTFACE)(uint32_t orientation);
    typedef void(STDCALL *PFNGLVIEWPORT)(int32_t x, int32_t y, int32_t width, int32_t height);
    typedef void(STDCALL *PFNGLSCISSOR)(int32_t x, int32_t y, int32_t width, int32_t height);
    typedef void(STDCALL *PFNGLACTIVETEXTURE)(uint32_t unit);
    typedef void(STDCALL *PFNGLGENTEXTURES)(int32_t count, TextureId *textures);
    typedef void(STDCALL *PFNGLDELETETEXTURES)(int32_t count, const TextureId *textures);
    typedef bool(STDCALL *PFNGLISTEXTURE)(TextureId texture);
    typedef void(STDCALL *PFNGLBINDTEXTURE)(uint32_t target, TextureId texture);
    typedef void(STDCALL *PFNGLTEXIMAGE2D)(uint32_t target, int32_t level, uint32_t internal_format,
                                           int32_t width, int32_t height, int32_t border,
                                           uint32_t format, uint32_t type, TexturePointer data);
    typedef void(STDCALL *PFNGLTEXSUBIMAGE2D)(uint32_t target, int32_t level, int32_t xoffset,
                                              int32_t yoffset, int32_t width, int32_t height,
                                              uint32_t format, uint32_t type, TexturePointer data);
    typedef void(STDCALL *PFNGLCOPYTEXIMAGE2D)(uint32_t target, int32_t level, uint32_t format,
                                               int32_t x, int32_t y, int32_t width, int32_t height,
                                               int32_t border);
    typedef void(STDCALL *PFNGLCOPYTEXSUBIMAGE2D)(uint32_t target, int32_t level, int32_t xoffset,
                                                  int32_t yoffset, int32_t x, int32_t y,
                                                  int32_t width, int32_t height);
    typedef void(STDCALL *PFNGLCOMPRESSEDTEXIMAGE2D)(uint32_t target, int32_t level,
                                                     uint32_t format, int32_t width, int32_t height,
                                                     int32_t border, int32_t image_size,
                                                     TexturePointer data);
    typedef void(STDCALL *PFNGLCOMPRESSEDTEXSUBIMAGE2D)(uint32_t target, int32_t level,
                                                        int32_t xoffset, int32_t yoffset,
                                                        int32_t width, int32_t height,
                                                        uint32_t format, int32_t image_size,
                                                        TexturePointer data);
    typedef void(STDCALL *PFNGLGENERATEMIPMAP)(uint32_t target);
    typedef void(STDCALL *PFNGLREADPIXELS)(int32_t x, int32_t y, int32_t width, int32_t height,
                                           uint32_t format, uint32_t type, void *data);
    typedef void(STDCALL *PFNGLGENFRAMEBUFFERS)(int32_t count, FramebufferId *framebuffers);
    typedef void(STDCALL *PFNGLBINDFRAMEBUFFER)(uint32_t target, FramebufferId framebuffer);
    typedef uint32_t(STDCALL *PFNGLCHECKFRAMEBUFFERSTATUS)(uint32_t target);
    typedef void(STDCALL *PFNGLDELETEFRAMEBUFFERS)(int32_t count,
                                                   const FramebufferId *framebuffers);
    typedef bool(STDCALL *PFNGLISFRAMEBUFFER)(FramebufferId framebuffer);
    typedef void(STDCALL *PFNGLGENRENDERBUFFERS)(int32_t count, RenderbufferId *renderbuffers);
    typedef void(STDCALL *PFNGLBINDRENDERBUFFER)(uint32_t target, RenderbufferId renderbuffer);
    typedef void(STDCALL *PFNGLRENDERBUFFERSTORAGE)(uint32_t target, uint32_t format, int32_t width,
                                                    int32_t height);
    typedef void(STDCALL *PFNGLDELETERENDERBUFFERS)(int32_t count,
                                                    const RenderbufferId *renderbuffers);
    typedef bool(STDCALL *PFNGLISRENDERBUFFER)(RenderbufferId renderbuffer);
    typedef void(STDCALL *PFNGLGETRENDERBUFFERPARAMETERIV)(uint32_t target, uint32_t parameter,
                                                           int32_t *values);
    typedef void(STDCALL *PFNGLGENBUFFERS)(int32_t count, BufferId *buffers);
    typedef void(STDCALL *PFNGLBINDBUFFER)(uint32_t target, BufferId buffer);
    typedef void(STDCALL *PFNGLBUFFERDATA)(uint32_t target, int32_t size, BufferDataPointer data,
                                           uint32_t usage);
    typedef void(STDCALL *PFNGLBUFFERSUBDATA)(uint32_t target, int32_t offset, int32_t size,
                                              const void *data);
    typedef void(STDCALL *PFNGLDELETEBUFFERS)(int32_t count, const BufferId *buffers);
    typedef bool(STDCALL *PFNGLISBUFFER)(BufferId buffer);
    typedef void(STDCALL *PFNGLGETBUFFERPARAMETERIV)(uint32_t target, uint32_t parameter,
                                                     int32_t *value);
    typedef ShaderId(STDCALL *PFNGLCREATESHADER)(uint32_t type);
    typedef void(STDCALL *PFNGLDELETESHADER)(ShaderId shader);
    typedef void(STDCALL *PFNGLSHADERSOURCE)(ShaderId shader, int32_t count, const char **source,
                                             const int32_t *length);
    typedef void(STDCALL *PFNGLSHADERBINARY)(int32_t count, const ShaderId *shaders,
                                             uint32_t binary_format, const void *binary,
                                             int32_t binary_size);
    typedef void(STDCALL *PFNGLGETSHADERINFOLOG)(ShaderId shader, int32_t buffer_length,
                                                 int32_t *string_length_written, char *info);
    typedef void(STDCALL *PFNGLGETSHADERSOURCE)(ShaderId shader, int32_t buffer_length,
                                                int32_t *string_length_written, char *source);
    typedef void(STDCALL *PFNGLRELEASESHADERCOMPILER)();
    typedef void(STDCALL *PFNGLCOMPILESHADER)(ShaderId shader);
    typedef bool(STDCALL *PFNGLISSHADER)(ShaderId shader);
    typedef ProgramId(STDCALL *PFNGLCREATEPROGRAM)();
    typedef void(STDCALL *PFNGLDELETEPROGRAM)(ProgramId program);
    typedef void(STDCALL *PFNGLATTACHSHADER)(ProgramId program, ShaderId shader);
    typedef void(STDCALL *PFNGLDETACHSHADER)(ProgramId program, ShaderId shader);
    typedef void(STDCALL *PFNGLGETATTACHEDSHADERS)(ProgramId program, int32_t buffer_length,
                                                   int32_t *shaders_length_written,
                                                   ShaderId *shaders);
    typedef void(STDCALL *PFNGLLINKPROGRAM)(ProgramId program);
    typedef void(STDCALL *PFNGLGETPROGRAMINFOLOG)(ProgramId program, int32_t buffer_length,
                                                  int32_t *string_length_written, char *info);
    typedef void(STDCALL *PFNGLUSEPROGRAM)(ProgramId program);
    typedef bool(STDCALL *PFNGLISPROGRAM)(ProgramId program);
    typedef void(STDCALL *PFNGLVALIDATEPROGRAM)(ProgramId program);
    typedef void(STDCALL *PFNGLCLEARCOLOR)(float r, float g, float b, float a);
    typedef void(STDCALL *PFNGLCLEARDEPTHF)(float depth);
    typedef void(STDCALL *PFNGLCLEARSTENCIL)(int32_t stencil);
    typedef void(STDCALL *PFNGLCLEAR)(uint32_t mask);
    typedef void(STDCALL *PFNGLCULLFACE)(uint32_t mode);
    typedef void(STDCALL *PFNGLPOLYGONOFFSET)(float scale_factor, float units);
    typedef void(STDCALL *PFNGLLINEWIDTH)(float width);
    typedef void(STDCALL *PFNGLSAMPLECOVERAGE)(float value, bool invert);
    typedef void(STDCALL *PFNGLHINT)(uint32_t target, uint32_t mode);
    typedef void(STDCALL *PFNGLFRAMEBUFFERRENDERBUFFER)(uint32_t framebuffer_target,
                                                        uint32_t framebuffer_attachment,
                                                        uint32_t renderbuffer_target,
                                                        RenderbufferId renderbuffer);
    typedef void(STDCALL *PFNGLFRAMEBUFFERTEXTURE2D)(uint32_t framebuffer_target,
                                                     uint32_t framebuffer_attachment,
                                                     uint32_t texture_target, TextureId texture,
                                                     int32_t level);
    typedef void(STDCALL *PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIV)(uint32_t framebuffer_target,
                                                                    uint32_t attachment,
                                                                    uint32_t parameter,
                                                                    int32_t *value);
    typedef void(STDCALL *PFNGLDRAWELEMENTS)(uint32_t draw_mode, int32_t element_count,
                                             uint32_t indices_type, IndicesPointer indices);
    typedef void(STDCALL *PFNGLDRAWARRAYS)(uint32_t draw_mode, int32_t first_index,
                                           int32_t index_count);
    typedef void(STDCALL *PFNGLFLUSH)();
    typedef void(STDCALL *PFNGLFINISH)();
    typedef void(STDCALL *PFNGLGETBOOLEANV)(uint32_t param, bool *values);
    typedef void(STDCALL *PFNGLGETFLOATV)(uint32_t param, float *values);
    typedef void(STDCALL *PFNGLGETINTEGERV)(uint32_t param, int32_t *values);
    typedef char *(STDCALL *PFNGLGETSTRING)(uint32_t param);
    typedef void(STDCALL *PFNGLENABLE)(uint32_t capability);
    typedef void(STDCALL *PFNGLDISABLE)(uint32_t capability);
    typedef bool(STDCALL *PFNGLISENABLED)(uint32_t capability);
    typedef void *(STDCALL *PFNGLMAPBUFFERRANGE)(uint32_t target, int32_t offset, int32_t length,
                                                 uint32_t access);
    typedef void(STDCALL *PFNGLUNMAPBUFFER)(uint32_t target);
    typedef void(STDCALL *PFNGLINVALIDATEFRAMEBUFFER)(uint32_t target, int32_t count,
                                                      const uint32_t *attachments);
    typedef void(STDCALL *PFNGLRENDERBUFFERSTORAGEMULTISAMPLE)(uint32_t target, int32_t samples,
                                                               uint32_t format, int32_t width,
                                                               int32_t height);
    typedef void(STDCALL *PFNGLBLITFRAMEBUFFER)(int32_t srcX0, int32_t srcY0, int32_t srcX1,
                                                int32_t srcY1, int32_t dstX0, int32_t dstY0,
                                                int32_t dstX1, int32_t dstY1, uint32_t mask,
                                                uint32_t filter);
    typedef void(STDCALL *PFNGLGENQUERIES)(int32_t count, QueryId *queries);
    typedef void(STDCALL *PFNGLBEGINQUERY)(uint32_t target, QueryId query);
    typedef void(STDCALL *PFNGLENDQUERY)(uint32_t target);
    typedef void(STDCALL *PFNGLDELETEQUERIES)(int32_t count, const QueryId *queries);
    typedef bool(STDCALL *PFNGLISQUERY)(QueryId query);
    typedef void(STDCALL *PFNGLGETQUERYIV)(uint32_t target, uint32_t parameter, int32_t *value);
    typedef void(STDCALL *PFNGLGETQUERYOBJECTUIV)(QueryId query, uint32_t parameter,
                                                  uint32_t *value);
    typedef void(STDCALL *PFNGLGENQUERIESEXT)(int32_t count, QueryId *queries);
    typedef void(STDCALL *PFNGLBEGINQUERYEXT)(uint32_t target, QueryId query);
    typedef void(STDCALL *PFNGLENDQUERYEXT)(uint32_t target);
    typedef void(STDCALL *PFNGLDELETEQUERIESEXT)(int32_t count, const QueryId *queries);
    typedef bool(STDCALL *PFNGLISQUERYEXT)(QueryId query);
    typedef void(STDCALL *PFNGLQUERYCOUNTEREXT)(QueryId query, uint32_t target);
    typedef void(STDCALL *PFNGLGETQUERYIVEXT)(uint32_t target, uint32_t parameter, int32_t *value);
    typedef void(STDCALL *PFNGLGETQUERYOBJECTIVEXT)(QueryId query, uint32_t parameter,
                                                    int32_t *value);
    typedef void(STDCALL *PFNGLGETQUERYOBJECTUIVEXT)(QueryId query, uint32_t parameter,
                                                     uint32_t *value);
    typedef void(STDCALL *PFNGLGETQUERYOBJECTI64VEXT)(QueryId query, uint32_t parameter,
                                                      int64_t *value);
    typedef void(STDCALL *PFNGLGETQUERYOBJECTUI64VEXT)(QueryId query, uint32_t parameter,
                                                       uint64_t *value);

    PFNEGLINITIALIZE eglInitialize;
    PFNEGLCREATECONTEXT eglCreateContext;
    PFNEGLMAKECURRENT eglMakeCurrent;
    PFNEGLSWAPBUFFERS eglSwapBuffers;
    PFNEGLQUERYSURFACE eglQuerySurface;
    PFNGLXCREATECONTEXT glXCreateContext;
    PFNGLXCREATENEWCONTEXT glXCreateNewContext;
    PFNGLXMAKECONTEXTCURRENT glXMakeContextCurrent;
    PFNGLXSWAPBUFFERS glXSwapBuffers;
    PFNWGLCREATECONTEXT wglCreateContext;
    PFNWGLCREATECONTEXTATTRIBSARB wglCreateContextAttribsARB;
    PFNWGLMAKECURRENT wglMakeCurrent;
    PFNWGLSWAPBUFFERS wglSwapBuffers;
    PFNCGLCREATECONTEXT CGLCreateContext;
    PFNCGLSETCURRENTCONTEXT CGLSetCurrentContext;
    PFNGLENABLECLIENTSTATE glEnableClientState;
    PFNGLDISABLECLIENTSTATE glDisableClientState;
    PFNGLGETPROGRAMBINARYOES glGetProgramBinaryOES;
    PFNGLPROGRAMBINARYOES glProgramBinaryOES;
    PFNGLSTARTTILINGQCOM glStartTilingQCOM;
    PFNGLENDTILINGQCOM glEndTilingQCOM;
    PFNGLDISCARDFRAMEBUFFEREXT glDiscardFramebufferEXT;
    PFNGLINSERTEVENTMARKEREXT glInsertEventMarkerEXT;
    PFNGLPUSHGROUPMARKEREXT glPushGroupMarkerEXT;
    PFNGLPOPGROUPMARKEREXT glPopGroupMarkerEXT;
    PFNGLTEXSTORAGE1DEXT glTexStorage1DEXT;
    PFNGLTEXSTORAGE2DEXT glTexStorage2DEXT;
    PFNGLTEXSTORAGE3DEXT glTexStorage3DEXT;
    PFNGLTEXTURESTORAGE1DEXT glTextureStorage1DEXT;
    PFNGLTEXTURESTORAGE2DEXT glTextureStorage2DEXT;
    PFNGLTEXTURESTORAGE3DEXT glTextureStorage3DEXT;
    PFNGLGENVERTEXARRAYSOES glGenVertexArraysOES;
    PFNGLBINDVERTEXARRAYOES glBindVertexArrayOES;
    PFNGLDELETEVERTEXARRAYSOES glDeleteVertexArraysOES;
    PFNGLISVERTEXARRAYOES glIsVertexArrayOES;
    PFNGLEGLIMAGETARGETTEXTURE2DOES glEGLImageTargetTexture2DOES;
    PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOES glEGLImageTargetRenderbufferStorageOES;
    PFNGLGETGRAPHICSRESETSTATUSEXT glGetGraphicsResetStatusEXT;
    PFNGLBINDATTRIBLOCATION glBindAttribLocation;
    PFNGLBLENDFUNC glBlendFunc;
    PFNGLBLENDFUNCSEPARATE glBlendFuncSeparate;
    PFNGLBLENDEQUATION glBlendEquation;
    PFNGLBLENDEQUATIONSEPARATE glBlendEquationSeparate;
    PFNGLBLENDCOLOR glBlendColor;
    PFNGLENABLEVERTEXATTRIBARRAY glEnableVertexAttribArray;
    PFNGLDISABLEVERTEXATTRIBARRAY glDisableVertexAttribArray;
    PFNGLVERTEXATTRIBPOINTER glVertexAttribPointer;
    PFNGLGETACTIVEATTRIB glGetActiveAttrib;
    PFNGLGETACTIVEUNIFORM glGetActiveUniform;
    PFNGLGETERROR glGetError;
    PFNGLGETPROGRAMIV glGetProgramiv;
    PFNGLGETSHADERIV glGetShaderiv;
    PFNGLGETUNIFORMLOCATION glGetUniformLocation;
    PFNGLGETATTRIBLOCATION glGetAttribLocation;
    PFNGLPIXELSTOREI glPixelStorei;
    PFNGLTEXPARAMETERI glTexParameteri;
    PFNGLTEXPARAMETERF glTexParameterf;
    PFNGLGETTEXPARAMETERIV glGetTexParameteriv;
    PFNGLGETTEXPARAMETERFV glGetTexParameterfv;
    PFNGLUNIFORM1I glUniform1i;
    PFNGLUNIFORM2I glUniform2i;
    PFNGLUNIFORM3I glUniform3i;
    PFNGLUNIFORM4I glUniform4i;
    PFNGLUNIFORM1IV glUniform1iv;
    PFNGLUNIFORM2IV glUniform2iv;
    PFNGLUNIFORM3IV glUniform3iv;
    PFNGLUNIFORM4IV glUniform4iv;
    PFNGLUNIFORM1F glUniform1f;
    PFNGLUNIFORM2F glUniform2f;
    PFNGLUNIFORM3F glUniform3f;
    PFNGLUNIFORM4F glUniform4f;
    PFNGLUNIFORM1FV glUniform1fv;
    PFNGLUNIFORM2FV glUniform2fv;
    PFNGLUNIFORM3FV glUniform3fv;
    PFNGLUNIFORM4FV glUniform4fv;
    PFNGLUNIFORMMATRIX2FV glUniformMatrix2fv;
    PFNGLUNIFORMMATRIX3FV glUniformMatrix3fv;
    PFNGLUNIFORMMATRIX4FV glUniformMatrix4fv;
    PFNGLGETUNIFORMFV glGetUniformfv;
    PFNGLGETUNIFORMIV glGetUniformiv;
    PFNGLVERTEXATTRIB1F glVertexAttrib1f;
    PFNGLVERTEXATTRIB2F glVertexAttrib2f;
    PFNGLVERTEXATTRIB3F glVertexAttrib3f;
    PFNGLVERTEXATTRIB4F glVertexAttrib4f;
    PFNGLVERTEXATTRIB1FV glVertexAttrib1fv;
    PFNGLVERTEXATTRIB2FV glVertexAttrib2fv;
    PFNGLVERTEXATTRIB3FV glVertexAttrib3fv;
    PFNGLVERTEXATTRIB4FV glVertexAttrib4fv;
    PFNGLGETSHADERPRECISIONFORMAT glGetShaderPrecisionFormat;
    PFNGLDEPTHMASK glDepthMask;
    PFNGLDEPTHFUNC glDepthFunc;
    PFNGLDEPTHRANGEF glDepthRangef;
    PFNGLCOLORMASK glColorMask;
    PFNGLSTENCILMASK glStencilMask;
    PFNGLSTENCILMASKSEPARATE glStencilMaskSeparate;
    PFNGLSTENCILFUNCSEPARATE glStencilFuncSeparate;
    PFNGLSTENCILOPSEPARATE glStencilOpSeparate;
    PFNGLFRONTFACE glFrontFace;
    PFNGLVIEWPORT glViewport;
    PFNGLSCISSOR glScissor;
    PFNGLACTIVETEXTURE glActiveTexture;
    PFNGLGENTEXTURES glGenTextures;
    PFNGLDELETETEXTURES glDeleteTextures;
    PFNGLISTEXTURE glIsTexture;
    PFNGLBINDTEXTURE glBindTexture;
    PFNGLTEXIMAGE2D glTexImage2D;
    PFNGLTEXSUBIMAGE2D glTexSubImage2D;
    PFNGLCOPYTEXIMAGE2D glCopyTexImage2D;
    PFNGLCOPYTEXSUBIMAGE2D glCopyTexSubImage2D;
    PFNGLCOMPRESSEDTEXIMAGE2D glCompressedTexImage2D;
    PFNGLCOMPRESSEDTEXSUBIMAGE2D glCompressedTexSubImage2D;
    PFNGLGENERATEMIPMAP glGenerateMipmap;
    PFNGLREADPIXELS glReadPixels;
    PFNGLGENFRAMEBUFFERS glGenFramebuffers;
    PFNGLBINDFRAMEBUFFER glBindFramebuffer;
    PFNGLCHECKFRAMEBUFFERSTATUS glCheckFramebufferStatus;
    PFNGLDELETEFRAMEBUFFERS glDeleteFramebuffers;
    PFNGLISFRAMEBUFFER glIsFramebuffer;
    PFNGLGENRENDERBUFFERS glGenRenderbuffers;
    PFNGLBINDRENDERBUFFER glBindRenderbuffer;
    PFNGLRENDERBUFFERSTORAGE glRenderbufferStorage;
    PFNGLDELETERENDERBUFFERS glDeleteRenderbuffers;
    PFNGLISRENDERBUFFER glIsRenderbuffer;
    PFNGLGETRENDERBUFFERPARAMETERIV glGetRenderbufferParameteriv;
    PFNGLGENBUFFERS glGenBuffers;
    PFNGLBINDBUFFER glBindBuffer;
    PFNGLBUFFERDATA glBufferData;
    PFNGLBUFFERSUBDATA glBufferSubData;
    PFNGLDELETEBUFFERS glDeleteBuffers;
    PFNGLISBUFFER glIsBuffer;
    PFNGLGETBUFFERPARAMETERIV glGetBufferParameteriv;
    PFNGLCREATESHADER glCreateShader;
    PFNGLDELETESHADER glDeleteShader;
    PFNGLSHADERSOURCE glShaderSource;
    PFNGLSHADERBINARY glShaderBinary;
    PFNGLGETSHADERINFOLOG glGetShaderInfoLog;
    PFNGLGETSHADERSOURCE glGetShaderSource;
    PFNGLRELEASESHADERCOMPILER glReleaseShaderCompiler;
    PFNGLCOMPILESHADER glCompileShader;
    PFNGLISSHADER glIsShader;
    PFNGLCREATEPROGRAM glCreateProgram;
    PFNGLDELETEPROGRAM glDeleteProgram;
    PFNGLATTACHSHADER glAttachShader;
    PFNGLDETACHSHADER glDetachShader;
    PFNGLGETATTACHEDSHADERS glGetAttachedShaders;
    PFNGLLINKPROGRAM glLinkProgram;
    PFNGLGETPROGRAMINFOLOG glGetProgramInfoLog;
    PFNGLUSEPROGRAM glUseProgram;
    PFNGLISPROGRAM glIsProgram;
    PFNGLVALIDATEPROGRAM glValidateProgram;
    PFNGLCLEARCOLOR glClearColor;
    PFNGLCLEARDEPTHF glClearDepthf;
    PFNGLCLEARSTENCIL glClearStencil;
    PFNGLCLEAR glClear;
    PFNGLCULLFACE glCullFace;
    PFNGLPOLYGONOFFSET glPolygonOffset;
    PFNGLLINEWIDTH glLineWidth;
    PFNGLSAMPLECOVERAGE glSampleCoverage;
    PFNGLHINT glHint;
    PFNGLFRAMEBUFFERRENDERBUFFER glFramebufferRenderbuffer;
    PFNGLFRAMEBUFFERTEXTURE2D glFramebufferTexture2D;
    PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIV glGetFramebufferAttachmentParameteriv;
    PFNGLDRAWELEMENTS glDrawElements;
    PFNGLDRAWARRAYS glDrawArrays;
    PFNGLFLUSH glFlush;
    PFNGLFINISH glFinish;
    PFNGLGETBOOLEANV glGetBooleanv;
    PFNGLGETFLOATV glGetFloatv;
    PFNGLGETINTEGERV glGetIntegerv;
    PFNGLGETSTRING glGetString;
    PFNGLENABLE glEnable;
    PFNGLDISABLE glDisable;
    PFNGLISENABLED glIsEnabled;
    PFNGLMAPBUFFERRANGE glMapBufferRange;
    PFNGLUNMAPBUFFER glUnmapBuffer;
    PFNGLINVALIDATEFRAMEBUFFER glInvalidateFramebuffer;
    PFNGLRENDERBUFFERSTORAGEMULTISAMPLE glRenderbufferStorageMultisample;
    PFNGLBLITFRAMEBUFFER glBlitFramebuffer;
    PFNGLGENQUERIES glGenQueries;
    PFNGLBEGINQUERY glBeginQuery;
    PFNGLENDQUERY glEndQuery;
    PFNGLDELETEQUERIES glDeleteQueries;
    PFNGLISQUERY glIsQuery;
    PFNGLGETQUERYIV glGetQueryiv;
    PFNGLGETQUERYOBJECTUIV glGetQueryObjectuiv;
    PFNGLGENQUERIESEXT glGenQueriesEXT;
    PFNGLBEGINQUERYEXT glBeginQueryEXT;
    PFNGLENDQUERYEXT glEndQueryEXT;
    PFNGLDELETEQUERIESEXT glDeleteQueriesEXT;
    PFNGLISQUERYEXT glIsQueryEXT;
    PFNGLQUERYCOUNTEREXT glQueryCounterEXT;
    PFNGLGETQUERYIVEXT glGetQueryivEXT;
    PFNGLGETQUERYOBJECTIVEXT glGetQueryObjectivEXT;
    PFNGLGETQUERYOBJECTUIVEXT glGetQueryObjectuivEXT;
    PFNGLGETQUERYOBJECTI64VEXT glGetQueryObjecti64vEXT;
    PFNGLGETQUERYOBJECTUI64VEXT glGetQueryObjectui64vEXT;
};
}  // namespace gapii

#endif  // GAPII_GLES_IMPORTS_H
