/*
 * Copyright 2015, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY apic. DO NOT EDIT.
 */

#ifndef ANDROID_GFXSPY_TYPES_H
#define ANDROID_GFXSPY_TYPES_H

#include <map>
#include <memory>
#include <stdint.h>

namespace gfxspy {

class Memory {};
class Any {};

// Class forward declarations.
struct Color;
struct Rect;
struct Image;
struct FramebufferAttachable;
struct Renderbuffer;
struct Texture;
struct CubemapLevel;
struct FramebufferAttachmentInfo;
struct Framebuffer;
struct Buffer;
struct Shader;
struct VertexAttribute;
struct Vec2i;
struct Vec3i;
struct Vec4i;
struct Vec2f;
struct Vec3f;
struct Vec4f;
struct Mat2f;
struct Mat3f;
struct Mat4f;
struct UniformValue;
struct Uniform;
struct Program;
struct VertexArray;
struct VertexAttributeArray;
struct Query;
struct BlendState;
struct RasterizerState;
struct ClearState;
struct InternalState;
struct Objects;

// Enums & bitfields
class DrawMode {
public:
    static const uint32_t GL_LINE_LOOP = 2;
    static const uint32_t GL_LINE_STRIP = 3;
    static const uint32_t GL_LINES = 1;
    static const uint32_t GL_POINTS = 0;
    static const uint32_t GL_TRIANGLE_FAN = 6;
    static const uint32_t GL_TRIANGLE_STRIP = 5;
    static const uint32_t GL_TRIANGLES = 4;

    inline DrawMode() : mValue(0) {}
    inline DrawMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class IndicesType {
public:
    static const uint32_t GL_UNSIGNED_BYTE = 5121;
    static const uint32_t GL_UNSIGNED_SHORT = 5123;
    static const uint32_t GL_UNSIGNED_INT = 5125;

    inline IndicesType() : mValue(0) {}
    inline IndicesType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureTarget_GLES_1_1 {
public:
    static const uint32_t GL_TEXTURE_2D = 3553;

    inline TextureTarget_GLES_1_1() : mValue(0) {}
    inline TextureTarget_GLES_1_1(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureTarget_GLES_2_0 {
public:
    static const uint32_t GL_TEXTURE_CUBE_MAP = 34067;

    inline TextureTarget_GLES_2_0() : mValue(0) {}
    inline TextureTarget_GLES_2_0(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureTarget_OES_EGL_image_external {
public:
    static const uint32_t GL_TEXTURE_EXTERNAL_OES = 36197;

    inline TextureTarget_OES_EGL_image_external() : mValue(0) {}
    inline TextureTarget_OES_EGL_image_external(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureTarget {
public:
    static const uint32_t GL_TEXTURE_2D = 3553;
    static const uint32_t GL_TEXTURE_CUBE_MAP = 34067;
    static const uint32_t GL_TEXTURE_EXTERNAL_OES = 36197;

    inline TextureTarget() : mValue(0) {}
    inline TextureTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class CubeMapImageTarget {
public:
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 34070;
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 34072;
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 34074;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_X = 34069;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 34071;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 34073;

    inline CubeMapImageTarget() : mValue(0) {}
    inline CubeMapImageTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class Texture2DImageTarget {
public:
    static const uint32_t GL_TEXTURE_2D = 3553;

    inline Texture2DImageTarget() : mValue(0) {}
    inline Texture2DImageTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureImageTarget {
public:
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 34070;
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 34072;
    static const uint32_t GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 34074;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_X = 34069;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 34071;
    static const uint32_t GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 34073;
    static const uint32_t GL_TEXTURE_2D = 3553;

    inline TextureImageTarget() : mValue(0) {}
    inline TextureImageTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BaseTexelFormat {
public:
    static const uint32_t GL_ALPHA = 6406;
    static const uint32_t GL_RGB = 6407;
    static const uint32_t GL_RGBA = 6408;

    inline BaseTexelFormat() : mValue(0) {}
    inline BaseTexelFormat(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TexelFormat_GLES_1_1 {
public:
    static const uint32_t GL_LUMINANCE = 6409;
    static const uint32_t GL_LUMINANCE_ALPHA = 6410;
    static const uint32_t GL_ALPHA = 6406;
    static const uint32_t GL_RGB = 6407;
    static const uint32_t GL_RGBA = 6408;

    inline TexelFormat_GLES_1_1() : mValue(0) {}
    inline TexelFormat_GLES_1_1(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TexelFormat_GLES_3_0 {
public:
    static const uint32_t GL_RED = 6403;
    static const uint32_t GL_RED_INTEGER = 36244;
    static const uint32_t GL_RG = 33319;
    static const uint32_t GL_RG_INTEGER = 33320;
    static const uint32_t GL_RGB_INTEGER = 36248;
    static const uint32_t GL_RGBA_INTEGER = 36249;
    static const uint32_t GL_DEPTH_COMPONENT = 6402;
    static const uint32_t GL_DEPTH_STENCIL = 34041;

    inline TexelFormat_GLES_3_0() : mValue(0) {}
    inline TexelFormat_GLES_3_0(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TexelFormat {
public:
    static const uint32_t GL_LUMINANCE = 6409;
    static const uint32_t GL_LUMINANCE_ALPHA = 6410;
    static const uint32_t GL_ALPHA = 6406;
    static const uint32_t GL_RGB = 6407;
    static const uint32_t GL_RGBA = 6408;
    static const uint32_t GL_RED = 6403;
    static const uint32_t GL_RED_INTEGER = 36244;
    static const uint32_t GL_RG = 33319;
    static const uint32_t GL_RG_INTEGER = 33320;
    static const uint32_t GL_RGB_INTEGER = 36248;
    static const uint32_t GL_RGBA_INTEGER = 36249;
    static const uint32_t GL_DEPTH_COMPONENT = 6402;
    static const uint32_t GL_DEPTH_STENCIL = 34041;

    inline TexelFormat() : mValue(0) {}
    inline TexelFormat(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class RenderbufferFormat {
public:
    static const uint32_t GL_RGBA4 = 32854;
    static const uint32_t GL_RGB5_A1 = 32855;
    static const uint32_t GL_RGB565 = 36194;
    static const uint32_t GL_RGBA8 = 32856;
    static const uint32_t GL_DEPTH_COMPONENT16 = 33189;
    static const uint32_t GL_STENCIL_INDEX8 = 36168;

    inline RenderbufferFormat() : mValue(0) {}
    inline RenderbufferFormat(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class Type_OES_vertex_half_float {
public:
    static const uint32_t GL_HALF_FLOAT_OES = 36193;

    inline Type_OES_vertex_half_float() : mValue(0) {}
    inline Type_OES_vertex_half_float(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class CompressedTexelFormat_OES_compressed_ETC1_RGB8_texture {
public:
    static const uint32_t GL_ETC1_RGB8_OES = 36196;

    inline CompressedTexelFormat_OES_compressed_ETC1_RGB8_texture() : mValue(0) {}
    inline CompressedTexelFormat_OES_compressed_ETC1_RGB8_texture(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class CompressedTexelFormat_AMD_compressed_ATC_texture {
public:
    static const uint32_t GL_ATC_RGB_AMD = 35986;
    static const uint32_t GL_ATC_RGBA_EXPLICIT_ALPHA_AMD = 35987;
    static const uint32_t GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD = 34798;

    inline CompressedTexelFormat_AMD_compressed_ATC_texture() : mValue(0) {}
    inline CompressedTexelFormat_AMD_compressed_ATC_texture(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class CompressedTexelFormat {
public:
    static const uint32_t GL_ETC1_RGB8_OES = 36196;
    static const uint32_t GL_ATC_RGB_AMD = 35986;
    static const uint32_t GL_ATC_RGBA_EXPLICIT_ALPHA_AMD = 35987;
    static const uint32_t GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD = 34798;

    inline CompressedTexelFormat() : mValue(0) {}
    inline CompressedTexelFormat(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ImageTexelFormat {
public:
    static const uint32_t GL_LUMINANCE = 6409;
    static const uint32_t GL_LUMINANCE_ALPHA = 6410;
    static const uint32_t GL_ALPHA = 6406;
    static const uint32_t GL_RGB = 6407;
    static const uint32_t GL_RGBA = 6408;
    static const uint32_t GL_RED = 6403;
    static const uint32_t GL_RED_INTEGER = 36244;
    static const uint32_t GL_RG = 33319;
    static const uint32_t GL_RG_INTEGER = 33320;
    static const uint32_t GL_RGB_INTEGER = 36248;
    static const uint32_t GL_RGBA_INTEGER = 36249;
    static const uint32_t GL_DEPTH_COMPONENT = 6402;
    static const uint32_t GL_DEPTH_STENCIL = 34041;
    static const uint32_t GL_ETC1_RGB8_OES = 36196;
    static const uint32_t GL_ATC_RGB_AMD = 35986;
    static const uint32_t GL_ATC_RGBA_EXPLICIT_ALPHA_AMD = 35987;
    static const uint32_t GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD = 34798;

    inline ImageTexelFormat() : mValue(0) {}
    inline ImageTexelFormat(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TexelType {
public:
    static const uint32_t GL_UNSIGNED_BYTE = 5121;
    static const uint32_t GL_UNSIGNED_SHORT_4_4_4_4 = 32819;
    static const uint32_t GL_UNSIGNED_SHORT_5_5_5_1 = 32820;
    static const uint32_t GL_UNSIGNED_SHORT_5_6_5 = 33635;
    static const uint32_t GL_FLOAT = 5126;

    inline TexelType() : mValue(0) {}
    inline TexelType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferAttachment {
public:
    static const uint32_t GL_COLOR_ATTACHMENT0 = 36064;
    static const uint32_t GL_DEPTH_ATTACHMENT = 36096;
    static const uint32_t GL_STENCIL_ATTACHMENT = 36128;

    inline FramebufferAttachment() : mValue(0) {}
    inline FramebufferAttachment(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferAttachmentType {
public:
    static const uint32_t GL_NONE = 0;
    static const uint32_t GL_RENDERBUFFER = 36161;
    static const uint32_t GL_TEXTURE = 5890;

    inline FramebufferAttachmentType() : mValue(0) {}
    inline FramebufferAttachmentType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferTarget_GLES_2_0 {
public:
    static const uint32_t GL_FRAMEBUFFER = 36160;

    inline FramebufferTarget_GLES_2_0() : mValue(0) {}
    inline FramebufferTarget_GLES_2_0(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferTarget_GLES_3_1 {
public:
    static const uint32_t GL_READ_FRAMEBUFFER = 36008;
    static const uint32_t GL_DRAW_FRAMEBUFFER = 36009;

    inline FramebufferTarget_GLES_3_1() : mValue(0) {}
    inline FramebufferTarget_GLES_3_1(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferTarget {
public:
    static const uint32_t GL_FRAMEBUFFER = 36160;
    static const uint32_t GL_READ_FRAMEBUFFER = 36008;
    static const uint32_t GL_DRAW_FRAMEBUFFER = 36009;

    inline FramebufferTarget() : mValue(0) {}
    inline FramebufferTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferAttachmentParameter {
public:
    static const uint32_t GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 36048;
    static const uint32_t GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 36049;
    static const uint32_t GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 36050;
    static const uint32_t GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 36051;

    inline FramebufferAttachmentParameter() : mValue(0) {}
    inline FramebufferAttachmentParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FramebufferStatus {
public:
    static const uint32_t GL_FRAMEBUFFER_COMPLETE = 36053;
    static const uint32_t GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 36054;
    static const uint32_t GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 36055;
    static const uint32_t GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 36057;
    static const uint32_t GL_FRAMEBUFFER_UNSUPPORTED = 36061;

    inline FramebufferStatus() : mValue(0) {}
    inline FramebufferStatus(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class RenderbufferTarget {
public:
    static const uint32_t GL_RENDERBUFFER = 36161;

    inline RenderbufferTarget() : mValue(0) {}
    inline RenderbufferTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class RenderbufferParameter {
public:
    static const uint32_t GL_RENDERBUFFER_WIDTH = 36162;
    static const uint32_t GL_RENDERBUFFER_HEIGHT = 36163;
    static const uint32_t GL_RENDERBUFFER_INTERNAL_FORMAT = 36164;
    static const uint32_t GL_RENDERBUFFER_RED_SIZE = 36176;
    static const uint32_t GL_RENDERBUFFER_GREEN_SIZE = 36177;
    static const uint32_t GL_RENDERBUFFER_BLUE_SIZE = 36178;
    static const uint32_t GL_RENDERBUFFER_ALPHA_SIZE = 36179;
    static const uint32_t GL_RENDERBUFFER_DEPTH_SIZE = 36180;
    static const uint32_t GL_RENDERBUFFER_STENCIL_SIZE = 36181;

    inline RenderbufferParameter() : mValue(0) {}
    inline RenderbufferParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BufferTarget {
public:
    static const uint32_t GL_ARRAY_BUFFER = 34962;
    static const uint32_t GL_ELEMENT_ARRAY_BUFFER = 34963;

    inline BufferTarget() : mValue(0) {}
    inline BufferTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BufferParameter {
public:
    static const uint32_t GL_BUFFER_SIZE = 34660;
    static const uint32_t GL_BUFFER_USAGE = 34661;

    inline BufferParameter() : mValue(0) {}
    inline BufferParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureUnit {
public:
    static const uint32_t GL_TEXTURE0 = 33984;
    static const uint32_t GL_TEXTURE1 = 33985;
    static const uint32_t GL_TEXTURE2 = 33986;
    static const uint32_t GL_TEXTURE3 = 33987;
    static const uint32_t GL_TEXTURE4 = 33988;
    static const uint32_t GL_TEXTURE5 = 33989;
    static const uint32_t GL_TEXTURE6 = 33990;
    static const uint32_t GL_TEXTURE7 = 33991;
    static const uint32_t GL_TEXTURE8 = 33992;
    static const uint32_t GL_TEXTURE9 = 33993;
    static const uint32_t GL_TEXTURE10 = 33994;
    static const uint32_t GL_TEXTURE11 = 33995;
    static const uint32_t GL_TEXTURE12 = 33996;
    static const uint32_t GL_TEXTURE13 = 33997;
    static const uint32_t GL_TEXTURE14 = 33998;
    static const uint32_t GL_TEXTURE15 = 33999;
    static const uint32_t GL_TEXTURE16 = 34000;
    static const uint32_t GL_TEXTURE17 = 34001;
    static const uint32_t GL_TEXTURE18 = 34002;
    static const uint32_t GL_TEXTURE19 = 34003;
    static const uint32_t GL_TEXTURE20 = 34004;
    static const uint32_t GL_TEXTURE21 = 34005;
    static const uint32_t GL_TEXTURE22 = 34006;
    static const uint32_t GL_TEXTURE23 = 34007;
    static const uint32_t GL_TEXTURE24 = 34008;
    static const uint32_t GL_TEXTURE25 = 34009;
    static const uint32_t GL_TEXTURE26 = 34010;
    static const uint32_t GL_TEXTURE27 = 34011;
    static const uint32_t GL_TEXTURE28 = 34012;
    static const uint32_t GL_TEXTURE29 = 34013;
    static const uint32_t GL_TEXTURE30 = 34014;
    static const uint32_t GL_TEXTURE31 = 34015;

    inline TextureUnit() : mValue(0) {}
    inline TextureUnit(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BufferUsage {
public:
    static const uint32_t GL_DYNAMIC_DRAW = 35048;
    static const uint32_t GL_STATIC_DRAW = 35044;
    static const uint32_t GL_STREAM_DRAW = 35040;

    inline BufferUsage() : mValue(0) {}
    inline BufferUsage(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ShaderType {
public:
    static const uint32_t GL_VERTEX_SHADER = 35633;
    static const uint32_t GL_FRAGMENT_SHADER = 35632;

    inline ShaderType() : mValue(0) {}
    inline ShaderType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StateVariable_GLES_2_0 {
public:
    static const uint32_t GL_ACTIVE_TEXTURE = 34016;
    static const uint32_t GL_ALIASED_LINE_WIDTH_RANGE = 33902;
    static const uint32_t GL_ALIASED_POINT_SIZE_RANGE = 33901;
    static const uint32_t GL_ALPHA_BITS = 3413;
    static const uint32_t GL_ARRAY_BUFFER_BINDING = 34964;
    static const uint32_t GL_BLEND = 3042;
    static const uint32_t GL_BLEND_COLOR = 32773;
    static const uint32_t GL_BLEND_DST_ALPHA = 32970;
    static const uint32_t GL_BLEND_DST_RGB = 32968;
    static const uint32_t GL_BLEND_EQUATION_ALPHA = 34877;
    static const uint32_t GL_BLEND_EQUATION_RGB = 32777;
    static const uint32_t GL_BLEND_SRC_ALPHA = 32971;
    static const uint32_t GL_BLEND_SRC_RGB = 32969;
    static const uint32_t GL_BLUE_BITS = 3412;
    static const uint32_t GL_COLOR_CLEAR_VALUE = 3106;
    static const uint32_t GL_COLOR_WRITEMASK = 3107;
    static const uint32_t GL_COMPRESSED_TEXTURE_FORMATS = 34467;
    static const uint32_t GL_CULL_FACE = 2884;
    static const uint32_t GL_CULL_FACE_MODE = 2885;
    static const uint32_t GL_CURRENT_PROGRAM = 35725;
    static const uint32_t GL_DEPTH_BITS = 3414;
    static const uint32_t GL_DEPTH_CLEAR_VALUE = 2931;
    static const uint32_t GL_DEPTH_FUNC = 2932;
    static const uint32_t GL_DEPTH_RANGE = 2928;
    static const uint32_t GL_DEPTH_TEST = 2929;
    static const uint32_t GL_DEPTH_WRITEMASK = 2930;
    static const uint32_t GL_DITHER = 3024;
    static const uint32_t GL_ELEMENT_ARRAY_BUFFER_BINDING = 34965;
    static const uint32_t GL_FRAMEBUFFER_BINDING = 36006;
    static const uint32_t GL_FRONT_FACE = 2886;
    static const uint32_t GL_GENERATE_MIPMAP_HINT = 33170;
    static const uint32_t GL_GREEN_BITS = 3411;
    static const uint32_t GL_IMPLEMENTATION_COLOR_READ_FORMAT = 35739;
    static const uint32_t GL_IMPLEMENTATION_COLOR_READ_TYPE = 35738;
    static const uint32_t GL_LINE_WIDTH = 2849;
    static const uint32_t GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 35661;
    static const uint32_t GL_MAX_CUBE_MAP_TEXTURE_SIZE = 34076;
    static const uint32_t GL_MAX_FRAGMENT_UNIFORM_VECTORS = 36349;
    static const uint32_t GL_MAX_RENDERBUFFER_SIZE = 34024;
    static const uint32_t GL_MAX_TEXTURE_IMAGE_UNITS = 34930;
    static const uint32_t GL_MAX_TEXTURE_SIZE = 3379;
    static const uint32_t GL_MAX_VARYING_VECTORS = 36348;
    static const uint32_t GL_MAX_VERTEX_ATTRIBS = 34921;
    static const uint32_t GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 35660;
    static const uint32_t GL_MAX_VERTEX_UNIFORM_VECTORS = 36347;
    static const uint32_t GL_MAX_VIEWPORT_DIMS = 3386;
    static const uint32_t GL_NUM_COMPRESSED_TEXTURE_FORMATS = 34466;
    static const uint32_t GL_NUM_SHADER_BINARY_FORMATS = 36345;
    static const uint32_t GL_PACK_ALIGNMENT = 3333;
    static const uint32_t GL_POLYGON_OFFSET_FACTOR = 32824;
    static const uint32_t GL_POLYGON_OFFSET_FILL = 32823;
    static const uint32_t GL_POLYGON_OFFSET_UNITS = 10752;
    static const uint32_t GL_RED_BITS = 3410;
    static const uint32_t GL_RENDERBUFFER_BINDING = 36007;
    static const uint32_t GL_SAMPLE_ALPHA_TO_COVERAGE = 32926;
    static const uint32_t GL_SAMPLE_BUFFERS = 32936;
    static const uint32_t GL_SAMPLE_COVERAGE = 32928;
    static const uint32_t GL_SAMPLE_COVERAGE_INVERT = 32939;
    static const uint32_t GL_SAMPLE_COVERAGE_VALUE = 32938;
    static const uint32_t GL_SAMPLES = 32937;
    static const uint32_t GL_SCISSOR_BOX = 3088;
    static const uint32_t GL_SCISSOR_TEST = 3089;
    static const uint32_t GL_SHADER_BINARY_FORMATS = 36344;
    static const uint32_t GL_SHADER_COMPILER = 36346;
    static const uint32_t GL_STENCIL_BACK_FAIL = 34817;
    static const uint32_t GL_STENCIL_BACK_FUNC = 34816;
    static const uint32_t GL_STENCIL_BACK_PASS_DEPTH_FAIL = 34818;
    static const uint32_t GL_STENCIL_BACK_PASS_DEPTH_PASS = 34819;
    static const uint32_t GL_STENCIL_BACK_REF = 36003;
    static const uint32_t GL_STENCIL_BACK_VALUE_MASK = 36004;
    static const uint32_t GL_STENCIL_BACK_WRITEMASK = 36005;
    static const uint32_t GL_STENCIL_BITS = 3415;
    static const uint32_t GL_STENCIL_CLEAR_VALUE = 2961;
    static const uint32_t GL_STENCIL_FAIL = 2964;
    static const uint32_t GL_STENCIL_FUNC = 2962;
    static const uint32_t GL_STENCIL_PASS_DEPTH_FAIL = 2965;
    static const uint32_t GL_STENCIL_PASS_DEPTH_PASS = 2966;
    static const uint32_t GL_STENCIL_REF = 2967;
    static const uint32_t GL_STENCIL_TEST = 2960;
    static const uint32_t GL_STENCIL_VALUE_MASK = 2963;
    static const uint32_t GL_STENCIL_WRITEMASK = 2968;
    static const uint32_t GL_SUBPIXEL_BITS = 3408;
    static const uint32_t GL_TEXTURE_BINDING_2D = 32873;
    static const uint32_t GL_TEXTURE_BINDING_CUBE_MAP = 34068;
    static const uint32_t GL_UNPACK_ALIGNMENT = 3317;
    static const uint32_t GL_VIEWPORT = 2978;

    inline StateVariable_GLES_2_0() : mValue(0) {}
    inline StateVariable_GLES_2_0(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StateVariable_GLES_3_1 {
public:
    static const uint32_t GL_READ_FRAMEBUFFER_BINDING = 36010;

    inline StateVariable_GLES_3_1() : mValue(0) {}
    inline StateVariable_GLES_3_1(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StateVariable_EXT_texture_filter_anisotropic {
public:
    static const uint32_t GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 34047;

    inline StateVariable_EXT_texture_filter_anisotropic() : mValue(0) {}
    inline StateVariable_EXT_texture_filter_anisotropic(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StateVariable_EXT_disjoint_timer_query {
public:
    static const uint32_t GL_GPU_DISJOINT_EXT = 36795;

    inline StateVariable_EXT_disjoint_timer_query() : mValue(0) {}
    inline StateVariable_EXT_disjoint_timer_query(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StateVariable {
public:
    static const uint32_t GL_ACTIVE_TEXTURE = 34016;
    static const uint32_t GL_ALIASED_LINE_WIDTH_RANGE = 33902;
    static const uint32_t GL_ALIASED_POINT_SIZE_RANGE = 33901;
    static const uint32_t GL_ALPHA_BITS = 3413;
    static const uint32_t GL_ARRAY_BUFFER_BINDING = 34964;
    static const uint32_t GL_BLEND = 3042;
    static const uint32_t GL_BLEND_COLOR = 32773;
    static const uint32_t GL_BLEND_DST_ALPHA = 32970;
    static const uint32_t GL_BLEND_DST_RGB = 32968;
    static const uint32_t GL_BLEND_EQUATION_ALPHA = 34877;
    static const uint32_t GL_BLEND_EQUATION_RGB = 32777;
    static const uint32_t GL_BLEND_SRC_ALPHA = 32971;
    static const uint32_t GL_BLEND_SRC_RGB = 32969;
    static const uint32_t GL_BLUE_BITS = 3412;
    static const uint32_t GL_COLOR_CLEAR_VALUE = 3106;
    static const uint32_t GL_COLOR_WRITEMASK = 3107;
    static const uint32_t GL_COMPRESSED_TEXTURE_FORMATS = 34467;
    static const uint32_t GL_CULL_FACE = 2884;
    static const uint32_t GL_CULL_FACE_MODE = 2885;
    static const uint32_t GL_CURRENT_PROGRAM = 35725;
    static const uint32_t GL_DEPTH_BITS = 3414;
    static const uint32_t GL_DEPTH_CLEAR_VALUE = 2931;
    static const uint32_t GL_DEPTH_FUNC = 2932;
    static const uint32_t GL_DEPTH_RANGE = 2928;
    static const uint32_t GL_DEPTH_TEST = 2929;
    static const uint32_t GL_DEPTH_WRITEMASK = 2930;
    static const uint32_t GL_DITHER = 3024;
    static const uint32_t GL_ELEMENT_ARRAY_BUFFER_BINDING = 34965;
    static const uint32_t GL_FRAMEBUFFER_BINDING = 36006;
    static const uint32_t GL_FRONT_FACE = 2886;
    static const uint32_t GL_GENERATE_MIPMAP_HINT = 33170;
    static const uint32_t GL_GREEN_BITS = 3411;
    static const uint32_t GL_IMPLEMENTATION_COLOR_READ_FORMAT = 35739;
    static const uint32_t GL_IMPLEMENTATION_COLOR_READ_TYPE = 35738;
    static const uint32_t GL_LINE_WIDTH = 2849;
    static const uint32_t GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 35661;
    static const uint32_t GL_MAX_CUBE_MAP_TEXTURE_SIZE = 34076;
    static const uint32_t GL_MAX_FRAGMENT_UNIFORM_VECTORS = 36349;
    static const uint32_t GL_MAX_RENDERBUFFER_SIZE = 34024;
    static const uint32_t GL_MAX_TEXTURE_IMAGE_UNITS = 34930;
    static const uint32_t GL_MAX_TEXTURE_SIZE = 3379;
    static const uint32_t GL_MAX_VARYING_VECTORS = 36348;
    static const uint32_t GL_MAX_VERTEX_ATTRIBS = 34921;
    static const uint32_t GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 35660;
    static const uint32_t GL_MAX_VERTEX_UNIFORM_VECTORS = 36347;
    static const uint32_t GL_MAX_VIEWPORT_DIMS = 3386;
    static const uint32_t GL_NUM_COMPRESSED_TEXTURE_FORMATS = 34466;
    static const uint32_t GL_NUM_SHADER_BINARY_FORMATS = 36345;
    static const uint32_t GL_PACK_ALIGNMENT = 3333;
    static const uint32_t GL_POLYGON_OFFSET_FACTOR = 32824;
    static const uint32_t GL_POLYGON_OFFSET_FILL = 32823;
    static const uint32_t GL_POLYGON_OFFSET_UNITS = 10752;
    static const uint32_t GL_RED_BITS = 3410;
    static const uint32_t GL_RENDERBUFFER_BINDING = 36007;
    static const uint32_t GL_SAMPLE_ALPHA_TO_COVERAGE = 32926;
    static const uint32_t GL_SAMPLE_BUFFERS = 32936;
    static const uint32_t GL_SAMPLE_COVERAGE = 32928;
    static const uint32_t GL_SAMPLE_COVERAGE_INVERT = 32939;
    static const uint32_t GL_SAMPLE_COVERAGE_VALUE = 32938;
    static const uint32_t GL_SAMPLES = 32937;
    static const uint32_t GL_SCISSOR_BOX = 3088;
    static const uint32_t GL_SCISSOR_TEST = 3089;
    static const uint32_t GL_SHADER_BINARY_FORMATS = 36344;
    static const uint32_t GL_SHADER_COMPILER = 36346;
    static const uint32_t GL_STENCIL_BACK_FAIL = 34817;
    static const uint32_t GL_STENCIL_BACK_FUNC = 34816;
    static const uint32_t GL_STENCIL_BACK_PASS_DEPTH_FAIL = 34818;
    static const uint32_t GL_STENCIL_BACK_PASS_DEPTH_PASS = 34819;
    static const uint32_t GL_STENCIL_BACK_REF = 36003;
    static const uint32_t GL_STENCIL_BACK_VALUE_MASK = 36004;
    static const uint32_t GL_STENCIL_BACK_WRITEMASK = 36005;
    static const uint32_t GL_STENCIL_BITS = 3415;
    static const uint32_t GL_STENCIL_CLEAR_VALUE = 2961;
    static const uint32_t GL_STENCIL_FAIL = 2964;
    static const uint32_t GL_STENCIL_FUNC = 2962;
    static const uint32_t GL_STENCIL_PASS_DEPTH_FAIL = 2965;
    static const uint32_t GL_STENCIL_PASS_DEPTH_PASS = 2966;
    static const uint32_t GL_STENCIL_REF = 2967;
    static const uint32_t GL_STENCIL_TEST = 2960;
    static const uint32_t GL_STENCIL_VALUE_MASK = 2963;
    static const uint32_t GL_STENCIL_WRITEMASK = 2968;
    static const uint32_t GL_SUBPIXEL_BITS = 3408;
    static const uint32_t GL_TEXTURE_BINDING_2D = 32873;
    static const uint32_t GL_TEXTURE_BINDING_CUBE_MAP = 34068;
    static const uint32_t GL_UNPACK_ALIGNMENT = 3317;
    static const uint32_t GL_VIEWPORT = 2978;
    static const uint32_t GL_READ_FRAMEBUFFER_BINDING = 36010;
    static const uint32_t GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 34047;
    static const uint32_t GL_GPU_DISJOINT_EXT = 36795;

    inline StateVariable() : mValue(0) {}
    inline StateVariable(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FaceMode {
public:
    static const uint32_t GL_FRONT = 1028;
    static const uint32_t GL_BACK = 1029;
    static const uint32_t GL_FRONT_AND_BACK = 1032;

    inline FaceMode() : mValue(0) {}
    inline FaceMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ArrayType_GLES_1_1 {
public:
    static const uint32_t GL_VERTEX_ARRAY = 32884;
    static const uint32_t GL_NORMAL_ARRAY = 32885;
    static const uint32_t GL_COLOR_ARRAY = 32886;
    static const uint32_t GL_TEXTURE_COORD_ARRAY = 32888;

    inline ArrayType_GLES_1_1() : mValue(0) {}
    inline ArrayType_GLES_1_1(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ArrayType_OES_point_size_array {
public:
    static const uint32_t GL_POINT_SIZE_ARRAY_OES = 35740;

    inline ArrayType_OES_point_size_array() : mValue(0) {}
    inline ArrayType_OES_point_size_array(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ArrayType {
public:
    static const uint32_t GL_VERTEX_ARRAY = 32884;
    static const uint32_t GL_NORMAL_ARRAY = 32885;
    static const uint32_t GL_COLOR_ARRAY = 32886;
    static const uint32_t GL_TEXTURE_COORD_ARRAY = 32888;
    static const uint32_t GL_POINT_SIZE_ARRAY_OES = 35740;

    inline ArrayType() : mValue(0) {}
    inline ArrayType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class Capability {
public:
    static const uint32_t GL_BLEND = 3042;
    static const uint32_t GL_CULL_FACE = 2884;
    static const uint32_t GL_DEPTH_TEST = 2929;
    static const uint32_t GL_DITHER = 3024;
    static const uint32_t GL_POLYGON_OFFSET_FILL = 32823;
    static const uint32_t GL_SAMPLE_ALPHA_TO_COVERAGE = 32926;
    static const uint32_t GL_SAMPLE_COVERAGE = 32928;
    static const uint32_t GL_SCISSOR_TEST = 3089;
    static const uint32_t GL_STENCIL_TEST = 2960;
    static const uint32_t GL_VERTEX_ARRAY = 32884;
    static const uint32_t GL_NORMAL_ARRAY = 32885;
    static const uint32_t GL_COLOR_ARRAY = 32886;
    static const uint32_t GL_TEXTURE_COORD_ARRAY = 32888;
    static const uint32_t GL_POINT_SIZE_ARRAY_OES = 35740;

    inline Capability() : mValue(0) {}
    inline Capability(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StringConstant {
public:
    static const uint32_t GL_EXTENSIONS = 7939;
    static const uint32_t GL_RENDERER = 7937;
    static const uint32_t GL_VENDOR = 7936;
    static const uint32_t GL_VERSION = 7938;

    inline StringConstant() : mValue(0) {}
    inline StringConstant(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class VertexAttribType {
public:
    static const uint32_t GL_BYTE = 5120;
    static const uint32_t GL_FIXED = 5132;
    static const uint32_t GL_FLOAT = 5126;
    static const uint32_t GL_SHORT = 5122;
    static const uint32_t GL_UNSIGNED_BYTE = 5121;
    static const uint32_t GL_UNSIGNED_SHORT = 5123;
    static const uint32_t GL_HALF_FLOAT_OES = 36193;

    inline VertexAttribType() : mValue(0) {}
    inline VertexAttribType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ShaderAttribType {
public:
    static const uint32_t GL_FLOAT = 5126;
    static const uint32_t GL_FLOAT_VEC2 = 35664;
    static const uint32_t GL_FLOAT_VEC3 = 35665;
    static const uint32_t GL_FLOAT_VEC4 = 35666;
    static const uint32_t GL_FLOAT_MAT2 = 35674;
    static const uint32_t GL_FLOAT_MAT3 = 35675;
    static const uint32_t GL_FLOAT_MAT4 = 35676;

    inline ShaderAttribType() : mValue(0) {}
    inline ShaderAttribType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ShaderUniformType {
public:
    static const uint32_t GL_FLOAT = 5126;
    static const uint32_t GL_FLOAT_VEC2 = 35664;
    static const uint32_t GL_FLOAT_VEC3 = 35665;
    static const uint32_t GL_FLOAT_VEC4 = 35666;
    static const uint32_t GL_INT = 5124;
    static const uint32_t GL_INT_VEC2 = 35667;
    static const uint32_t GL_INT_VEC3 = 35668;
    static const uint32_t GL_INT_VEC4 = 35669;
    static const uint32_t GL_BOOL = 35670;
    static const uint32_t GL_BOOL_VEC2 = 35671;
    static const uint32_t GL_BOOL_VEC3 = 35672;
    static const uint32_t GL_BOOL_VEC4 = 35673;
    static const uint32_t GL_FLOAT_MAT2 = 35674;
    static const uint32_t GL_FLOAT_MAT3 = 35675;
    static const uint32_t GL_FLOAT_MAT4 = 35676;
    static const uint32_t GL_SAMPLER_2D = 35678;
    static const uint32_t GL_SAMPLER_CUBE = 35680;

    inline ShaderUniformType() : mValue(0) {}
    inline ShaderUniformType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class Error {
public:
    static const uint32_t GL_NO_ERROR = 0;
    static const uint32_t GL_INVALID_ENUM = 1280;
    static const uint32_t GL_INVALID_VALUE = 1281;
    static const uint32_t GL_INVALID_OPERATION = 1282;
    static const uint32_t GL_INVALID_FRAMEBUFFER_OPERATION = 1286;
    static const uint32_t GL_OUT_OF_MEMORY = 1285;

    inline Error() : mValue(0) {}
    inline Error(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class HintTarget {
public:
    static const uint32_t GL_GENERATE_MIPMAP_HINT = 33170;

    inline HintTarget() : mValue(0) {}
    inline HintTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class HintMode {
public:
    static const uint32_t GL_DONT_CARE = 4352;
    static const uint32_t GL_FASTEST = 4353;
    static const uint32_t GL_NICEST = 4354;

    inline HintMode() : mValue(0) {}
    inline HintMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class DiscardFramebufferAttachment {
public:
    static const uint32_t GL_COLOR_EXT = 6144;
    static const uint32_t GL_DEPTH_EXT = 6145;
    static const uint32_t GL_STENCIL_EXT = 6146;

    inline DiscardFramebufferAttachment() : mValue(0) {}
    inline DiscardFramebufferAttachment(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ProgramParameter {
public:
    static const uint32_t GL_DELETE_STATUS = 35712;
    static const uint32_t GL_LINK_STATUS = 35714;
    static const uint32_t GL_VALIDATE_STATUS = 35715;
    static const uint32_t GL_INFO_LOG_LENGTH = 35716;
    static const uint32_t GL_ATTACHED_SHADERS = 35717;
    static const uint32_t GL_ACTIVE_ATTRIBUTES = 35721;
    static const uint32_t GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 35722;
    static const uint32_t GL_ACTIVE_UNIFORMS = 35718;
    static const uint32_t GL_ACTIVE_UNIFORM_MAX_LENGTH = 35719;

    inline ProgramParameter() : mValue(0) {}
    inline ProgramParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ShaderParameter {
public:
    static const uint32_t GL_SHADER_TYPE = 35663;
    static const uint32_t GL_DELETE_STATUS = 35712;
    static const uint32_t GL_COMPILE_STATUS = 35713;
    static const uint32_t GL_INFO_LOG_LENGTH = 35716;
    static const uint32_t GL_SHADER_SOURCE_LENGTH = 35720;

    inline ShaderParameter() : mValue(0) {}
    inline ShaderParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class PixelStoreParameter {
public:
    static const uint32_t GL_PACK_ALIGNMENT = 3333;
    static const uint32_t GL_UNPACK_ALIGNMENT = 3317;

    inline PixelStoreParameter() : mValue(0) {}
    inline PixelStoreParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureParameter_FilterMode {
public:
    static const uint32_t GL_TEXTURE_MIN_FILTER = 10241;
    static const uint32_t GL_TEXTURE_MAG_FILTER = 10240;

    inline TextureParameter_FilterMode() : mValue(0) {}
    inline TextureParameter_FilterMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureParameter_WrapMode {
public:
    static const uint32_t GL_TEXTURE_WRAP_S = 10242;
    static const uint32_t GL_TEXTURE_WRAP_T = 10243;

    inline TextureParameter_WrapMode() : mValue(0) {}
    inline TextureParameter_WrapMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureParameter_EXT_texture_filter_anisotropic {
public:
    static const uint32_t GL_TEXTURE_MAX_ANISOTROPY_EXT = 34046;

    inline TextureParameter_EXT_texture_filter_anisotropic() : mValue(0) {}
    inline TextureParameter_EXT_texture_filter_anisotropic(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureParameter_SwizzleMode {
public:
    static const uint32_t GL_TEXTURE_SWIZZLE_R = 36418;
    static const uint32_t GL_TEXTURE_SWIZZLE_G = 36419;
    static const uint32_t GL_TEXTURE_SWIZZLE_B = 36420;
    static const uint32_t GL_TEXTURE_SWIZZLE_A = 36421;

    inline TextureParameter_SwizzleMode() : mValue(0) {}
    inline TextureParameter_SwizzleMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureParameter {
public:
    static const uint32_t GL_TEXTURE_MIN_FILTER = 10241;
    static const uint32_t GL_TEXTURE_MAG_FILTER = 10240;
    static const uint32_t GL_TEXTURE_WRAP_S = 10242;
    static const uint32_t GL_TEXTURE_WRAP_T = 10243;
    static const uint32_t GL_TEXTURE_SWIZZLE_R = 36418;
    static const uint32_t GL_TEXTURE_SWIZZLE_G = 36419;
    static const uint32_t GL_TEXTURE_SWIZZLE_B = 36420;
    static const uint32_t GL_TEXTURE_SWIZZLE_A = 36421;
    static const uint32_t GL_TEXTURE_MAX_ANISOTROPY_EXT = 34046;

    inline TextureParameter() : mValue(0) {}
    inline TextureParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureFilterMode {
public:
    static const uint32_t GL_NEAREST = 9728;
    static const uint32_t GL_LINEAR = 9729;
    static const uint32_t GL_NEAREST_MIPMAP_NEAREST = 9984;
    static const uint32_t GL_LINEAR_MIPMAP_NEAREST = 9985;
    static const uint32_t GL_NEAREST_MIPMAP_LINEAR = 9986;
    static const uint32_t GL_LINEAR_MIPMAP_LINEAR = 9987;

    inline TextureFilterMode() : mValue(0) {}
    inline TextureFilterMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureWrapMode {
public:
    static const uint32_t GL_CLAMP_TO_EDGE = 33071;
    static const uint32_t GL_MIRRORED_REPEAT = 33648;
    static const uint32_t GL_REPEAT = 10497;

    inline TextureWrapMode() : mValue(0) {}
    inline TextureWrapMode(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TexelComponent {
public:
    static const uint32_t GL_RED = 6403;
    static const uint32_t GL_GREEN = 6404;
    static const uint32_t GL_BLUE = 6405;
    static const uint32_t GL_ALPHA = 6406;

    inline TexelComponent() : mValue(0) {}
    inline TexelComponent(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BlendFactor {
public:
    static const uint32_t GL_ZERO = 0;
    static const uint32_t GL_ONE = 1;
    static const uint32_t GL_SRC_COLOR = 768;
    static const uint32_t GL_ONE_MINUS_SRC_COLOR = 769;
    static const uint32_t GL_DST_COLOR = 774;
    static const uint32_t GL_ONE_MINUS_DST_COLOR = 775;
    static const uint32_t GL_SRC_ALPHA = 770;
    static const uint32_t GL_ONE_MINUS_SRC_ALPHA = 771;
    static const uint32_t GL_DST_ALPHA = 772;
    static const uint32_t GL_ONE_MINUS_DST_ALPHA = 773;
    static const uint32_t GL_CONSTANT_COLOR = 32769;
    static const uint32_t GL_ONE_MINUS_CONSTANT_COLOR = 32770;
    static const uint32_t GL_CONSTANT_ALPHA = 32771;
    static const uint32_t GL_ONE_MINUS_CONSTANT_ALPHA = 32772;
    static const uint32_t GL_SRC_ALPHA_SATURATE = 776;

    inline BlendFactor() : mValue(0) {}
    inline BlendFactor(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class PrecisionType {
public:
    static const uint32_t GL_LOW_FLOAT = 36336;
    static const uint32_t GL_MEDIUM_FLOAT = 36337;
    static const uint32_t GL_HIGH_FLOAT = 36338;
    static const uint32_t GL_LOW_INT = 36339;
    static const uint32_t GL_MEDIUM_INT = 36340;
    static const uint32_t GL_HIGH_INT = 36341;

    inline PrecisionType() : mValue(0) {}
    inline PrecisionType(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TestFunction {
public:
    static const uint32_t GL_NEVER = 512;
    static const uint32_t GL_LESS = 513;
    static const uint32_t GL_EQUAL = 514;
    static const uint32_t GL_LEQUAL = 515;
    static const uint32_t GL_GREATER = 516;
    static const uint32_t GL_NOTEQUAL = 517;
    static const uint32_t GL_GEQUAL = 518;
    static const uint32_t GL_ALWAYS = 519;

    inline TestFunction() : mValue(0) {}
    inline TestFunction(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class StencilAction {
public:
    static const uint32_t GL_KEEP = 7680;
    static const uint32_t GL_ZERO = 0;
    static const uint32_t GL_REPLACE = 7681;
    static const uint32_t GL_INCR = 7682;
    static const uint32_t GL_INCR_WRAP = 34055;
    static const uint32_t GL_DECR = 7683;
    static const uint32_t GL_DECR_WRAP = 34056;
    static const uint32_t GL_INVERT = 5386;

    inline StencilAction() : mValue(0) {}
    inline StencilAction(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class FaceOrientation {
public:
    static const uint32_t GL_CW = 2304;
    static const uint32_t GL_CCW = 2305;

    inline FaceOrientation() : mValue(0) {}
    inline FaceOrientation(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class BlendEquation {
public:
    static const uint32_t GL_FUNC_ADD = 32774;
    static const uint32_t GL_FUNC_SUBTRACT = 32778;
    static const uint32_t GL_FUNC_REVERSE_SUBTRACT = 32779;

    inline BlendEquation() : mValue(0) {}
    inline BlendEquation(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class MapBufferTarget {
public:
    static const uint32_t GL_ARRAY_BUFFER = 34962;
    static const uint32_t GL_COPY_READ_BUFFER = 36662;
    static const uint32_t GL_COPY_WRITE_BUFFER = 36663;
    static const uint32_t GL_ELEMENT_ARRAY_BUFFER = 34963;
    static const uint32_t GL_PIXEL_PACK_BUFFER = 35051;
    static const uint32_t GL_PIXEL_UNPACK_BUFFER = 35052;
    static const uint32_t GL_TRANSFORM_FEEDBACK_BUFFER = 35982;
    static const uint32_t GL_UNIFORM_BUFFER = 35345;

    inline MapBufferTarget() : mValue(0) {}
    inline MapBufferTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ImageTargetTexture_OES_EGL_image {
public:
    static const uint32_t GL_TEXTURE_2D = 3553;

    inline ImageTargetTexture_OES_EGL_image() : mValue(0) {}
    inline ImageTargetTexture_OES_EGL_image(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ImageTargetTexture_OES_EGL_image_external {
public:
    static const uint32_t GL_TEXTURE_EXTERNAL_OES = 36197;

    inline ImageTargetTexture_OES_EGL_image_external() : mValue(0) {}
    inline ImageTargetTexture_OES_EGL_image_external(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ImageTargetTexture {
public:
    static const uint32_t GL_TEXTURE_2D = 3553;
    static const uint32_t GL_TEXTURE_EXTERNAL_OES = 36197;

    inline ImageTargetTexture() : mValue(0) {}
    inline ImageTargetTexture(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ImageTargetRenderbufferStorage {
public:
    static const uint32_t GL_RENDERBUFFER_OES = 36161;

    inline ImageTargetRenderbufferStorage() : mValue(0) {}
    inline ImageTargetRenderbufferStorage(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ResetStatus {
public:
    static const uint32_t GL_NO_ERROR = 0;
    static const uint32_t GL_GUILTY_CONTEXT_RESET_EXT = 33363;
    static const uint32_t GL_INNOCENT_CONTEXT_RESET_EXT = 33364;
    static const uint32_t GL_UNKNOWN_CONTEXT_RESET_EXT = 33365;

    inline ResetStatus() : mValue(0) {}
    inline ResetStatus(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TextureKind {
public:
    static const uint32_t UNDEFINED = 0;
    static const uint32_t TEXTURE2D = 1;
    static const uint32_t CUBEMAP = 2;

    inline TextureKind() : mValue(0) {}
    inline TextureKind(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class VertexAttribSize {
public:
    static const uint32_t SIZE_1 = 1;
    static const uint32_t SIZE_2 = 2;
    static const uint32_t SIZE_3 = 3;
    static const uint32_t SIZE_4 = 4;

    inline VertexAttribSize() : mValue(0) {}
    inline VertexAttribSize(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryParameter_GLES_3 {
public:
    static const uint32_t GL_CURRENT_QUERY = 34917;

    inline QueryParameter_GLES_3() : mValue(0) {}
    inline QueryParameter_GLES_3(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryParameter_EXT_disjoint_timer_query {
public:
    static const uint32_t GL_QUERY_COUNTER_BITS_EXT = 34916;

    inline QueryParameter_EXT_disjoint_timer_query() : mValue(0) {}
    inline QueryParameter_EXT_disjoint_timer_query(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryParameter {
public:
    static const uint32_t GL_CURRENT_QUERY = 34917;
    static const uint32_t GL_QUERY_COUNTER_BITS_EXT = 34916;

    inline QueryParameter() : mValue(0) {}
    inline QueryParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryObjectParameter_GLES_3 {
public:
    static const uint32_t GL_QUERY_RESULT = 34918;
    static const uint32_t GL_QUERY_RESULT_AVAILABLE = 34919;

    inline QueryObjectParameter_GLES_3() : mValue(0) {}
    inline QueryObjectParameter_GLES_3(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryObjectParameter_EXT_disjoint_timer_query {
public:

    inline QueryObjectParameter_EXT_disjoint_timer_query() : mValue(0) {}
    inline QueryObjectParameter_EXT_disjoint_timer_query(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryObjectParameter {
public:
    static const uint32_t GL_QUERY_RESULT = 34918;
    static const uint32_t GL_QUERY_RESULT_AVAILABLE = 34919;

    inline QueryObjectParameter() : mValue(0) {}
    inline QueryObjectParameter(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryTarget_GLES_3 {
public:
    static const uint32_t GL_ANY_SAMPLES_PASSED = 35887;
    static const uint32_t GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 36202;
    static const uint32_t GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 35976;

    inline QueryTarget_GLES_3() : mValue(0) {}
    inline QueryTarget_GLES_3(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryTarget_EXT_disjoint_timer_query {
public:
    static const uint32_t GL_TIME_ELAPSED_EXT = 35007;
    static const uint32_t GL_TIMESTAMP_EXT = 36392;

    inline QueryTarget_EXT_disjoint_timer_query() : mValue(0) {}
    inline QueryTarget_EXT_disjoint_timer_query(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class QueryTarget {
public:
    static const uint32_t GL_ANY_SAMPLES_PASSED = 35887;
    static const uint32_t GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 36202;
    static const uint32_t GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 35976;
    static const uint32_t GL_TIME_ELAPSED_EXT = 35007;
    static const uint32_t GL_TIMESTAMP_EXT = 36392;

    inline QueryTarget() : mValue(0) {}
    inline QueryTarget(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class TilePreserveMaskQCOM {
public:
    static const uint32_t GL_COLOR_BUFFER_BIT0_QCOM = 1;
    static const uint32_t GL_COLOR_BUFFER_BIT1_QCOM = 2;
    static const uint32_t GL_COLOR_BUFFER_BIT2_QCOM = 4;
    static const uint32_t GL_COLOR_BUFFER_BIT3_QCOM = 8;
    static const uint32_t GL_COLOR_BUFFER_BIT4_QCOM = 16;
    static const uint32_t GL_COLOR_BUFFER_BIT5_QCOM = 32;
    static const uint32_t GL_COLOR_BUFFER_BIT6_QCOM = 64;
    static const uint32_t GL_COLOR_BUFFER_BIT7_QCOM = 128;
    static const uint32_t GL_DEPTH_BUFFER_BIT0_QCOM = 256;
    static const uint32_t GL_DEPTH_BUFFER_BIT1_QCOM = 512;
    static const uint32_t GL_DEPTH_BUFFER_BIT2_QCOM = 1024;
    static const uint32_t GL_DEPTH_BUFFER_BIT3_QCOM = 2048;
    static const uint32_t GL_DEPTH_BUFFER_BIT4_QCOM = 4096;
    static const uint32_t GL_DEPTH_BUFFER_BIT5_QCOM = 8192;
    static const uint32_t GL_DEPTH_BUFFER_BIT6_QCOM = 16384;
    static const uint32_t GL_DEPTH_BUFFER_BIT7_QCOM = 32768;
    static const uint32_t GL_STENCIL_BUFFER_BIT0_QCOM = 65536;
    static const uint32_t GL_STENCIL_BUFFER_BIT1_QCOM = 131072;
    static const uint32_t GL_STENCIL_BUFFER_BIT2_QCOM = 262144;
    static const uint32_t GL_STENCIL_BUFFER_BIT3_QCOM = 524288;
    static const uint32_t GL_STENCIL_BUFFER_BIT4_QCOM = 1048576;
    static const uint32_t GL_STENCIL_BUFFER_BIT5_QCOM = 2097152;
    static const uint32_t GL_STENCIL_BUFFER_BIT6_QCOM = 4194304;
    static const uint32_t GL_STENCIL_BUFFER_BIT7_QCOM = 8388608;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT0_QCOM = 16777216;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT1_QCOM = 33554432;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT2_QCOM = 67108864;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT3_QCOM = 134217728;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT4_QCOM = 268435456;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT5_QCOM = 536870912;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT6_QCOM = 1073741824;
    static const uint32_t GL_MULTISAMPLE_BUFFER_BIT7_QCOM = 2147483648;

    inline TilePreserveMaskQCOM() : mValue(0) {}
    inline TilePreserveMaskQCOM(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class ClearMask {
public:
    static const uint32_t GL_COLOR_BUFFER_BIT = 16384;
    static const uint32_t GL_DEPTH_BUFFER_BIT = 256;
    static const uint32_t GL_STENCIL_BUFFER_BIT = 1024;

    inline ClearMask() : mValue(0) {}
    inline ClearMask(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};


class MapBufferRangeAccess {
public:
    static const uint32_t GL_MAP_READ_BIT = 1;
    static const uint32_t GL_MAP_WRITE_BIT = 2;
    static const uint32_t GL_MAP_INVALIDATE_RANGE_BIT = 4;
    static const uint32_t GL_MAP_INVALIDATE_BUFFER_BIT = 8;
    static const uint32_t GL_MAP_FLUSH_EXPLICIT_BIT = 16;
    static const uint32_t GL_MAP_UNSYNCHRONIZED_BIT = 32;

    inline MapBufferRangeAccess() : mValue(0) {}
    inline MapBufferRangeAccess(uint32_t v) : mValue(v) {}
    inline operator uint32_t() const { return mValue; }
private:
    uint32_t mValue;
};



// Pseudonyms
typedef uint32_t RenderbufferId;
typedef uint32_t TextureId;
typedef uint32_t FramebufferId;
typedef uint32_t BufferId;
typedef uint32_t ShaderId;
typedef uint32_t ProgramId;
typedef uint32_t VertexArrayId;
typedef uint32_t QueryId;
typedef int32_t UniformLocation;
typedef int32_t AttributeLocation;
typedef void* IndicesPointer;
typedef void* VertexPointer;
typedef void* TexturePointer;
typedef void* BufferDataPointer;
typedef void* ImageOES;

// Maps
typedef std::map<const char*, AttributeLocation> AttributeLocation_stringMap;
typedef std::map<Capability, bool> Bool_CapabilityMap;
typedef std::map<BufferTarget, BufferId> BufferId_BufferTargetMap;
typedef std::map<BufferId, std::shared_ptr<Buffer>> BufferRef_BufferIdMap;
typedef std::map<int32_t, CubemapLevel> CubemapLevel_s32Map;
typedef std::map<FramebufferAttachment, FramebufferAttachmentInfo> FramebufferAttachmentInfo_FramebufferAttachmentMap;
typedef std::map<FramebufferTarget, FramebufferId> FramebufferId_FramebufferTargetMap;
typedef std::map<FramebufferId, std::shared_ptr<Framebuffer>> FramebufferRef_FramebufferIdMap;
typedef std::map<CubeMapImageTarget, Image> Image_CubeMapImageTargetMap;
typedef std::map<int32_t, Image> Image_s32Map;
typedef std::map<ProgramId, std::shared_ptr<Program>> ProgramRef_ProgramIdMap;
typedef std::map<QueryId, std::shared_ptr<Query>> QueryRef_QueryIdMap;
typedef std::map<RenderbufferTarget, RenderbufferId> RenderbufferId_RenderbufferTargetMap;
typedef std::map<RenderbufferId, std::shared_ptr<Renderbuffer>> RenderbufferRef_RenderbufferIdMap;
typedef std::map<PixelStoreParameter, int32_t> S32_PixelStoreParameterMap;
typedef std::map<ShaderType, ShaderId> ShaderId_ShaderTypeMap;
typedef std::map<ShaderId, std::shared_ptr<Shader>> ShaderRef_ShaderIdMap;
typedef std::map<TextureTarget, TextureId> TextureId_TextureTargetMap;
typedef std::map<TextureUnit, TextureId_TextureTargetMap> TextureId_TextureTargetMap_TextureUnitMap;
typedef std::map<TextureId, std::shared_ptr<Texture>> TextureRef_TextureIdMap;
typedef std::map<FaceMode, uint32_t> U32_FaceModeMap;
typedef std::map<UniformLocation, Uniform> Uniform_UniformLocationMap;
typedef std::map<VertexArrayId, std::shared_ptr<VertexArray>> VertexArrayRef_VertexArrayIdMap;
typedef std::map<AttributeLocation, std::shared_ptr<VertexAttributeArray>> VertexAttributeArrayRef_AttributeLocationMap;
typedef std::map<int32_t, VertexAttribute> VertexAttribute_s32Map;

// Classes
struct Color {
    float Red;
    float Green;
    float Blue;
    float Alpha;
};

struct Rect {
    int32_t X;
    int32_t Y;
    int32_t Width;
    int32_t Height;
};

struct Image {
    int32_t Width;
    int32_t Height;
    Memory Data;
    int32_t Size;
    ImageTexelFormat Format;
};

struct FramebufferAttachable {
};

struct Renderbuffer {
    int32_t Width;
    int32_t Height;
    Memory Data;
    RenderbufferFormat Format;
};

struct Texture {
    TextureKind Kind;
    ImageTexelFormat Format;
    Image_s32Map Texture2D;
    CubemapLevel_s32Map Cubemap;
    TextureFilterMode MagFilter;
    TextureFilterMode MinFilter;
    TextureWrapMode WrapS;
    TextureWrapMode WrapT;
    TexelComponent SwizzleR;
    TexelComponent SwizzleG;
    TexelComponent SwizzleB;
    TexelComponent SwizzleA;
    float MaxAnisotropy;
};

struct CubemapLevel {
    Image_CubeMapImageTargetMap Faces;
};

struct FramebufferAttachmentInfo {
    uint32_t Object;
    FramebufferAttachmentType Type;
    int32_t TextureLevel;
    CubeMapImageTarget CubeMapFace;
};

struct Framebuffer {
    FramebufferAttachmentInfo_FramebufferAttachmentMap Attachments;
};

struct Buffer {
    Memory Data;
    int32_t Size;
    BufferUsage Usage;
};

struct Shader {
    Memory Binary;
    bool Compiled;
    bool Deletable;
    const char* InfoLog;
    const char** Source;
    ShaderType Type;
};

struct VertexAttribute {
    const char* Name;
    int32_t VectorCount;
    ShaderAttribType Type;
};

struct Vec2i {
    int32_t X;
    int32_t Y;
};

struct Vec3i {
    int32_t X;
    int32_t Y;
    int32_t Z;
};

struct Vec4i {
    int32_t X;
    int32_t Y;
    int32_t Z;
    int32_t W;
};

struct Vec2f {
    float X;
    float Y;
};

struct Vec3f {
    float X;
    float Y;
    float Z;
};

struct Vec4f {
    float X;
    float Y;
    float Z;
    float W;
};

struct Mat2f {
    Vec2f Col0;
    Vec2f Col1;
};

struct Mat3f {
    Vec3f Col0;
    Vec3f Col1;
    Vec3f Col2;
};

struct Mat4f {
    Vec4f Col0;
    Vec4f Col1;
    Vec4f Col2;
    Vec4f Col3;
};

struct UniformValue {
    float F32;
    Vec2f Vec2f;
    Vec3f Vec3f;
    Vec4f Vec4f;
    int32_t S32;
    Vec2i Vec2i;
    Vec3i Vec3i;
    Vec4i Vec4i;
    Mat2f Mat2f;
    Mat3f Mat3f;
    Mat4f Mat4f;
};

struct Uniform {
    const char* Name;
    ShaderUniformType Type;
    UniformValue Value;
};

struct Program {
    ShaderId_ShaderTypeMap Shaders;
    bool Linked;
    Memory Binary;
    AttributeLocation_stringMap AttributeBindings;
    VertexAttribute_s32Map Attributes;
    Uniform_UniformLocationMap Uniforms;
    const char* InfoLog;
};

struct VertexArray {
};

struct VertexAttributeArray {
    bool Enabled;
    VertexAttribSize Size;
    VertexAttribType Type;
    bool Normalized;
    int32_t Stride;
    void* Data;
};

struct Query {
};

struct BlendState {
    BlendFactor SrcRgbBlendFactor;
    BlendFactor SrcAlphaBlendFactor;
    BlendFactor DstRgbBlendFactor;
    BlendFactor DstAlphaBlendFactor;
    BlendEquation BlendEquationRgb;
    BlendEquation BlendEquationAlpha;
    Color BlendColor;
};

struct RasterizerState {
    bool DepthMask;
    TestFunction DepthTestFunction;
    float DepthNear;
    float DepthFar;
    bool ColorMaskRed;
    bool ColorMaskGreen;
    bool ColorMaskBlue;
    bool ColorMaskAlpha;
    U32_FaceModeMap StencilMask;
    Rect Viewport;
    Rect Scissor;
    FaceOrientation FrontFace;
    FaceMode CullFace;
    float LineWidth;
    float PolygonOffsetFactor;
    float PolygonOffsetUnits;
    float SampleCoverageValue;
    bool SampleCoverageInvert;
};

struct ClearState {
    Color ClearColor;
    float ClearDepth;
    int32_t ClearStencil;
};

struct InternalState {
    BufferId NilBuffer;
    TextureId NilTexture;
    RenderbufferId NilRenderbuffer;
    FramebufferId Backbuffer;
};

struct Objects {
    RenderbufferRef_RenderbufferIdMap Renderbuffers;
    TextureRef_TextureIdMap Textures;
    FramebufferRef_FramebufferIdMap Framebuffers;
    BufferRef_BufferIdMap Buffers;
    ShaderRef_ShaderIdMap Shaders;
    ProgramRef_ProgramIdMap Programs;
    VertexArrayRef_VertexArrayIdMap VertexArrays;
    QueryRef_QueryIdMap Queries;
};


} // namespace gfxspy
#endif // ANDROID_GFXSPY_TYPES_H
