package gles

import (
	"io"

	"android.googlesource.com/platform/tools/gpu/atom"
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/gfxapi"
	"android.googlesource.com/platform/tools/gpu/replay/builder"
	"android.googlesource.com/platform/tools/gpu/replay/protocol"
	"android.googlesource.com/platform/tools/gpu/replay/value"
)

// transientAtom is an atom generated by a replay transform. It is used as a
// base for atoms that require custom replay handling.
type transientAtom struct{}

func (transientAtom) TypeID() atom.TypeID          { return 0 }
func (transientAtom) ContextID() atom.ContextID    { return 0 }
func (transientAtom) Flags() atom.Flags            { return 0 }
func (transientAtom) Encode(*binary.Encoder) error { return nil }
func (transientAtom) Decode(*binary.Decoder) error { return nil }

// These must conform to the replayer interface in order to be used by
// replayWriter.Write:
var _ = replayer(readFramebufferDepth{})
var _ = replayer(readFramebufferColor{})

// readFramebufferDepth is an atom used to postback the content of the currently
// bound framebuffer's depth attachment.
type readFramebufferDepth struct{ transientAtom }

func (c readFramebufferDepth) replay(id atom.ID, s *state, b *builder.Builder, wantOutput bool) {
	fbW, fbH, err := s.GetFramebufferAttachmentSize(gfxapi.FramebufferAttachmentDepth)
	if err != nil {
		b.EndAtom()
		return
	}

	imageSize := uint64(fbW * fbH * 4)
	addr := b.AllocateTemporaryMemory(imageSize)

	captureImageData(b, int32(fbW), int32(fbH), uint32(TexelFormat_GL_DEPTH_COMPONENT), uint32(TexelType_GL_FLOAT), addr)

	b.Post(addr, imageSize, id,
		func(d *protocol.Decoder) (interface{}, error) {
			buf := make([]byte, imageSize)
			_, err := io.ReadFull(d, buf)
			return buf, err
		},
	)

	b.EndAtom()
}

// readFramebufferColor is an atom used to postback the content of the currently
// bound framebuffer's color attachment.
type readFramebufferColor struct {
	transientAtom
	width, height uint32
}

func (c readFramebufferColor) replay(id atom.ID, s *state, b *builder.Builder, wantOutput bool) {
	imageSize := uint64(c.height * c.width * 4)
	addr := b.AllocateTemporaryMemory(imageSize)

	fbW, fbH, err := s.GetFramebufferAttachmentSize(gfxapi.FramebufferAttachmentColor)
	if err != nil {
		b.EndAtom()
		return
	}

	if c.width == fbW && c.height == fbH {
		captureImageData(b, int32(c.width), int32(c.height), uint32(TexelFormat_GL_RGBA), uint32(IndicesType_GL_UNSIGNED_BYTE), addr)
	} else {
		origReadFramebufferID := b.AllocateTemporaryMemory(4)
		origDrawFramebufferID := b.AllocateTemporaryMemory(4)
		origRenderbufferID := b.AllocateTemporaryMemory(4)
		frameBufferID := b.AllocateTemporaryMemory(4)
		renderBufferID := b.AllocateTemporaryMemory(4)

		b.Push(value.U32(StateVariable_GL_READ_FRAMEBUFFER_BINDING))
		b.Push(origReadFramebufferID)
		b.CallNoPush(funcInfoGlGetIntegerv)

		b.Push(value.U32(StateVariable_GL_FRAMEBUFFER_BINDING))
		b.Push(origDrawFramebufferID)
		b.CallNoPush(funcInfoGlGetIntegerv)

		b.Push(value.U32(StateVariable_GL_RENDERBUFFER_BINDING))
		b.Push(origRenderbufferID)
		b.CallNoPush(funcInfoGlGetIntegerv)

		b.Push(value.S32(1))
		b.Push(frameBufferID)
		b.CallNoPush(funcInfoGlGenFramebuffers)

		b.Push(value.U32(FramebufferTarget_GL_DRAW_FRAMEBUFFER))
		b.Load(protocol.TypeUint32, frameBufferID)
		b.CallNoPush(funcInfoGlBindFramebuffer)

		b.Push(value.S32(1))
		b.Push(renderBufferID)
		b.CallNoPush(funcInfoGlGenRenderbuffers)

		b.Push(value.U32(RenderbufferTarget_GL_RENDERBUFFER))
		b.Load(protocol.TypeUint32, renderBufferID)
		b.CallNoPush(funcInfoGlBindRenderbuffer)

		b.Push(value.U32(RenderbufferTarget_GL_RENDERBUFFER))
		b.Push(value.U32(RenderbufferFormat_GL_RGBA8))
		b.Push(value.S32(c.width))
		b.Push(value.S32(c.height))
		b.CallNoPush(funcInfoGlRenderbufferStorage)

		b.Push(value.U32(FramebufferTarget_GL_DRAW_FRAMEBUFFER))
		b.Push(value.U32(FramebufferAttachment_GL_COLOR_ATTACHMENT0))
		b.Push(value.U32(RenderbufferTarget_GL_RENDERBUFFER))
		b.Load(protocol.TypeUint32, renderBufferID)
		b.CallNoPush(funcInfoGlFramebufferRenderbuffer)

		b.Push(value.S32(0))
		b.Push(value.S32(0))
		b.Push(value.S32(fbW))
		b.Push(value.S32(fbH))
		b.Push(value.S32(0))
		b.Push(value.S32(0))
		b.Push(value.S32(c.width))
		b.Push(value.S32(c.height))
		b.Push(value.U32(ClearMask_GL_COLOR_BUFFER_BIT))
		b.Push(value.U32(TextureFilterMode_GL_LINEAR))
		b.CallNoPush(funcInfoGlBlitFramebuffer)

		b.Push(value.U32(FramebufferTarget_GL_READ_FRAMEBUFFER))
		b.Load(protocol.TypeUint32, frameBufferID)
		b.CallNoPush(funcInfoGlBindFramebuffer)

		captureImageData(b, int32(c.width), int32(c.height), uint32(TexelFormat_GL_RGBA), uint32(TexelType_GL_UNSIGNED_BYTE), addr)

		b.Push(value.U32(RenderbufferTarget_GL_RENDERBUFFER))
		b.Load(protocol.TypeUint32, origRenderbufferID)
		b.CallNoPush(funcInfoGlBindRenderbuffer)

		b.Push(value.U32(FramebufferTarget_GL_READ_FRAMEBUFFER))
		b.Load(protocol.TypeUint32, origReadFramebufferID)
		b.CallNoPush(funcInfoGlBindFramebuffer)

		b.Push(value.U32(FramebufferTarget_GL_DRAW_FRAMEBUFFER))
		b.Load(protocol.TypeUint32, origDrawFramebufferID)
		b.CallNoPush(funcInfoGlBindFramebuffer)

		b.Push(value.S32(1))
		b.Push(renderBufferID)
		b.CallNoPush(funcInfoGlDeleteRenderbuffers)

		b.Push(value.S32(1))
		b.Push(frameBufferID)
		b.CallNoPush(funcInfoGlDeleteFramebuffers)
	}

	b.Post(addr, imageSize, id,
		func(d *protocol.Decoder) (interface{}, error) {
			buf := make([]byte, imageSize)
			_, err := io.ReadFull(d, buf)
			return buf, err
		},
	)

	b.EndAtom()
}

func captureImageData(b *builder.Builder, width int32, height int32, format uint32, dataType uint32, addr value.Pointer) {
	packAlignment := b.AllocateTemporaryMemory(4)

	b.Push(value.U32(StateVariable_GL_PACK_ALIGNMENT))
	b.Push(packAlignment)
	b.CallNoPush(funcInfoGlGetIntegerv)

	b.Push(value.U32(StateVariable_GL_PACK_ALIGNMENT))
	b.Push(value.S32(1))
	b.CallNoPush(funcInfoGlPixelStorei)

	b.Push(value.S32(0))
	b.Push(value.S32(0))
	b.Push(value.S32(width))
	b.Push(value.S32(height))
	b.Push(value.U32(format))
	b.Push(value.U32(dataType))
	b.Push(addr)
	b.CallNoPush(funcInfoGlReadPixels)

	b.Push(value.U32(StateVariable_GL_PACK_ALIGNMENT))
	b.Load(protocol.TypeInt32, packAlignment)
	b.CallNoPush(funcInfoGlPixelStorei)
}
