////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen -go
////////////////////////////////////////////////////////////////////////////////

package test

import (
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/binary/schema"
	"android.googlesource.com/platform/tools/gpu/memory"
)

func init() {
	registry.Add((*CmdArrayOfFloat)(nil).Class())
	registry.Add((*CmdBool)(nil).Class())
	registry.Add((*CmdF32)(nil).Class())
	registry.Add((*CmdF64)(nil).Class())
	registry.Add((*CmdPointer)(nil).Class())
	registry.Add((*CmdS16)(nil).Class())
	registry.Add((*CmdS32)(nil).Class())
	registry.Add((*CmdS64)(nil).Class())
	registry.Add((*CmdS8)(nil).Class())
	registry.Add((*CmdString)(nil).Class())
	registry.Add((*CmdU16)(nil).Class())
	registry.Add((*CmdU32)(nil).Class())
	registry.Add((*CmdU64)(nil).Class())
	registry.Add((*CmdU8)(nil).Class())
	registry.Add((*CmdVoid)(nil).Class())
	registry.Add((*CmdVoid3Arrays)(nil).Class())
	registry.Add((*CmdVoid3Remapped)(nil).Class())
	registry.Add((*CmdVoid3Strings)(nil).Class())
	registry.Add((*CmdVoidArrayOfStrings)(nil).Class())
	registry.Add((*CmdVoidBool)(nil).Class())
	registry.Add((*CmdVoidF32)(nil).Class())
	registry.Add((*CmdVoidF64)(nil).Class())
	registry.Add((*CmdVoidOut3Remapped)(nil).Class())
	registry.Add((*CmdVoidOut3Strings)(nil).Class())
	registry.Add((*CmdVoidOutArrayOfRemapped)(nil).Class())
	registry.Add((*CmdVoidOutBool)(nil).Class())
	registry.Add((*CmdVoidOutF32)(nil).Class())
	registry.Add((*CmdVoidOutF64)(nil).Class())
	registry.Add((*CmdVoidOutFixedSizeBuffer)(nil).Class())
	registry.Add((*CmdVoidOutS16)(nil).Class())
	registry.Add((*CmdVoidOutS32)(nil).Class())
	registry.Add((*CmdVoidOutS64)(nil).Class())
	registry.Add((*CmdVoidOutS8)(nil).Class())
	registry.Add((*CmdVoidOutString)(nil).Class())
	registry.Add((*CmdVoidOutU16)(nil).Class())
	registry.Add((*CmdVoidOutU32)(nil).Class())
	registry.Add((*CmdVoidOutU64)(nil).Class())
	registry.Add((*CmdVoidOutU8)(nil).Class())
	registry.Add((*CmdVoidS16)(nil).Class())
	registry.Add((*CmdVoidS32)(nil).Class())
	registry.Add((*CmdVoidS64)(nil).Class())
	registry.Add((*CmdVoidS8)(nil).Class())
	registry.Add((*CmdVoidString)(nil).Class())
	registry.Add((*CmdVoidU16)(nil).Class())
	registry.Add((*CmdVoidU32)(nil).Class())
	registry.Add((*CmdVoidU64)(nil).Class())
	registry.Add((*CmdVoidU8)(nil).Class())
	registry.Add((*Globals)(nil).Class())
}

var (
	binaryIDCmdArrayOfFloat           = binary.ID{0x35, 0x9b, 0x5e, 0xce, 0x2f, 0x44, 0x83, 0x70, 0x25, 0x96, 0x74, 0x46, 0x35, 0x94, 0x9b, 0x00, 0xa0, 0xfb, 0xed, 0x40}
	binaryIDCmdBool                   = binary.ID{0x47, 0x05, 0x7d, 0xd3, 0xe2, 0x8a, 0x35, 0xcd, 0x7e, 0x6c, 0xe1, 0x5a, 0x41, 0xea, 0xa1, 0xb4, 0x9a, 0x9a, 0xe1, 0x04}
	binaryIDCmdF32                    = binary.ID{0xac, 0xeb, 0x50, 0x8b, 0x44, 0x00, 0xd5, 0x16, 0xf3, 0x81, 0xcf, 0xce, 0x60, 0x31, 0x86, 0x93, 0x31, 0x23, 0x08, 0xe2}
	binaryIDCmdF64                    = binary.ID{0xba, 0xdf, 0x95, 0xa4, 0xbb, 0xa6, 0xbc, 0xfb, 0x3c, 0x77, 0x73, 0x5d, 0x02, 0x75, 0xb4, 0xf4, 0x4d, 0x3d, 0xd0, 0xd7}
	binaryIDCmdPointer                = binary.ID{0x0a, 0xb5, 0xb1, 0x9b, 0xfa, 0x4d, 0xe7, 0x93, 0xba, 0xea, 0x72, 0x22, 0x89, 0x9d, 0x82, 0x82, 0xe8, 0x7f, 0xc2, 0x17}
	binaryIDCmdS16                    = binary.ID{0x6d, 0xcf, 0x21, 0x7c, 0xaf, 0xea, 0xb4, 0x80, 0xc9, 0xb4, 0xbd, 0x61, 0x43, 0xcf, 0x6c, 0x56, 0x96, 0xd7, 0x55, 0x37}
	binaryIDCmdS32                    = binary.ID{0xee, 0x00, 0xfd, 0x9c, 0xec, 0x69, 0x81, 0xd9, 0x3f, 0xb8, 0xb5, 0x7d, 0xfb, 0x99, 0xcb, 0xf6, 0x1c, 0x28, 0x4c, 0xea}
	binaryIDCmdS64                    = binary.ID{0x25, 0x35, 0xa6, 0x38, 0x97, 0xde, 0x2c, 0xb2, 0x75, 0xaa, 0xe7, 0x89, 0x68, 0x6e, 0x20, 0xed, 0x23, 0x77, 0xbd, 0x23}
	binaryIDCmdS8                     = binary.ID{0x12, 0x6b, 0x91, 0x16, 0x39, 0x64, 0xbc, 0x87, 0xc6, 0x72, 0xf1, 0x3e, 0xdb, 0xa6, 0x4b, 0x16, 0xde, 0xc9, 0x64, 0x45}
	binaryIDCmdString                 = binary.ID{0x6c, 0x20, 0xe9, 0x15, 0x63, 0x82, 0x4a, 0xb2, 0xf6, 0x34, 0xc0, 0x83, 0x90, 0x2d, 0xa8, 0xc9, 0xcb, 0xde, 0xb6, 0x46}
	binaryIDCmdU16                    = binary.ID{0x85, 0xce, 0xbe, 0x9c, 0xdc, 0xc5, 0xfa, 0x06, 0x16, 0xaf, 0xe7, 0x43, 0xc8, 0x25, 0x99, 0x30, 0xb9, 0x14, 0x35, 0x32}
	binaryIDCmdU32                    = binary.ID{0x78, 0xa4, 0x3d, 0x15, 0x0a, 0x41, 0x0c, 0x46, 0x5e, 0x08, 0x4a, 0x9a, 0xab, 0xdc, 0xe5, 0xe0, 0x30, 0x23, 0xef, 0x57}
	binaryIDCmdU64                    = binary.ID{0x96, 0x70, 0xfa, 0x99, 0x32, 0x0a, 0x92, 0x14, 0xfa, 0xc5, 0x08, 0xc3, 0x98, 0xff, 0x94, 0x31, 0xea, 0x8c, 0x38, 0xf4}
	binaryIDCmdU8                     = binary.ID{0x25, 0x6f, 0x35, 0x1c, 0x91, 0xd6, 0xf3, 0xa6, 0x70, 0x81, 0xb2, 0xe0, 0xfa, 0x44, 0x2c, 0x17, 0xf2, 0x17, 0xac, 0x54}
	binaryIDCmdVoid                   = binary.ID{0x05, 0xb2, 0x9c, 0xcc, 0x68, 0x65, 0x50, 0x68, 0xf3, 0x67, 0x28, 0xe9, 0xff, 0x48, 0x87, 0x75, 0x32, 0x24, 0x1e, 0xaf}
	binaryIDCmdVoid3Arrays            = binary.ID{0x9a, 0xc2, 0xfd, 0xc3, 0x44, 0x20, 0x45, 0x50, 0xe5, 0x0f, 0x65, 0x18, 0x9f, 0x33, 0x43, 0xc0, 0xb1, 0x2c, 0x13, 0x5d}
	binaryIDCmdVoid3Remapped          = binary.ID{0x58, 0xcd, 0x42, 0x62, 0x94, 0xae, 0xd5, 0x21, 0x91, 0x3b, 0xe3, 0x77, 0x7e, 0x68, 0x7f, 0x66, 0x3a, 0x43, 0x8b, 0xc9}
	binaryIDCmdVoid3Strings           = binary.ID{0x76, 0xa6, 0x85, 0x68, 0x72, 0x46, 0x75, 0x5c, 0x4b, 0x1d, 0x15, 0x95, 0xbb, 0xdc, 0xbe, 0x23, 0xe0, 0xad, 0xdd, 0xfd}
	binaryIDCmdVoidArrayOfStrings     = binary.ID{0x6e, 0x9e, 0x71, 0x70, 0x9b, 0xb7, 0x1d, 0xf5, 0xcd, 0xeb, 0xd8, 0xd2, 0xbc, 0x00, 0x16, 0x1c, 0x92, 0xb5, 0x9e, 0x26}
	binaryIDCmdVoidBool               = binary.ID{0x00, 0xde, 0x06, 0xc9, 0x63, 0x41, 0x3a, 0x6b, 0x94, 0x85, 0x59, 0x7a, 0x3b, 0xf6, 0x93, 0xf7, 0x3b, 0x2c, 0xf9, 0x8c}
	binaryIDCmdVoidF32                = binary.ID{0x2e, 0x14, 0x6d, 0x75, 0x60, 0xc4, 0xa0, 0x75, 0x83, 0x78, 0x35, 0xbc, 0x0d, 0x2d, 0xf7, 0xd3, 0xdb, 0x7d, 0xe8, 0xb1}
	binaryIDCmdVoidF64                = binary.ID{0x59, 0xcb, 0x74, 0xb0, 0xd2, 0x3e, 0x74, 0xd1, 0xce, 0x39, 0x6e, 0xa9, 0x5e, 0xf5, 0x75, 0x02, 0x24, 0x23, 0x36, 0xb7}
	binaryIDCmdVoidOut3Remapped       = binary.ID{0x4c, 0x62, 0xae, 0x94, 0x53, 0xd5, 0x34, 0xe7, 0x5a, 0xdb, 0x9f, 0xc3, 0x73, 0x93, 0xb2, 0xa9, 0xbc, 0x61, 0xf9, 0x0c}
	binaryIDCmdVoidOut3Strings        = binary.ID{0x74, 0xba, 0x1c, 0xe6, 0x06, 0x73, 0x4c, 0x13, 0x4b, 0x54, 0x23, 0x3a, 0xee, 0x83, 0x32, 0xdf, 0x74, 0x19, 0x6e, 0xf5}
	binaryIDCmdVoidOutArrayOfRemapped = binary.ID{0xf8, 0xa4, 0xee, 0xb5, 0x0e, 0x94, 0x45, 0x1a, 0xaf, 0xf7, 0x26, 0x26, 0x79, 0x32, 0x24, 0x2c, 0x37, 0xb9, 0x68, 0x6f}
	binaryIDCmdVoidOutBool            = binary.ID{0x66, 0x14, 0x6f, 0xc3, 0x83, 0xfa, 0x7e, 0x34, 0xfd, 0xb0, 0x77, 0xf6, 0x96, 0xbe, 0xf1, 0x5b, 0x98, 0x77, 0xe1, 0xa7}
	binaryIDCmdVoidOutF32             = binary.ID{0xb0, 0xe2, 0x3b, 0xc0, 0x28, 0x93, 0x76, 0x84, 0x7f, 0xf7, 0x96, 0xbe, 0xe4, 0xcb, 0xec, 0xeb, 0xfb, 0x35, 0x3e, 0x02}
	binaryIDCmdVoidOutF64             = binary.ID{0x58, 0x7d, 0xf5, 0x3a, 0xa1, 0x4e, 0xf4, 0xb5, 0xa7, 0x30, 0x11, 0xeb, 0x5a, 0x68, 0xb2, 0xc6, 0xdd, 0xa2, 0x5d, 0xb9}
	binaryIDCmdVoidOutFixedSizeBuffer = binary.ID{0xd2, 0x2a, 0x9e, 0x9b, 0x08, 0xa6, 0x0b, 0x11, 0x19, 0x87, 0x36, 0x17, 0xea, 0xdc, 0x49, 0x8a, 0x01, 0x88, 0x5c, 0x8f}
	binaryIDCmdVoidOutS16             = binary.ID{0x38, 0xf0, 0x6e, 0xcf, 0x5b, 0x9b, 0xe3, 0xb7, 0x6d, 0x9b, 0x7b, 0x51, 0xbc, 0x94, 0x3d, 0xba, 0xfe, 0x6c, 0x8a, 0xbf}
	binaryIDCmdVoidOutS32             = binary.ID{0x4b, 0xb3, 0x5a, 0x13, 0xc1, 0x6b, 0xcd, 0x01, 0xcd, 0xd0, 0x88, 0x89, 0xc8, 0x5e, 0x5e, 0x70, 0x44, 0xc4, 0x9a, 0x23}
	binaryIDCmdVoidOutS64             = binary.ID{0x2f, 0xf0, 0x6c, 0x4c, 0xa3, 0x73, 0xa0, 0x26, 0x3c, 0x17, 0xf9, 0x17, 0xa6, 0x89, 0x23, 0xce, 0xc9, 0x7b, 0x37, 0xa4}
	binaryIDCmdVoidOutS8              = binary.ID{0xc9, 0x3a, 0x05, 0x36, 0x35, 0x2d, 0x93, 0x76, 0xf4, 0x06, 0xa7, 0x28, 0xe9, 0xe5, 0xed, 0x4f, 0xdb, 0x45, 0xe8, 0x2b}
	binaryIDCmdVoidOutString          = binary.ID{0xef, 0xa9, 0xd0, 0x00, 0x2e, 0x7d, 0xd2, 0xdf, 0xb0, 0x5b, 0x35, 0x51, 0xa7, 0x9f, 0x49, 0x3a, 0xbf, 0xa0, 0x3f, 0x00}
	binaryIDCmdVoidOutU16             = binary.ID{0x4d, 0x5a, 0xb8, 0x48, 0x9e, 0x43, 0x34, 0x4a, 0x79, 0x5e, 0x86, 0xf2, 0xac, 0x38, 0x87, 0x13, 0xd5, 0xba, 0xbf, 0xc7}
	binaryIDCmdVoidOutU32             = binary.ID{0x03, 0x91, 0xd1, 0x3f, 0x3f, 0x9e, 0xea, 0x33, 0x71, 0xff, 0x02, 0x0c, 0x70, 0x6a, 0x07, 0xbb, 0x2f, 0x32, 0xeb, 0x0b}
	binaryIDCmdVoidOutU64             = binary.ID{0x81, 0x40, 0x56, 0x73, 0x6c, 0x01, 0x6c, 0x62, 0x23, 0x19, 0xc3, 0x24, 0xc7, 0xe0, 0xcd, 0x3b, 0xa4, 0x04, 0xb9, 0x3e}
	binaryIDCmdVoidOutU8              = binary.ID{0x91, 0xe3, 0xf7, 0x1e, 0x4d, 0xa7, 0x2e, 0xce, 0x6d, 0x2e, 0x5b, 0xca, 0xd6, 0x16, 0xc6, 0xf3, 0xf4, 0x5a, 0x91, 0x27}
	binaryIDCmdVoidS16                = binary.ID{0xf3, 0x1f, 0x79, 0x1e, 0xbd, 0xc5, 0xda, 0x5a, 0xb3, 0x62, 0x45, 0x34, 0x2b, 0x5b, 0xdd, 0xea, 0x68, 0x3f, 0x58, 0x57}
	binaryIDCmdVoidS32                = binary.ID{0x45, 0xc2, 0x1f, 0x19, 0x69, 0xb2, 0x83, 0x0e, 0x67, 0x51, 0x74, 0x10, 0x09, 0xfd, 0xeb, 0x31, 0xcc, 0xf1, 0x52, 0x66}
	binaryIDCmdVoidS64                = binary.ID{0x78, 0x68, 0x18, 0x4b, 0xbf, 0x77, 0xd8, 0x45, 0x30, 0x06, 0xc5, 0x44, 0xca, 0x8c, 0x1e, 0xf8, 0xee, 0x82, 0x85, 0x31}
	binaryIDCmdVoidS8                 = binary.ID{0xfc, 0x01, 0x6b, 0x1c, 0x5f, 0x06, 0xe1, 0x1d, 0xf8, 0x15, 0x8d, 0x51, 0xa4, 0xcb, 0x44, 0x3d, 0xb1, 0xd1, 0x59, 0x61}
	binaryIDCmdVoidString             = binary.ID{0xdb, 0x9c, 0xa9, 0x10, 0x3a, 0x69, 0x32, 0xac, 0xa3, 0x56, 0xbc, 0x07, 0x34, 0x29, 0xe4, 0x48, 0x42, 0xbe, 0xc3, 0x98}
	binaryIDCmdVoidU16                = binary.ID{0x8b, 0x3f, 0xb3, 0x3b, 0xd4, 0xdf, 0xed, 0xf5, 0x51, 0xaa, 0x5a, 0x4c, 0x4d, 0x37, 0x12, 0xd7, 0xab, 0x01, 0x18, 0xd4}
	binaryIDCmdVoidU32                = binary.ID{0xa9, 0xce, 0x14, 0x64, 0x4e, 0x49, 0xe5, 0x68, 0xc7, 0xfe, 0xb1, 0x8f, 0xbf, 0x8b, 0x51, 0x5e, 0xb7, 0x6c, 0x92, 0x26}
	binaryIDCmdVoidU64                = binary.ID{0xf0, 0x94, 0xd4, 0x52, 0x67, 0x8b, 0x0b, 0xb6, 0xc9, 0x2c, 0x5a, 0xeb, 0xad, 0x86, 0x6e, 0x16, 0x39, 0x05, 0x36, 0x12}
	binaryIDCmdVoidU8                 = binary.ID{0x37, 0x14, 0xbd, 0x49, 0x55, 0x6f, 0xbf, 0x7b, 0x5b, 0xa2, 0x72, 0x0a, 0xb8, 0x94, 0x3a, 0x21, 0x4c, 0xdb, 0xe3, 0x32}
	binaryIDGlobals                   = binary.ID{0xc0, 0x56, 0xa7, 0xd5, 0x53, 0x88, 0xac, 0xaa, 0x75, 0x81, 0x46, 0x04, 0x13, 0xd4, 0xd3, 0x88, 0x43, 0x9c, 0xef, 0x61}
)

type binaryClassCmdArrayOfFloat struct{}

func (*CmdArrayOfFloat) Class() binary.Class {
	return (*binaryClassCmdArrayOfFloat)(nil)
}
func doEncodeCmdArrayOfFloat(e binary.Encoder, o *CmdArrayOfFloat) error {
	if err := e.Uint32(uint32(len(o.Result))); err != nil {
		return err
	}
	for i := range o.Result {
		if err := e.Float32(o.Result[i]); err != nil {
			return err
		}
	}
	return nil
}
func doDecodeCmdArrayOfFloat(d binary.Decoder, o *CmdArrayOfFloat) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.Result = make(F32Array, count)
		for i := range o.Result {
			if obj, err := d.Float32(); err != nil {
				return err
			} else {
				o.Result[i] = float32(obj)
			}
		}
	}
	return nil
}
func doSkipCmdArrayOfFloat(d binary.Decoder) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if _, err := d.Float32(); err != nil {
				return err
			}
		}
	}
	return nil
}
func (*binaryClassCmdArrayOfFloat) ID() binary.ID      { return binaryIDCmdArrayOfFloat }
func (*binaryClassCmdArrayOfFloat) New() binary.Object { return &CmdArrayOfFloat{} }
func (*binaryClassCmdArrayOfFloat) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdArrayOfFloat(e, obj.(*CmdArrayOfFloat))
}
func (*binaryClassCmdArrayOfFloat) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdArrayOfFloat{}
	return obj, doDecodeCmdArrayOfFloat(d, obj)
}
func (*binaryClassCmdArrayOfFloat) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdArrayOfFloat(d, obj.(*CmdArrayOfFloat))
}
func (*binaryClassCmdArrayOfFloat) Skip(d binary.Decoder) error { return doSkipCmdArrayOfFloat(d) }
func (*binaryClassCmdArrayOfFloat) Schema() *schema.Class       { return schemaCmdArrayOfFloat }

var schemaCmdArrayOfFloat = &schema.Class{
	TypeID: binaryIDCmdArrayOfFloat,
	Name:   "CmdArrayOfFloat",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Slice{Alias: "F32Array", ValueType: &schema.Primitive{Name: "float32", Method: schema.Float32}}},
	},
}

type binaryClassCmdBool struct{}

func (*CmdBool) Class() binary.Class {
	return (*binaryClassCmdBool)(nil)
}
func doEncodeCmdBool(e binary.Encoder, o *CmdBool) error {
	if err := e.Bool(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdBool(d binary.Decoder, o *CmdBool) error {
	if obj, err := d.Bool(); err != nil {
		return err
	} else {
		o.Result = bool(obj)
	}
	return nil
}
func doSkipCmdBool(d binary.Decoder) error {
	if _, err := d.Bool(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdBool) ID() binary.ID      { return binaryIDCmdBool }
func (*binaryClassCmdBool) New() binary.Object { return &CmdBool{} }
func (*binaryClassCmdBool) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdBool(e, obj.(*CmdBool))
}
func (*binaryClassCmdBool) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdBool{}
	return obj, doDecodeCmdBool(d, obj)
}
func (*binaryClassCmdBool) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdBool(d, obj.(*CmdBool))
}
func (*binaryClassCmdBool) Skip(d binary.Decoder) error { return doSkipCmdBool(d) }
func (*binaryClassCmdBool) Schema() *schema.Class       { return schemaCmdBool }

var schemaCmdBool = &schema.Class{
	TypeID: binaryIDCmdBool,
	Name:   "CmdBool",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "bool", Method: schema.Bool}},
	},
}

type binaryClassCmdF32 struct{}

func (*CmdF32) Class() binary.Class {
	return (*binaryClassCmdF32)(nil)
}
func doEncodeCmdF32(e binary.Encoder, o *CmdF32) error {
	if err := e.Float32(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdF32(d binary.Decoder, o *CmdF32) error {
	if obj, err := d.Float32(); err != nil {
		return err
	} else {
		o.Result = float32(obj)
	}
	return nil
}
func doSkipCmdF32(d binary.Decoder) error {
	if _, err := d.Float32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdF32) ID() binary.ID      { return binaryIDCmdF32 }
func (*binaryClassCmdF32) New() binary.Object { return &CmdF32{} }
func (*binaryClassCmdF32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdF32(e, obj.(*CmdF32))
}
func (*binaryClassCmdF32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdF32{}
	return obj, doDecodeCmdF32(d, obj)
}
func (*binaryClassCmdF32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdF32(d, obj.(*CmdF32))
}
func (*binaryClassCmdF32) Skip(d binary.Decoder) error { return doSkipCmdF32(d) }
func (*binaryClassCmdF32) Schema() *schema.Class       { return schemaCmdF32 }

var schemaCmdF32 = &schema.Class{
	TypeID: binaryIDCmdF32,
	Name:   "CmdF32",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "float32", Method: schema.Float32}},
	},
}

type binaryClassCmdF64 struct{}

func (*CmdF64) Class() binary.Class {
	return (*binaryClassCmdF64)(nil)
}
func doEncodeCmdF64(e binary.Encoder, o *CmdF64) error {
	if err := e.Float64(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdF64(d binary.Decoder, o *CmdF64) error {
	if obj, err := d.Float64(); err != nil {
		return err
	} else {
		o.Result = float64(obj)
	}
	return nil
}
func doSkipCmdF64(d binary.Decoder) error {
	if _, err := d.Float64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdF64) ID() binary.ID      { return binaryIDCmdF64 }
func (*binaryClassCmdF64) New() binary.Object { return &CmdF64{} }
func (*binaryClassCmdF64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdF64(e, obj.(*CmdF64))
}
func (*binaryClassCmdF64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdF64{}
	return obj, doDecodeCmdF64(d, obj)
}
func (*binaryClassCmdF64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdF64(d, obj.(*CmdF64))
}
func (*binaryClassCmdF64) Skip(d binary.Decoder) error { return doSkipCmdF64(d) }
func (*binaryClassCmdF64) Schema() *schema.Class       { return schemaCmdF64 }

var schemaCmdF64 = &schema.Class{
	TypeID: binaryIDCmdF64,
	Name:   "CmdF64",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "float64", Method: schema.Float64}},
	},
}

type binaryClassCmdPointer struct{}

func (*CmdPointer) Class() binary.Class {
	return (*binaryClassCmdPointer)(nil)
}
func doEncodeCmdPointer(e binary.Encoder, o *CmdPointer) error {
	if err := e.Uint64(uint64(o.Result)); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdPointer(d binary.Decoder, o *CmdPointer) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.Result = memory.Pointer(obj)
	}
	return nil
}
func doSkipCmdPointer(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdPointer) ID() binary.ID      { return binaryIDCmdPointer }
func (*binaryClassCmdPointer) New() binary.Object { return &CmdPointer{} }
func (*binaryClassCmdPointer) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdPointer(e, obj.(*CmdPointer))
}
func (*binaryClassCmdPointer) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdPointer{}
	return obj, doDecodeCmdPointer(d, obj)
}
func (*binaryClassCmdPointer) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdPointer(d, obj.(*CmdPointer))
}
func (*binaryClassCmdPointer) Skip(d binary.Decoder) error { return doSkipCmdPointer(d) }
func (*binaryClassCmdPointer) Schema() *schema.Class       { return schemaCmdPointer }

var schemaCmdPointer = &schema.Class{
	TypeID: binaryIDCmdPointer,
	Name:   "CmdPointer",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "memory.Pointer", Method: schema.Uint64}},
	},
}

type binaryClassCmdS16 struct{}

func (*CmdS16) Class() binary.Class {
	return (*binaryClassCmdS16)(nil)
}
func doEncodeCmdS16(e binary.Encoder, o *CmdS16) error {
	if err := e.Int16(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdS16(d binary.Decoder, o *CmdS16) error {
	if obj, err := d.Int16(); err != nil {
		return err
	} else {
		o.Result = int16(obj)
	}
	return nil
}
func doSkipCmdS16(d binary.Decoder) error {
	if _, err := d.Int16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdS16) ID() binary.ID      { return binaryIDCmdS16 }
func (*binaryClassCmdS16) New() binary.Object { return &CmdS16{} }
func (*binaryClassCmdS16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdS16(e, obj.(*CmdS16))
}
func (*binaryClassCmdS16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdS16{}
	return obj, doDecodeCmdS16(d, obj)
}
func (*binaryClassCmdS16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdS16(d, obj.(*CmdS16))
}
func (*binaryClassCmdS16) Skip(d binary.Decoder) error { return doSkipCmdS16(d) }
func (*binaryClassCmdS16) Schema() *schema.Class       { return schemaCmdS16 }

var schemaCmdS16 = &schema.Class{
	TypeID: binaryIDCmdS16,
	Name:   "CmdS16",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "int16", Method: schema.Int16}},
	},
}

type binaryClassCmdS32 struct{}

func (*CmdS32) Class() binary.Class {
	return (*binaryClassCmdS32)(nil)
}
func doEncodeCmdS32(e binary.Encoder, o *CmdS32) error {
	if err := e.Int32(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdS32(d binary.Decoder, o *CmdS32) error {
	if obj, err := d.Int32(); err != nil {
		return err
	} else {
		o.Result = int32(obj)
	}
	return nil
}
func doSkipCmdS32(d binary.Decoder) error {
	if _, err := d.Int32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdS32) ID() binary.ID      { return binaryIDCmdS32 }
func (*binaryClassCmdS32) New() binary.Object { return &CmdS32{} }
func (*binaryClassCmdS32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdS32(e, obj.(*CmdS32))
}
func (*binaryClassCmdS32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdS32{}
	return obj, doDecodeCmdS32(d, obj)
}
func (*binaryClassCmdS32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdS32(d, obj.(*CmdS32))
}
func (*binaryClassCmdS32) Skip(d binary.Decoder) error { return doSkipCmdS32(d) }
func (*binaryClassCmdS32) Schema() *schema.Class       { return schemaCmdS32 }

var schemaCmdS32 = &schema.Class{
	TypeID: binaryIDCmdS32,
	Name:   "CmdS32",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "int32", Method: schema.Int32}},
	},
}

type binaryClassCmdS64 struct{}

func (*CmdS64) Class() binary.Class {
	return (*binaryClassCmdS64)(nil)
}
func doEncodeCmdS64(e binary.Encoder, o *CmdS64) error {
	if err := e.Int64(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdS64(d binary.Decoder, o *CmdS64) error {
	if obj, err := d.Int64(); err != nil {
		return err
	} else {
		o.Result = int64(obj)
	}
	return nil
}
func doSkipCmdS64(d binary.Decoder) error {
	if _, err := d.Int64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdS64) ID() binary.ID      { return binaryIDCmdS64 }
func (*binaryClassCmdS64) New() binary.Object { return &CmdS64{} }
func (*binaryClassCmdS64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdS64(e, obj.(*CmdS64))
}
func (*binaryClassCmdS64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdS64{}
	return obj, doDecodeCmdS64(d, obj)
}
func (*binaryClassCmdS64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdS64(d, obj.(*CmdS64))
}
func (*binaryClassCmdS64) Skip(d binary.Decoder) error { return doSkipCmdS64(d) }
func (*binaryClassCmdS64) Schema() *schema.Class       { return schemaCmdS64 }

var schemaCmdS64 = &schema.Class{
	TypeID: binaryIDCmdS64,
	Name:   "CmdS64",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "int64", Method: schema.Int64}},
	},
}

type binaryClassCmdS8 struct{}

func (*CmdS8) Class() binary.Class {
	return (*binaryClassCmdS8)(nil)
}
func doEncodeCmdS8(e binary.Encoder, o *CmdS8) error {
	if err := e.Int8(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdS8(d binary.Decoder, o *CmdS8) error {
	if obj, err := d.Int8(); err != nil {
		return err
	} else {
		o.Result = int8(obj)
	}
	return nil
}
func doSkipCmdS8(d binary.Decoder) error {
	if _, err := d.Int8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdS8) ID() binary.ID      { return binaryIDCmdS8 }
func (*binaryClassCmdS8) New() binary.Object { return &CmdS8{} }
func (*binaryClassCmdS8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdS8(e, obj.(*CmdS8))
}
func (*binaryClassCmdS8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdS8{}
	return obj, doDecodeCmdS8(d, obj)
}
func (*binaryClassCmdS8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdS8(d, obj.(*CmdS8))
}
func (*binaryClassCmdS8) Skip(d binary.Decoder) error { return doSkipCmdS8(d) }
func (*binaryClassCmdS8) Schema() *schema.Class       { return schemaCmdS8 }

var schemaCmdS8 = &schema.Class{
	TypeID: binaryIDCmdS8,
	Name:   "CmdS8",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "int8", Method: schema.Int8}},
	},
}

type binaryClassCmdString struct{}

func (*CmdString) Class() binary.Class {
	return (*binaryClassCmdString)(nil)
}
func doEncodeCmdString(e binary.Encoder, o *CmdString) error {
	if err := e.String(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdString(d binary.Decoder, o *CmdString) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.Result = string(obj)
	}
	return nil
}
func doSkipCmdString(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdString) ID() binary.ID      { return binaryIDCmdString }
func (*binaryClassCmdString) New() binary.Object { return &CmdString{} }
func (*binaryClassCmdString) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdString(e, obj.(*CmdString))
}
func (*binaryClassCmdString) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdString{}
	return obj, doDecodeCmdString(d, obj)
}
func (*binaryClassCmdString) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdString(d, obj.(*CmdString))
}
func (*binaryClassCmdString) Skip(d binary.Decoder) error { return doSkipCmdString(d) }
func (*binaryClassCmdString) Schema() *schema.Class       { return schemaCmdString }

var schemaCmdString = &schema.Class{
	TypeID: binaryIDCmdString,
	Name:   "CmdString",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassCmdU16 struct{}

func (*CmdU16) Class() binary.Class {
	return (*binaryClassCmdU16)(nil)
}
func doEncodeCmdU16(e binary.Encoder, o *CmdU16) error {
	if err := e.Uint16(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdU16(d binary.Decoder, o *CmdU16) error {
	if obj, err := d.Uint16(); err != nil {
		return err
	} else {
		o.Result = uint16(obj)
	}
	return nil
}
func doSkipCmdU16(d binary.Decoder) error {
	if _, err := d.Uint16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdU16) ID() binary.ID      { return binaryIDCmdU16 }
func (*binaryClassCmdU16) New() binary.Object { return &CmdU16{} }
func (*binaryClassCmdU16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdU16(e, obj.(*CmdU16))
}
func (*binaryClassCmdU16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdU16{}
	return obj, doDecodeCmdU16(d, obj)
}
func (*binaryClassCmdU16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdU16(d, obj.(*CmdU16))
}
func (*binaryClassCmdU16) Skip(d binary.Decoder) error { return doSkipCmdU16(d) }
func (*binaryClassCmdU16) Schema() *schema.Class       { return schemaCmdU16 }

var schemaCmdU16 = &schema.Class{
	TypeID: binaryIDCmdU16,
	Name:   "CmdU16",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "uint16", Method: schema.Uint16}},
	},
}

type binaryClassCmdU32 struct{}

func (*CmdU32) Class() binary.Class {
	return (*binaryClassCmdU32)(nil)
}
func doEncodeCmdU32(e binary.Encoder, o *CmdU32) error {
	if err := e.Uint32(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdU32(d binary.Decoder, o *CmdU32) error {
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.Result = uint32(obj)
	}
	return nil
}
func doSkipCmdU32(d binary.Decoder) error {
	if _, err := d.Uint32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdU32) ID() binary.ID      { return binaryIDCmdU32 }
func (*binaryClassCmdU32) New() binary.Object { return &CmdU32{} }
func (*binaryClassCmdU32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdU32(e, obj.(*CmdU32))
}
func (*binaryClassCmdU32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdU32{}
	return obj, doDecodeCmdU32(d, obj)
}
func (*binaryClassCmdU32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdU32(d, obj.(*CmdU32))
}
func (*binaryClassCmdU32) Skip(d binary.Decoder) error { return doSkipCmdU32(d) }
func (*binaryClassCmdU32) Schema() *schema.Class       { return schemaCmdU32 }

var schemaCmdU32 = &schema.Class{
	TypeID: binaryIDCmdU32,
	Name:   "CmdU32",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
	},
}

type binaryClassCmdU64 struct{}

func (*CmdU64) Class() binary.Class {
	return (*binaryClassCmdU64)(nil)
}
func doEncodeCmdU64(e binary.Encoder, o *CmdU64) error {
	if err := e.Uint64(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdU64(d binary.Decoder, o *CmdU64) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.Result = uint64(obj)
	}
	return nil
}
func doSkipCmdU64(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdU64) ID() binary.ID      { return binaryIDCmdU64 }
func (*binaryClassCmdU64) New() binary.Object { return &CmdU64{} }
func (*binaryClassCmdU64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdU64(e, obj.(*CmdU64))
}
func (*binaryClassCmdU64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdU64{}
	return obj, doDecodeCmdU64(d, obj)
}
func (*binaryClassCmdU64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdU64(d, obj.(*CmdU64))
}
func (*binaryClassCmdU64) Skip(d binary.Decoder) error { return doSkipCmdU64(d) }
func (*binaryClassCmdU64) Schema() *schema.Class       { return schemaCmdU64 }

var schemaCmdU64 = &schema.Class{
	TypeID: binaryIDCmdU64,
	Name:   "CmdU64",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
	},
}

type binaryClassCmdU8 struct{}

func (*CmdU8) Class() binary.Class {
	return (*binaryClassCmdU8)(nil)
}
func doEncodeCmdU8(e binary.Encoder, o *CmdU8) error {
	if err := e.Uint8(o.Result); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdU8(d binary.Decoder, o *CmdU8) error {
	if obj, err := d.Uint8(); err != nil {
		return err
	} else {
		o.Result = uint8(obj)
	}
	return nil
}
func doSkipCmdU8(d binary.Decoder) error {
	if _, err := d.Uint8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdU8) ID() binary.ID      { return binaryIDCmdU8 }
func (*binaryClassCmdU8) New() binary.Object { return &CmdU8{} }
func (*binaryClassCmdU8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdU8(e, obj.(*CmdU8))
}
func (*binaryClassCmdU8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdU8{}
	return obj, doDecodeCmdU8(d, obj)
}
func (*binaryClassCmdU8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdU8(d, obj.(*CmdU8))
}
func (*binaryClassCmdU8) Skip(d binary.Decoder) error { return doSkipCmdU8(d) }
func (*binaryClassCmdU8) Schema() *schema.Class       { return schemaCmdU8 }

var schemaCmdU8 = &schema.Class{
	TypeID: binaryIDCmdU8,
	Name:   "CmdU8",
	Fields: []schema.Field{
		schema.Field{Declared: "Result", Type: &schema.Primitive{Name: "uint8", Method: schema.Uint8}},
	},
}

type binaryClassCmdVoid struct{}

func (*CmdVoid) Class() binary.Class {
	return (*binaryClassCmdVoid)(nil)
}
func doEncodeCmdVoid(e binary.Encoder, o *CmdVoid) error {
	return nil
}
func doDecodeCmdVoid(d binary.Decoder, o *CmdVoid) error {
	return nil
}
func doSkipCmdVoid(d binary.Decoder) error {
	return nil
}
func (*binaryClassCmdVoid) ID() binary.ID      { return binaryIDCmdVoid }
func (*binaryClassCmdVoid) New() binary.Object { return &CmdVoid{} }
func (*binaryClassCmdVoid) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoid(e, obj.(*CmdVoid))
}
func (*binaryClassCmdVoid) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoid{}
	return obj, doDecodeCmdVoid(d, obj)
}
func (*binaryClassCmdVoid) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoid(d, obj.(*CmdVoid))
}
func (*binaryClassCmdVoid) Skip(d binary.Decoder) error { return doSkipCmdVoid(d) }
func (*binaryClassCmdVoid) Schema() *schema.Class       { return schemaCmdVoid }

var schemaCmdVoid = &schema.Class{
	TypeID: binaryIDCmdVoid,
	Name:   "CmdVoid",
	Fields: []schema.Field{},
}

type binaryClassCmdVoid3Arrays struct{}

func (*CmdVoid3Arrays) Class() binary.Class {
	return (*binaryClassCmdVoid3Arrays)(nil)
}
func doEncodeCmdVoid3Arrays(e binary.Encoder, o *CmdVoid3Arrays) error {
	if err := e.Uint32(uint32(len(o.A))); err != nil {
		return err
	}
	for i := range o.A {
		if err := e.Int8(o.A[i]); err != nil {
			return err
		}
	}
	if err := e.Uint32(uint32(len(o.B))); err != nil {
		return err
	}
	for i := range o.B {
		if err := e.String(o.B[i]); err != nil {
			return err
		}
	}
	if err := e.Uint32(uint32(len(o.C))); err != nil {
		return err
	}
	for i := range o.C {
		if err := e.Bool(o.C[i]); err != nil {
			return err
		}
	}
	return nil
}
func doDecodeCmdVoid3Arrays(d binary.Decoder, o *CmdVoid3Arrays) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = make(S8Array, count)
		for i := range o.A {
			if obj, err := d.Int8(); err != nil {
				return err
			} else {
				o.A[i] = int8(obj)
			}
		}
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.B = make(StringArray, count)
		for i := range o.B {
			if obj, err := d.String(); err != nil {
				return err
			} else {
				o.B[i] = string(obj)
			}
		}
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.C = make(BoolArray, count)
		for i := range o.C {
			if obj, err := d.Bool(); err != nil {
				return err
			} else {
				o.C[i] = bool(obj)
			}
		}
	}
	return nil
}
func doSkipCmdVoid3Arrays(d binary.Decoder) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if _, err := d.Int8(); err != nil {
				return err
			}
		}
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if err := d.SkipString(); err != nil {
				return err
			}
		}
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if _, err := d.Bool(); err != nil {
				return err
			}
		}
	}
	return nil
}
func (*binaryClassCmdVoid3Arrays) ID() binary.ID      { return binaryIDCmdVoid3Arrays }
func (*binaryClassCmdVoid3Arrays) New() binary.Object { return &CmdVoid3Arrays{} }
func (*binaryClassCmdVoid3Arrays) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoid3Arrays(e, obj.(*CmdVoid3Arrays))
}
func (*binaryClassCmdVoid3Arrays) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoid3Arrays{}
	return obj, doDecodeCmdVoid3Arrays(d, obj)
}
func (*binaryClassCmdVoid3Arrays) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoid3Arrays(d, obj.(*CmdVoid3Arrays))
}
func (*binaryClassCmdVoid3Arrays) Skip(d binary.Decoder) error { return doSkipCmdVoid3Arrays(d) }
func (*binaryClassCmdVoid3Arrays) Schema() *schema.Class       { return schemaCmdVoid3Arrays }

var schemaCmdVoid3Arrays = &schema.Class{
	TypeID: binaryIDCmdVoid3Arrays,
	Name:   "CmdVoid3Arrays",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Slice{Alias: "S8Array", ValueType: &schema.Primitive{Name: "int8", Method: schema.Int8}}},
		schema.Field{Declared: "B", Type: &schema.Slice{Alias: "StringArray", ValueType: &schema.Primitive{Name: "string", Method: schema.String}}},
		schema.Field{Declared: "C", Type: &schema.Slice{Alias: "BoolArray", ValueType: &schema.Primitive{Name: "bool", Method: schema.Bool}}},
	},
}

type binaryClassCmdVoid3Remapped struct{}

func (*CmdVoid3Remapped) Class() binary.Class {
	return (*binaryClassCmdVoid3Remapped)(nil)
}
func doEncodeCmdVoid3Remapped(e binary.Encoder, o *CmdVoid3Remapped) error {
	if err := e.Uint32(uint32(o.A)); err != nil {
		return err
	}
	if err := e.Uint32(uint32(o.B)); err != nil {
		return err
	}
	if err := e.Uint32(uint32(o.C)); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoid3Remapped(d binary.Decoder, o *CmdVoid3Remapped) error {
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = remapped(obj)
	}
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.B = remapped(obj)
	}
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.C = remapped(obj)
	}
	return nil
}
func doSkipCmdVoid3Remapped(d binary.Decoder) error {
	if _, err := d.Uint32(); err != nil {
		return err
	}
	if _, err := d.Uint32(); err != nil {
		return err
	}
	if _, err := d.Uint32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoid3Remapped) ID() binary.ID      { return binaryIDCmdVoid3Remapped }
func (*binaryClassCmdVoid3Remapped) New() binary.Object { return &CmdVoid3Remapped{} }
func (*binaryClassCmdVoid3Remapped) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoid3Remapped(e, obj.(*CmdVoid3Remapped))
}
func (*binaryClassCmdVoid3Remapped) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoid3Remapped{}
	return obj, doDecodeCmdVoid3Remapped(d, obj)
}
func (*binaryClassCmdVoid3Remapped) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoid3Remapped(d, obj.(*CmdVoid3Remapped))
}
func (*binaryClassCmdVoid3Remapped) Skip(d binary.Decoder) error { return doSkipCmdVoid3Remapped(d) }
func (*binaryClassCmdVoid3Remapped) Schema() *schema.Class       { return schemaCmdVoid3Remapped }

var schemaCmdVoid3Remapped = &schema.Class{
	TypeID: binaryIDCmdVoid3Remapped,
	Name:   "CmdVoid3Remapped",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
		schema.Field{Declared: "B", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
		schema.Field{Declared: "C", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
	},
}

type binaryClassCmdVoid3Strings struct{}

func (*CmdVoid3Strings) Class() binary.Class {
	return (*binaryClassCmdVoid3Strings)(nil)
}
func doEncodeCmdVoid3Strings(e binary.Encoder, o *CmdVoid3Strings) error {
	if err := e.String(o.A); err != nil {
		return err
	}
	if err := e.String(o.B); err != nil {
		return err
	}
	if err := e.String(o.C); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoid3Strings(d binary.Decoder, o *CmdVoid3Strings) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.A = string(obj)
	}
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.B = string(obj)
	}
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.C = string(obj)
	}
	return nil
}
func doSkipCmdVoid3Strings(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	if err := d.SkipString(); err != nil {
		return err
	}
	if err := d.SkipString(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoid3Strings) ID() binary.ID      { return binaryIDCmdVoid3Strings }
func (*binaryClassCmdVoid3Strings) New() binary.Object { return &CmdVoid3Strings{} }
func (*binaryClassCmdVoid3Strings) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoid3Strings(e, obj.(*CmdVoid3Strings))
}
func (*binaryClassCmdVoid3Strings) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoid3Strings{}
	return obj, doDecodeCmdVoid3Strings(d, obj)
}
func (*binaryClassCmdVoid3Strings) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoid3Strings(d, obj.(*CmdVoid3Strings))
}
func (*binaryClassCmdVoid3Strings) Skip(d binary.Decoder) error { return doSkipCmdVoid3Strings(d) }
func (*binaryClassCmdVoid3Strings) Schema() *schema.Class       { return schemaCmdVoid3Strings }

var schemaCmdVoid3Strings = &schema.Class{
	TypeID: binaryIDCmdVoid3Strings,
	Name:   "CmdVoid3Strings",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		schema.Field{Declared: "B", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		schema.Field{Declared: "C", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassCmdVoidArrayOfStrings struct{}

func (*CmdVoidArrayOfStrings) Class() binary.Class {
	return (*binaryClassCmdVoidArrayOfStrings)(nil)
}
func doEncodeCmdVoidArrayOfStrings(e binary.Encoder, o *CmdVoidArrayOfStrings) error {
	if err := e.Uint32(uint32(len(o.A))); err != nil {
		return err
	}
	for i := range o.A {
		if err := e.String(o.A[i]); err != nil {
			return err
		}
	}
	return nil
}
func doDecodeCmdVoidArrayOfStrings(d binary.Decoder, o *CmdVoidArrayOfStrings) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = make(StringArray, count)
		for i := range o.A {
			if obj, err := d.String(); err != nil {
				return err
			} else {
				o.A[i] = string(obj)
			}
		}
	}
	return nil
}
func doSkipCmdVoidArrayOfStrings(d binary.Decoder) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if err := d.SkipString(); err != nil {
				return err
			}
		}
	}
	return nil
}
func (*binaryClassCmdVoidArrayOfStrings) ID() binary.ID      { return binaryIDCmdVoidArrayOfStrings }
func (*binaryClassCmdVoidArrayOfStrings) New() binary.Object { return &CmdVoidArrayOfStrings{} }
func (*binaryClassCmdVoidArrayOfStrings) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidArrayOfStrings(e, obj.(*CmdVoidArrayOfStrings))
}
func (*binaryClassCmdVoidArrayOfStrings) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidArrayOfStrings{}
	return obj, doDecodeCmdVoidArrayOfStrings(d, obj)
}
func (*binaryClassCmdVoidArrayOfStrings) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidArrayOfStrings(d, obj.(*CmdVoidArrayOfStrings))
}
func (*binaryClassCmdVoidArrayOfStrings) Skip(d binary.Decoder) error {
	return doSkipCmdVoidArrayOfStrings(d)
}
func (*binaryClassCmdVoidArrayOfStrings) Schema() *schema.Class { return schemaCmdVoidArrayOfStrings }

var schemaCmdVoidArrayOfStrings = &schema.Class{
	TypeID: binaryIDCmdVoidArrayOfStrings,
	Name:   "CmdVoidArrayOfStrings",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Slice{Alias: "StringArray", ValueType: &schema.Primitive{Name: "string", Method: schema.String}}},
	},
}

type binaryClassCmdVoidBool struct{}

func (*CmdVoidBool) Class() binary.Class {
	return (*binaryClassCmdVoidBool)(nil)
}
func doEncodeCmdVoidBool(e binary.Encoder, o *CmdVoidBool) error {
	if err := e.Bool(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidBool(d binary.Decoder, o *CmdVoidBool) error {
	if obj, err := d.Bool(); err != nil {
		return err
	} else {
		o.A = bool(obj)
	}
	return nil
}
func doSkipCmdVoidBool(d binary.Decoder) error {
	if _, err := d.Bool(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidBool) ID() binary.ID      { return binaryIDCmdVoidBool }
func (*binaryClassCmdVoidBool) New() binary.Object { return &CmdVoidBool{} }
func (*binaryClassCmdVoidBool) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidBool(e, obj.(*CmdVoidBool))
}
func (*binaryClassCmdVoidBool) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidBool{}
	return obj, doDecodeCmdVoidBool(d, obj)
}
func (*binaryClassCmdVoidBool) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidBool(d, obj.(*CmdVoidBool))
}
func (*binaryClassCmdVoidBool) Skip(d binary.Decoder) error { return doSkipCmdVoidBool(d) }
func (*binaryClassCmdVoidBool) Schema() *schema.Class       { return schemaCmdVoidBool }

var schemaCmdVoidBool = &schema.Class{
	TypeID: binaryIDCmdVoidBool,
	Name:   "CmdVoidBool",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "bool", Method: schema.Bool}},
	},
}

type binaryClassCmdVoidF32 struct{}

func (*CmdVoidF32) Class() binary.Class {
	return (*binaryClassCmdVoidF32)(nil)
}
func doEncodeCmdVoidF32(e binary.Encoder, o *CmdVoidF32) error {
	if err := e.Float32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidF32(d binary.Decoder, o *CmdVoidF32) error {
	if obj, err := d.Float32(); err != nil {
		return err
	} else {
		o.A = float32(obj)
	}
	return nil
}
func doSkipCmdVoidF32(d binary.Decoder) error {
	if _, err := d.Float32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidF32) ID() binary.ID      { return binaryIDCmdVoidF32 }
func (*binaryClassCmdVoidF32) New() binary.Object { return &CmdVoidF32{} }
func (*binaryClassCmdVoidF32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidF32(e, obj.(*CmdVoidF32))
}
func (*binaryClassCmdVoidF32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidF32{}
	return obj, doDecodeCmdVoidF32(d, obj)
}
func (*binaryClassCmdVoidF32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidF32(d, obj.(*CmdVoidF32))
}
func (*binaryClassCmdVoidF32) Skip(d binary.Decoder) error { return doSkipCmdVoidF32(d) }
func (*binaryClassCmdVoidF32) Schema() *schema.Class       { return schemaCmdVoidF32 }

var schemaCmdVoidF32 = &schema.Class{
	TypeID: binaryIDCmdVoidF32,
	Name:   "CmdVoidF32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "float32", Method: schema.Float32}},
	},
}

type binaryClassCmdVoidF64 struct{}

func (*CmdVoidF64) Class() binary.Class {
	return (*binaryClassCmdVoidF64)(nil)
}
func doEncodeCmdVoidF64(e binary.Encoder, o *CmdVoidF64) error {
	if err := e.Float64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidF64(d binary.Decoder, o *CmdVoidF64) error {
	if obj, err := d.Float64(); err != nil {
		return err
	} else {
		o.A = float64(obj)
	}
	return nil
}
func doSkipCmdVoidF64(d binary.Decoder) error {
	if _, err := d.Float64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidF64) ID() binary.ID      { return binaryIDCmdVoidF64 }
func (*binaryClassCmdVoidF64) New() binary.Object { return &CmdVoidF64{} }
func (*binaryClassCmdVoidF64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidF64(e, obj.(*CmdVoidF64))
}
func (*binaryClassCmdVoidF64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidF64{}
	return obj, doDecodeCmdVoidF64(d, obj)
}
func (*binaryClassCmdVoidF64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidF64(d, obj.(*CmdVoidF64))
}
func (*binaryClassCmdVoidF64) Skip(d binary.Decoder) error { return doSkipCmdVoidF64(d) }
func (*binaryClassCmdVoidF64) Schema() *schema.Class       { return schemaCmdVoidF64 }

var schemaCmdVoidF64 = &schema.Class{
	TypeID: binaryIDCmdVoidF64,
	Name:   "CmdVoidF64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "float64", Method: schema.Float64}},
	},
}

type binaryClassCmdVoidOut3Remapped struct{}

func (*CmdVoidOut3Remapped) Class() binary.Class {
	return (*binaryClassCmdVoidOut3Remapped)(nil)
}
func doEncodeCmdVoidOut3Remapped(e binary.Encoder, o *CmdVoidOut3Remapped) error {
	if err := e.Uint32(uint32(o.A)); err != nil {
		return err
	}
	if err := e.Uint32(uint32(o.B)); err != nil {
		return err
	}
	if err := e.Uint32(uint32(o.C)); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOut3Remapped(d binary.Decoder, o *CmdVoidOut3Remapped) error {
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = remapped(obj)
	}
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.B = remapped(obj)
	}
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.C = remapped(obj)
	}
	return nil
}
func doSkipCmdVoidOut3Remapped(d binary.Decoder) error {
	if _, err := d.Uint32(); err != nil {
		return err
	}
	if _, err := d.Uint32(); err != nil {
		return err
	}
	if _, err := d.Uint32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOut3Remapped) ID() binary.ID      { return binaryIDCmdVoidOut3Remapped }
func (*binaryClassCmdVoidOut3Remapped) New() binary.Object { return &CmdVoidOut3Remapped{} }
func (*binaryClassCmdVoidOut3Remapped) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOut3Remapped(e, obj.(*CmdVoidOut3Remapped))
}
func (*binaryClassCmdVoidOut3Remapped) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOut3Remapped{}
	return obj, doDecodeCmdVoidOut3Remapped(d, obj)
}
func (*binaryClassCmdVoidOut3Remapped) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOut3Remapped(d, obj.(*CmdVoidOut3Remapped))
}
func (*binaryClassCmdVoidOut3Remapped) Skip(d binary.Decoder) error {
	return doSkipCmdVoidOut3Remapped(d)
}
func (*binaryClassCmdVoidOut3Remapped) Schema() *schema.Class { return schemaCmdVoidOut3Remapped }

var schemaCmdVoidOut3Remapped = &schema.Class{
	TypeID: binaryIDCmdVoidOut3Remapped,
	Name:   "CmdVoidOut3Remapped",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
		schema.Field{Declared: "B", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
		schema.Field{Declared: "C", Type: &schema.Primitive{Name: "remapped", Method: schema.Uint32}},
	},
}

type binaryClassCmdVoidOut3Strings struct{}

func (*CmdVoidOut3Strings) Class() binary.Class {
	return (*binaryClassCmdVoidOut3Strings)(nil)
}
func doEncodeCmdVoidOut3Strings(e binary.Encoder, o *CmdVoidOut3Strings) error {
	if err := e.String(o.A); err != nil {
		return err
	}
	if err := e.String(o.B); err != nil {
		return err
	}
	if err := e.String(o.C); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOut3Strings(d binary.Decoder, o *CmdVoidOut3Strings) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.A = string(obj)
	}
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.B = string(obj)
	}
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.C = string(obj)
	}
	return nil
}
func doSkipCmdVoidOut3Strings(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	if err := d.SkipString(); err != nil {
		return err
	}
	if err := d.SkipString(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOut3Strings) ID() binary.ID      { return binaryIDCmdVoidOut3Strings }
func (*binaryClassCmdVoidOut3Strings) New() binary.Object { return &CmdVoidOut3Strings{} }
func (*binaryClassCmdVoidOut3Strings) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOut3Strings(e, obj.(*CmdVoidOut3Strings))
}
func (*binaryClassCmdVoidOut3Strings) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOut3Strings{}
	return obj, doDecodeCmdVoidOut3Strings(d, obj)
}
func (*binaryClassCmdVoidOut3Strings) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOut3Strings(d, obj.(*CmdVoidOut3Strings))
}
func (*binaryClassCmdVoidOut3Strings) Skip(d binary.Decoder) error { return doSkipCmdVoidOut3Strings(d) }
func (*binaryClassCmdVoidOut3Strings) Schema() *schema.Class       { return schemaCmdVoidOut3Strings }

var schemaCmdVoidOut3Strings = &schema.Class{
	TypeID: binaryIDCmdVoidOut3Strings,
	Name:   "CmdVoidOut3Strings",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		schema.Field{Declared: "B", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		schema.Field{Declared: "C", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassCmdVoidOutArrayOfRemapped struct{}

func (*CmdVoidOutArrayOfRemapped) Class() binary.Class {
	return (*binaryClassCmdVoidOutArrayOfRemapped)(nil)
}
func doEncodeCmdVoidOutArrayOfRemapped(e binary.Encoder, o *CmdVoidOutArrayOfRemapped) error {
	if err := e.Uint32(uint32(len(o.A))); err != nil {
		return err
	}
	for i := range o.A {
		if err := e.Uint32(uint32(o.A[i])); err != nil {
			return err
		}
	}
	return nil
}
func doDecodeCmdVoidOutArrayOfRemapped(d binary.Decoder, o *CmdVoidOutArrayOfRemapped) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = make(RemappedArray, count)
		for i := range o.A {
			if obj, err := d.Uint32(); err != nil {
				return err
			} else {
				o.A[i] = remapped(obj)
			}
		}
	}
	return nil
}
func doSkipCmdVoidOutArrayOfRemapped(d binary.Decoder) error {
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if _, err := d.Uint32(); err != nil {
				return err
			}
		}
	}
	return nil
}
func (*binaryClassCmdVoidOutArrayOfRemapped) ID() binary.ID      { return binaryIDCmdVoidOutArrayOfRemapped }
func (*binaryClassCmdVoidOutArrayOfRemapped) New() binary.Object { return &CmdVoidOutArrayOfRemapped{} }
func (*binaryClassCmdVoidOutArrayOfRemapped) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutArrayOfRemapped(e, obj.(*CmdVoidOutArrayOfRemapped))
}
func (*binaryClassCmdVoidOutArrayOfRemapped) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutArrayOfRemapped{}
	return obj, doDecodeCmdVoidOutArrayOfRemapped(d, obj)
}
func (*binaryClassCmdVoidOutArrayOfRemapped) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutArrayOfRemapped(d, obj.(*CmdVoidOutArrayOfRemapped))
}
func (*binaryClassCmdVoidOutArrayOfRemapped) Skip(d binary.Decoder) error {
	return doSkipCmdVoidOutArrayOfRemapped(d)
}
func (*binaryClassCmdVoidOutArrayOfRemapped) Schema() *schema.Class {
	return schemaCmdVoidOutArrayOfRemapped
}

var schemaCmdVoidOutArrayOfRemapped = &schema.Class{
	TypeID: binaryIDCmdVoidOutArrayOfRemapped,
	Name:   "CmdVoidOutArrayOfRemapped",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Slice{Alias: "RemappedArray", ValueType: &schema.Primitive{Name: "remapped", Method: schema.Uint32}}},
	},
}

type binaryClassCmdVoidOutBool struct{}

func (*CmdVoidOutBool) Class() binary.Class {
	return (*binaryClassCmdVoidOutBool)(nil)
}
func doEncodeCmdVoidOutBool(e binary.Encoder, o *CmdVoidOutBool) error {
	if err := e.Bool(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutBool(d binary.Decoder, o *CmdVoidOutBool) error {
	if obj, err := d.Bool(); err != nil {
		return err
	} else {
		o.A = bool(obj)
	}
	return nil
}
func doSkipCmdVoidOutBool(d binary.Decoder) error {
	if _, err := d.Bool(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutBool) ID() binary.ID      { return binaryIDCmdVoidOutBool }
func (*binaryClassCmdVoidOutBool) New() binary.Object { return &CmdVoidOutBool{} }
func (*binaryClassCmdVoidOutBool) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutBool(e, obj.(*CmdVoidOutBool))
}
func (*binaryClassCmdVoidOutBool) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutBool{}
	return obj, doDecodeCmdVoidOutBool(d, obj)
}
func (*binaryClassCmdVoidOutBool) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutBool(d, obj.(*CmdVoidOutBool))
}
func (*binaryClassCmdVoidOutBool) Skip(d binary.Decoder) error { return doSkipCmdVoidOutBool(d) }
func (*binaryClassCmdVoidOutBool) Schema() *schema.Class       { return schemaCmdVoidOutBool }

var schemaCmdVoidOutBool = &schema.Class{
	TypeID: binaryIDCmdVoidOutBool,
	Name:   "CmdVoidOutBool",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "bool", Method: schema.Bool}},
	},
}

type binaryClassCmdVoidOutF32 struct{}

func (*CmdVoidOutF32) Class() binary.Class {
	return (*binaryClassCmdVoidOutF32)(nil)
}
func doEncodeCmdVoidOutF32(e binary.Encoder, o *CmdVoidOutF32) error {
	if err := e.Float32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutF32(d binary.Decoder, o *CmdVoidOutF32) error {
	if obj, err := d.Float32(); err != nil {
		return err
	} else {
		o.A = float32(obj)
	}
	return nil
}
func doSkipCmdVoidOutF32(d binary.Decoder) error {
	if _, err := d.Float32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutF32) ID() binary.ID      { return binaryIDCmdVoidOutF32 }
func (*binaryClassCmdVoidOutF32) New() binary.Object { return &CmdVoidOutF32{} }
func (*binaryClassCmdVoidOutF32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutF32(e, obj.(*CmdVoidOutF32))
}
func (*binaryClassCmdVoidOutF32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutF32{}
	return obj, doDecodeCmdVoidOutF32(d, obj)
}
func (*binaryClassCmdVoidOutF32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutF32(d, obj.(*CmdVoidOutF32))
}
func (*binaryClassCmdVoidOutF32) Skip(d binary.Decoder) error { return doSkipCmdVoidOutF32(d) }
func (*binaryClassCmdVoidOutF32) Schema() *schema.Class       { return schemaCmdVoidOutF32 }

var schemaCmdVoidOutF32 = &schema.Class{
	TypeID: binaryIDCmdVoidOutF32,
	Name:   "CmdVoidOutF32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "float32", Method: schema.Float32}},
	},
}

type binaryClassCmdVoidOutF64 struct{}

func (*CmdVoidOutF64) Class() binary.Class {
	return (*binaryClassCmdVoidOutF64)(nil)
}
func doEncodeCmdVoidOutF64(e binary.Encoder, o *CmdVoidOutF64) error {
	if err := e.Float64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutF64(d binary.Decoder, o *CmdVoidOutF64) error {
	if obj, err := d.Float64(); err != nil {
		return err
	} else {
		o.A = float64(obj)
	}
	return nil
}
func doSkipCmdVoidOutF64(d binary.Decoder) error {
	if _, err := d.Float64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutF64) ID() binary.ID      { return binaryIDCmdVoidOutF64 }
func (*binaryClassCmdVoidOutF64) New() binary.Object { return &CmdVoidOutF64{} }
func (*binaryClassCmdVoidOutF64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutF64(e, obj.(*CmdVoidOutF64))
}
func (*binaryClassCmdVoidOutF64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutF64{}
	return obj, doDecodeCmdVoidOutF64(d, obj)
}
func (*binaryClassCmdVoidOutF64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutF64(d, obj.(*CmdVoidOutF64))
}
func (*binaryClassCmdVoidOutF64) Skip(d binary.Decoder) error { return doSkipCmdVoidOutF64(d) }
func (*binaryClassCmdVoidOutF64) Schema() *schema.Class       { return schemaCmdVoidOutF64 }

var schemaCmdVoidOutF64 = &schema.Class{
	TypeID: binaryIDCmdVoidOutF64,
	Name:   "CmdVoidOutF64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "float64", Method: schema.Float64}},
	},
}

type binaryClassCmdVoidOutFixedSizeBuffer struct{}

func (*CmdVoidOutFixedSizeBuffer) Class() binary.Class {
	return (*binaryClassCmdVoidOutFixedSizeBuffer)(nil)
}
func doEncodeCmdVoidOutFixedSizeBuffer(e binary.Encoder, o *CmdVoidOutFixedSizeBuffer) error {
	if err := e.Uint64(uint64(o.A)); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutFixedSizeBuffer(d binary.Decoder, o *CmdVoidOutFixedSizeBuffer) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.A = memory.Pointer(obj)
	}
	return nil
}
func doSkipCmdVoidOutFixedSizeBuffer(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutFixedSizeBuffer) ID() binary.ID      { return binaryIDCmdVoidOutFixedSizeBuffer }
func (*binaryClassCmdVoidOutFixedSizeBuffer) New() binary.Object { return &CmdVoidOutFixedSizeBuffer{} }
func (*binaryClassCmdVoidOutFixedSizeBuffer) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutFixedSizeBuffer(e, obj.(*CmdVoidOutFixedSizeBuffer))
}
func (*binaryClassCmdVoidOutFixedSizeBuffer) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutFixedSizeBuffer{}
	return obj, doDecodeCmdVoidOutFixedSizeBuffer(d, obj)
}
func (*binaryClassCmdVoidOutFixedSizeBuffer) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutFixedSizeBuffer(d, obj.(*CmdVoidOutFixedSizeBuffer))
}
func (*binaryClassCmdVoidOutFixedSizeBuffer) Skip(d binary.Decoder) error {
	return doSkipCmdVoidOutFixedSizeBuffer(d)
}
func (*binaryClassCmdVoidOutFixedSizeBuffer) Schema() *schema.Class {
	return schemaCmdVoidOutFixedSizeBuffer
}

var schemaCmdVoidOutFixedSizeBuffer = &schema.Class{
	TypeID: binaryIDCmdVoidOutFixedSizeBuffer,
	Name:   "CmdVoidOutFixedSizeBuffer",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "memory.Pointer", Method: schema.Uint64}},
	},
}

type binaryClassCmdVoidOutS16 struct{}

func (*CmdVoidOutS16) Class() binary.Class {
	return (*binaryClassCmdVoidOutS16)(nil)
}
func doEncodeCmdVoidOutS16(e binary.Encoder, o *CmdVoidOutS16) error {
	if err := e.Int16(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutS16(d binary.Decoder, o *CmdVoidOutS16) error {
	if obj, err := d.Int16(); err != nil {
		return err
	} else {
		o.A = int16(obj)
	}
	return nil
}
func doSkipCmdVoidOutS16(d binary.Decoder) error {
	if _, err := d.Int16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutS16) ID() binary.ID      { return binaryIDCmdVoidOutS16 }
func (*binaryClassCmdVoidOutS16) New() binary.Object { return &CmdVoidOutS16{} }
func (*binaryClassCmdVoidOutS16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutS16(e, obj.(*CmdVoidOutS16))
}
func (*binaryClassCmdVoidOutS16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutS16{}
	return obj, doDecodeCmdVoidOutS16(d, obj)
}
func (*binaryClassCmdVoidOutS16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutS16(d, obj.(*CmdVoidOutS16))
}
func (*binaryClassCmdVoidOutS16) Skip(d binary.Decoder) error { return doSkipCmdVoidOutS16(d) }
func (*binaryClassCmdVoidOutS16) Schema() *schema.Class       { return schemaCmdVoidOutS16 }

var schemaCmdVoidOutS16 = &schema.Class{
	TypeID: binaryIDCmdVoidOutS16,
	Name:   "CmdVoidOutS16",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int16", Method: schema.Int16}},
	},
}

type binaryClassCmdVoidOutS32 struct{}

func (*CmdVoidOutS32) Class() binary.Class {
	return (*binaryClassCmdVoidOutS32)(nil)
}
func doEncodeCmdVoidOutS32(e binary.Encoder, o *CmdVoidOutS32) error {
	if err := e.Int32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutS32(d binary.Decoder, o *CmdVoidOutS32) error {
	if obj, err := d.Int32(); err != nil {
		return err
	} else {
		o.A = int32(obj)
	}
	return nil
}
func doSkipCmdVoidOutS32(d binary.Decoder) error {
	if _, err := d.Int32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutS32) ID() binary.ID      { return binaryIDCmdVoidOutS32 }
func (*binaryClassCmdVoidOutS32) New() binary.Object { return &CmdVoidOutS32{} }
func (*binaryClassCmdVoidOutS32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutS32(e, obj.(*CmdVoidOutS32))
}
func (*binaryClassCmdVoidOutS32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutS32{}
	return obj, doDecodeCmdVoidOutS32(d, obj)
}
func (*binaryClassCmdVoidOutS32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutS32(d, obj.(*CmdVoidOutS32))
}
func (*binaryClassCmdVoidOutS32) Skip(d binary.Decoder) error { return doSkipCmdVoidOutS32(d) }
func (*binaryClassCmdVoidOutS32) Schema() *schema.Class       { return schemaCmdVoidOutS32 }

var schemaCmdVoidOutS32 = &schema.Class{
	TypeID: binaryIDCmdVoidOutS32,
	Name:   "CmdVoidOutS32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int32", Method: schema.Int32}},
	},
}

type binaryClassCmdVoidOutS64 struct{}

func (*CmdVoidOutS64) Class() binary.Class {
	return (*binaryClassCmdVoidOutS64)(nil)
}
func doEncodeCmdVoidOutS64(e binary.Encoder, o *CmdVoidOutS64) error {
	if err := e.Int64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutS64(d binary.Decoder, o *CmdVoidOutS64) error {
	if obj, err := d.Int64(); err != nil {
		return err
	} else {
		o.A = int64(obj)
	}
	return nil
}
func doSkipCmdVoidOutS64(d binary.Decoder) error {
	if _, err := d.Int64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutS64) ID() binary.ID      { return binaryIDCmdVoidOutS64 }
func (*binaryClassCmdVoidOutS64) New() binary.Object { return &CmdVoidOutS64{} }
func (*binaryClassCmdVoidOutS64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutS64(e, obj.(*CmdVoidOutS64))
}
func (*binaryClassCmdVoidOutS64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutS64{}
	return obj, doDecodeCmdVoidOutS64(d, obj)
}
func (*binaryClassCmdVoidOutS64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutS64(d, obj.(*CmdVoidOutS64))
}
func (*binaryClassCmdVoidOutS64) Skip(d binary.Decoder) error { return doSkipCmdVoidOutS64(d) }
func (*binaryClassCmdVoidOutS64) Schema() *schema.Class       { return schemaCmdVoidOutS64 }

var schemaCmdVoidOutS64 = &schema.Class{
	TypeID: binaryIDCmdVoidOutS64,
	Name:   "CmdVoidOutS64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int64", Method: schema.Int64}},
	},
}

type binaryClassCmdVoidOutS8 struct{}

func (*CmdVoidOutS8) Class() binary.Class {
	return (*binaryClassCmdVoidOutS8)(nil)
}
func doEncodeCmdVoidOutS8(e binary.Encoder, o *CmdVoidOutS8) error {
	if err := e.Int8(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutS8(d binary.Decoder, o *CmdVoidOutS8) error {
	if obj, err := d.Int8(); err != nil {
		return err
	} else {
		o.A = int8(obj)
	}
	return nil
}
func doSkipCmdVoidOutS8(d binary.Decoder) error {
	if _, err := d.Int8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutS8) ID() binary.ID      { return binaryIDCmdVoidOutS8 }
func (*binaryClassCmdVoidOutS8) New() binary.Object { return &CmdVoidOutS8{} }
func (*binaryClassCmdVoidOutS8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutS8(e, obj.(*CmdVoidOutS8))
}
func (*binaryClassCmdVoidOutS8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutS8{}
	return obj, doDecodeCmdVoidOutS8(d, obj)
}
func (*binaryClassCmdVoidOutS8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutS8(d, obj.(*CmdVoidOutS8))
}
func (*binaryClassCmdVoidOutS8) Skip(d binary.Decoder) error { return doSkipCmdVoidOutS8(d) }
func (*binaryClassCmdVoidOutS8) Schema() *schema.Class       { return schemaCmdVoidOutS8 }

var schemaCmdVoidOutS8 = &schema.Class{
	TypeID: binaryIDCmdVoidOutS8,
	Name:   "CmdVoidOutS8",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int8", Method: schema.Int8}},
	},
}

type binaryClassCmdVoidOutString struct{}

func (*CmdVoidOutString) Class() binary.Class {
	return (*binaryClassCmdVoidOutString)(nil)
}
func doEncodeCmdVoidOutString(e binary.Encoder, o *CmdVoidOutString) error {
	if err := e.String(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutString(d binary.Decoder, o *CmdVoidOutString) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.A = string(obj)
	}
	return nil
}
func doSkipCmdVoidOutString(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutString) ID() binary.ID      { return binaryIDCmdVoidOutString }
func (*binaryClassCmdVoidOutString) New() binary.Object { return &CmdVoidOutString{} }
func (*binaryClassCmdVoidOutString) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutString(e, obj.(*CmdVoidOutString))
}
func (*binaryClassCmdVoidOutString) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutString{}
	return obj, doDecodeCmdVoidOutString(d, obj)
}
func (*binaryClassCmdVoidOutString) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutString(d, obj.(*CmdVoidOutString))
}
func (*binaryClassCmdVoidOutString) Skip(d binary.Decoder) error { return doSkipCmdVoidOutString(d) }
func (*binaryClassCmdVoidOutString) Schema() *schema.Class       { return schemaCmdVoidOutString }

var schemaCmdVoidOutString = &schema.Class{
	TypeID: binaryIDCmdVoidOutString,
	Name:   "CmdVoidOutString",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassCmdVoidOutU16 struct{}

func (*CmdVoidOutU16) Class() binary.Class {
	return (*binaryClassCmdVoidOutU16)(nil)
}
func doEncodeCmdVoidOutU16(e binary.Encoder, o *CmdVoidOutU16) error {
	if err := e.Uint16(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutU16(d binary.Decoder, o *CmdVoidOutU16) error {
	if obj, err := d.Uint16(); err != nil {
		return err
	} else {
		o.A = uint16(obj)
	}
	return nil
}
func doSkipCmdVoidOutU16(d binary.Decoder) error {
	if _, err := d.Uint16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutU16) ID() binary.ID      { return binaryIDCmdVoidOutU16 }
func (*binaryClassCmdVoidOutU16) New() binary.Object { return &CmdVoidOutU16{} }
func (*binaryClassCmdVoidOutU16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutU16(e, obj.(*CmdVoidOutU16))
}
func (*binaryClassCmdVoidOutU16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutU16{}
	return obj, doDecodeCmdVoidOutU16(d, obj)
}
func (*binaryClassCmdVoidOutU16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutU16(d, obj.(*CmdVoidOutU16))
}
func (*binaryClassCmdVoidOutU16) Skip(d binary.Decoder) error { return doSkipCmdVoidOutU16(d) }
func (*binaryClassCmdVoidOutU16) Schema() *schema.Class       { return schemaCmdVoidOutU16 }

var schemaCmdVoidOutU16 = &schema.Class{
	TypeID: binaryIDCmdVoidOutU16,
	Name:   "CmdVoidOutU16",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint16", Method: schema.Uint16}},
	},
}

type binaryClassCmdVoidOutU32 struct{}

func (*CmdVoidOutU32) Class() binary.Class {
	return (*binaryClassCmdVoidOutU32)(nil)
}
func doEncodeCmdVoidOutU32(e binary.Encoder, o *CmdVoidOutU32) error {
	if err := e.Uint32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutU32(d binary.Decoder, o *CmdVoidOutU32) error {
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = uint32(obj)
	}
	return nil
}
func doSkipCmdVoidOutU32(d binary.Decoder) error {
	if _, err := d.Uint32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutU32) ID() binary.ID      { return binaryIDCmdVoidOutU32 }
func (*binaryClassCmdVoidOutU32) New() binary.Object { return &CmdVoidOutU32{} }
func (*binaryClassCmdVoidOutU32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutU32(e, obj.(*CmdVoidOutU32))
}
func (*binaryClassCmdVoidOutU32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutU32{}
	return obj, doDecodeCmdVoidOutU32(d, obj)
}
func (*binaryClassCmdVoidOutU32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutU32(d, obj.(*CmdVoidOutU32))
}
func (*binaryClassCmdVoidOutU32) Skip(d binary.Decoder) error { return doSkipCmdVoidOutU32(d) }
func (*binaryClassCmdVoidOutU32) Schema() *schema.Class       { return schemaCmdVoidOutU32 }

var schemaCmdVoidOutU32 = &schema.Class{
	TypeID: binaryIDCmdVoidOutU32,
	Name:   "CmdVoidOutU32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
	},
}

type binaryClassCmdVoidOutU64 struct{}

func (*CmdVoidOutU64) Class() binary.Class {
	return (*binaryClassCmdVoidOutU64)(nil)
}
func doEncodeCmdVoidOutU64(e binary.Encoder, o *CmdVoidOutU64) error {
	if err := e.Uint64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutU64(d binary.Decoder, o *CmdVoidOutU64) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.A = uint64(obj)
	}
	return nil
}
func doSkipCmdVoidOutU64(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutU64) ID() binary.ID      { return binaryIDCmdVoidOutU64 }
func (*binaryClassCmdVoidOutU64) New() binary.Object { return &CmdVoidOutU64{} }
func (*binaryClassCmdVoidOutU64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutU64(e, obj.(*CmdVoidOutU64))
}
func (*binaryClassCmdVoidOutU64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutU64{}
	return obj, doDecodeCmdVoidOutU64(d, obj)
}
func (*binaryClassCmdVoidOutU64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutU64(d, obj.(*CmdVoidOutU64))
}
func (*binaryClassCmdVoidOutU64) Skip(d binary.Decoder) error { return doSkipCmdVoidOutU64(d) }
func (*binaryClassCmdVoidOutU64) Schema() *schema.Class       { return schemaCmdVoidOutU64 }

var schemaCmdVoidOutU64 = &schema.Class{
	TypeID: binaryIDCmdVoidOutU64,
	Name:   "CmdVoidOutU64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
	},
}

type binaryClassCmdVoidOutU8 struct{}

func (*CmdVoidOutU8) Class() binary.Class {
	return (*binaryClassCmdVoidOutU8)(nil)
}
func doEncodeCmdVoidOutU8(e binary.Encoder, o *CmdVoidOutU8) error {
	if err := e.Uint8(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidOutU8(d binary.Decoder, o *CmdVoidOutU8) error {
	if obj, err := d.Uint8(); err != nil {
		return err
	} else {
		o.A = uint8(obj)
	}
	return nil
}
func doSkipCmdVoidOutU8(d binary.Decoder) error {
	if _, err := d.Uint8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidOutU8) ID() binary.ID      { return binaryIDCmdVoidOutU8 }
func (*binaryClassCmdVoidOutU8) New() binary.Object { return &CmdVoidOutU8{} }
func (*binaryClassCmdVoidOutU8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidOutU8(e, obj.(*CmdVoidOutU8))
}
func (*binaryClassCmdVoidOutU8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidOutU8{}
	return obj, doDecodeCmdVoidOutU8(d, obj)
}
func (*binaryClassCmdVoidOutU8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidOutU8(d, obj.(*CmdVoidOutU8))
}
func (*binaryClassCmdVoidOutU8) Skip(d binary.Decoder) error { return doSkipCmdVoidOutU8(d) }
func (*binaryClassCmdVoidOutU8) Schema() *schema.Class       { return schemaCmdVoidOutU8 }

var schemaCmdVoidOutU8 = &schema.Class{
	TypeID: binaryIDCmdVoidOutU8,
	Name:   "CmdVoidOutU8",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint8", Method: schema.Uint8}},
	},
}

type binaryClassCmdVoidS16 struct{}

func (*CmdVoidS16) Class() binary.Class {
	return (*binaryClassCmdVoidS16)(nil)
}
func doEncodeCmdVoidS16(e binary.Encoder, o *CmdVoidS16) error {
	if err := e.Int16(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidS16(d binary.Decoder, o *CmdVoidS16) error {
	if obj, err := d.Int16(); err != nil {
		return err
	} else {
		o.A = int16(obj)
	}
	return nil
}
func doSkipCmdVoidS16(d binary.Decoder) error {
	if _, err := d.Int16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidS16) ID() binary.ID      { return binaryIDCmdVoidS16 }
func (*binaryClassCmdVoidS16) New() binary.Object { return &CmdVoidS16{} }
func (*binaryClassCmdVoidS16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidS16(e, obj.(*CmdVoidS16))
}
func (*binaryClassCmdVoidS16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidS16{}
	return obj, doDecodeCmdVoidS16(d, obj)
}
func (*binaryClassCmdVoidS16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidS16(d, obj.(*CmdVoidS16))
}
func (*binaryClassCmdVoidS16) Skip(d binary.Decoder) error { return doSkipCmdVoidS16(d) }
func (*binaryClassCmdVoidS16) Schema() *schema.Class       { return schemaCmdVoidS16 }

var schemaCmdVoidS16 = &schema.Class{
	TypeID: binaryIDCmdVoidS16,
	Name:   "CmdVoidS16",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int16", Method: schema.Int16}},
	},
}

type binaryClassCmdVoidS32 struct{}

func (*CmdVoidS32) Class() binary.Class {
	return (*binaryClassCmdVoidS32)(nil)
}
func doEncodeCmdVoidS32(e binary.Encoder, o *CmdVoidS32) error {
	if err := e.Int32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidS32(d binary.Decoder, o *CmdVoidS32) error {
	if obj, err := d.Int32(); err != nil {
		return err
	} else {
		o.A = int32(obj)
	}
	return nil
}
func doSkipCmdVoidS32(d binary.Decoder) error {
	if _, err := d.Int32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidS32) ID() binary.ID      { return binaryIDCmdVoidS32 }
func (*binaryClassCmdVoidS32) New() binary.Object { return &CmdVoidS32{} }
func (*binaryClassCmdVoidS32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidS32(e, obj.(*CmdVoidS32))
}
func (*binaryClassCmdVoidS32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidS32{}
	return obj, doDecodeCmdVoidS32(d, obj)
}
func (*binaryClassCmdVoidS32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidS32(d, obj.(*CmdVoidS32))
}
func (*binaryClassCmdVoidS32) Skip(d binary.Decoder) error { return doSkipCmdVoidS32(d) }
func (*binaryClassCmdVoidS32) Schema() *schema.Class       { return schemaCmdVoidS32 }

var schemaCmdVoidS32 = &schema.Class{
	TypeID: binaryIDCmdVoidS32,
	Name:   "CmdVoidS32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int32", Method: schema.Int32}},
	},
}

type binaryClassCmdVoidS64 struct{}

func (*CmdVoidS64) Class() binary.Class {
	return (*binaryClassCmdVoidS64)(nil)
}
func doEncodeCmdVoidS64(e binary.Encoder, o *CmdVoidS64) error {
	if err := e.Int64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidS64(d binary.Decoder, o *CmdVoidS64) error {
	if obj, err := d.Int64(); err != nil {
		return err
	} else {
		o.A = int64(obj)
	}
	return nil
}
func doSkipCmdVoidS64(d binary.Decoder) error {
	if _, err := d.Int64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidS64) ID() binary.ID      { return binaryIDCmdVoidS64 }
func (*binaryClassCmdVoidS64) New() binary.Object { return &CmdVoidS64{} }
func (*binaryClassCmdVoidS64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidS64(e, obj.(*CmdVoidS64))
}
func (*binaryClassCmdVoidS64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidS64{}
	return obj, doDecodeCmdVoidS64(d, obj)
}
func (*binaryClassCmdVoidS64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidS64(d, obj.(*CmdVoidS64))
}
func (*binaryClassCmdVoidS64) Skip(d binary.Decoder) error { return doSkipCmdVoidS64(d) }
func (*binaryClassCmdVoidS64) Schema() *schema.Class       { return schemaCmdVoidS64 }

var schemaCmdVoidS64 = &schema.Class{
	TypeID: binaryIDCmdVoidS64,
	Name:   "CmdVoidS64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int64", Method: schema.Int64}},
	},
}

type binaryClassCmdVoidS8 struct{}

func (*CmdVoidS8) Class() binary.Class {
	return (*binaryClassCmdVoidS8)(nil)
}
func doEncodeCmdVoidS8(e binary.Encoder, o *CmdVoidS8) error {
	if err := e.Int8(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidS8(d binary.Decoder, o *CmdVoidS8) error {
	if obj, err := d.Int8(); err != nil {
		return err
	} else {
		o.A = int8(obj)
	}
	return nil
}
func doSkipCmdVoidS8(d binary.Decoder) error {
	if _, err := d.Int8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidS8) ID() binary.ID      { return binaryIDCmdVoidS8 }
func (*binaryClassCmdVoidS8) New() binary.Object { return &CmdVoidS8{} }
func (*binaryClassCmdVoidS8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidS8(e, obj.(*CmdVoidS8))
}
func (*binaryClassCmdVoidS8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidS8{}
	return obj, doDecodeCmdVoidS8(d, obj)
}
func (*binaryClassCmdVoidS8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidS8(d, obj.(*CmdVoidS8))
}
func (*binaryClassCmdVoidS8) Skip(d binary.Decoder) error { return doSkipCmdVoidS8(d) }
func (*binaryClassCmdVoidS8) Schema() *schema.Class       { return schemaCmdVoidS8 }

var schemaCmdVoidS8 = &schema.Class{
	TypeID: binaryIDCmdVoidS8,
	Name:   "CmdVoidS8",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "int8", Method: schema.Int8}},
	},
}

type binaryClassCmdVoidString struct{}

func (*CmdVoidString) Class() binary.Class {
	return (*binaryClassCmdVoidString)(nil)
}
func doEncodeCmdVoidString(e binary.Encoder, o *CmdVoidString) error {
	if err := e.String(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidString(d binary.Decoder, o *CmdVoidString) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.A = string(obj)
	}
	return nil
}
func doSkipCmdVoidString(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidString) ID() binary.ID      { return binaryIDCmdVoidString }
func (*binaryClassCmdVoidString) New() binary.Object { return &CmdVoidString{} }
func (*binaryClassCmdVoidString) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidString(e, obj.(*CmdVoidString))
}
func (*binaryClassCmdVoidString) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidString{}
	return obj, doDecodeCmdVoidString(d, obj)
}
func (*binaryClassCmdVoidString) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidString(d, obj.(*CmdVoidString))
}
func (*binaryClassCmdVoidString) Skip(d binary.Decoder) error { return doSkipCmdVoidString(d) }
func (*binaryClassCmdVoidString) Schema() *schema.Class       { return schemaCmdVoidString }

var schemaCmdVoidString = &schema.Class{
	TypeID: binaryIDCmdVoidString,
	Name:   "CmdVoidString",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassCmdVoidU16 struct{}

func (*CmdVoidU16) Class() binary.Class {
	return (*binaryClassCmdVoidU16)(nil)
}
func doEncodeCmdVoidU16(e binary.Encoder, o *CmdVoidU16) error {
	if err := e.Uint16(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidU16(d binary.Decoder, o *CmdVoidU16) error {
	if obj, err := d.Uint16(); err != nil {
		return err
	} else {
		o.A = uint16(obj)
	}
	return nil
}
func doSkipCmdVoidU16(d binary.Decoder) error {
	if _, err := d.Uint16(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidU16) ID() binary.ID      { return binaryIDCmdVoidU16 }
func (*binaryClassCmdVoidU16) New() binary.Object { return &CmdVoidU16{} }
func (*binaryClassCmdVoidU16) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidU16(e, obj.(*CmdVoidU16))
}
func (*binaryClassCmdVoidU16) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidU16{}
	return obj, doDecodeCmdVoidU16(d, obj)
}
func (*binaryClassCmdVoidU16) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidU16(d, obj.(*CmdVoidU16))
}
func (*binaryClassCmdVoidU16) Skip(d binary.Decoder) error { return doSkipCmdVoidU16(d) }
func (*binaryClassCmdVoidU16) Schema() *schema.Class       { return schemaCmdVoidU16 }

var schemaCmdVoidU16 = &schema.Class{
	TypeID: binaryIDCmdVoidU16,
	Name:   "CmdVoidU16",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint16", Method: schema.Uint16}},
	},
}

type binaryClassCmdVoidU32 struct{}

func (*CmdVoidU32) Class() binary.Class {
	return (*binaryClassCmdVoidU32)(nil)
}
func doEncodeCmdVoidU32(e binary.Encoder, o *CmdVoidU32) error {
	if err := e.Uint32(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidU32(d binary.Decoder, o *CmdVoidU32) error {
	if obj, err := d.Uint32(); err != nil {
		return err
	} else {
		o.A = uint32(obj)
	}
	return nil
}
func doSkipCmdVoidU32(d binary.Decoder) error {
	if _, err := d.Uint32(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidU32) ID() binary.ID      { return binaryIDCmdVoidU32 }
func (*binaryClassCmdVoidU32) New() binary.Object { return &CmdVoidU32{} }
func (*binaryClassCmdVoidU32) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidU32(e, obj.(*CmdVoidU32))
}
func (*binaryClassCmdVoidU32) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidU32{}
	return obj, doDecodeCmdVoidU32(d, obj)
}
func (*binaryClassCmdVoidU32) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidU32(d, obj.(*CmdVoidU32))
}
func (*binaryClassCmdVoidU32) Skip(d binary.Decoder) error { return doSkipCmdVoidU32(d) }
func (*binaryClassCmdVoidU32) Schema() *schema.Class       { return schemaCmdVoidU32 }

var schemaCmdVoidU32 = &schema.Class{
	TypeID: binaryIDCmdVoidU32,
	Name:   "CmdVoidU32",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
	},
}

type binaryClassCmdVoidU64 struct{}

func (*CmdVoidU64) Class() binary.Class {
	return (*binaryClassCmdVoidU64)(nil)
}
func doEncodeCmdVoidU64(e binary.Encoder, o *CmdVoidU64) error {
	if err := e.Uint64(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidU64(d binary.Decoder, o *CmdVoidU64) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.A = uint64(obj)
	}
	return nil
}
func doSkipCmdVoidU64(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidU64) ID() binary.ID      { return binaryIDCmdVoidU64 }
func (*binaryClassCmdVoidU64) New() binary.Object { return &CmdVoidU64{} }
func (*binaryClassCmdVoidU64) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidU64(e, obj.(*CmdVoidU64))
}
func (*binaryClassCmdVoidU64) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidU64{}
	return obj, doDecodeCmdVoidU64(d, obj)
}
func (*binaryClassCmdVoidU64) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidU64(d, obj.(*CmdVoidU64))
}
func (*binaryClassCmdVoidU64) Skip(d binary.Decoder) error { return doSkipCmdVoidU64(d) }
func (*binaryClassCmdVoidU64) Schema() *schema.Class       { return schemaCmdVoidU64 }

var schemaCmdVoidU64 = &schema.Class{
	TypeID: binaryIDCmdVoidU64,
	Name:   "CmdVoidU64",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
	},
}

type binaryClassCmdVoidU8 struct{}

func (*CmdVoidU8) Class() binary.Class {
	return (*binaryClassCmdVoidU8)(nil)
}
func doEncodeCmdVoidU8(e binary.Encoder, o *CmdVoidU8) error {
	if err := e.Uint8(o.A); err != nil {
		return err
	}
	return nil
}
func doDecodeCmdVoidU8(d binary.Decoder, o *CmdVoidU8) error {
	if obj, err := d.Uint8(); err != nil {
		return err
	} else {
		o.A = uint8(obj)
	}
	return nil
}
func doSkipCmdVoidU8(d binary.Decoder) error {
	if _, err := d.Uint8(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassCmdVoidU8) ID() binary.ID      { return binaryIDCmdVoidU8 }
func (*binaryClassCmdVoidU8) New() binary.Object { return &CmdVoidU8{} }
func (*binaryClassCmdVoidU8) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeCmdVoidU8(e, obj.(*CmdVoidU8))
}
func (*binaryClassCmdVoidU8) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &CmdVoidU8{}
	return obj, doDecodeCmdVoidU8(d, obj)
}
func (*binaryClassCmdVoidU8) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeCmdVoidU8(d, obj.(*CmdVoidU8))
}
func (*binaryClassCmdVoidU8) Skip(d binary.Decoder) error { return doSkipCmdVoidU8(d) }
func (*binaryClassCmdVoidU8) Schema() *schema.Class       { return schemaCmdVoidU8 }

var schemaCmdVoidU8 = &schema.Class{
	TypeID: binaryIDCmdVoidU8,
	Name:   "CmdVoidU8",
	Fields: []schema.Field{
		schema.Field{Declared: "A", Type: &schema.Primitive{Name: "uint8", Method: schema.Uint8}},
	},
}

type binaryClassGlobals struct{}

func (*Globals) Class() binary.Class {
	return (*binaryClassGlobals)(nil)
}
func doEncodeGlobals(e binary.Encoder, o *Globals) error {
	return nil
}
func doDecodeGlobals(d binary.Decoder, o *Globals) error {
	return nil
}
func doSkipGlobals(d binary.Decoder) error {
	return nil
}
func (*binaryClassGlobals) ID() binary.ID      { return binaryIDGlobals }
func (*binaryClassGlobals) New() binary.Object { return &Globals{} }
func (*binaryClassGlobals) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeGlobals(e, obj.(*Globals))
}
func (*binaryClassGlobals) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &Globals{}
	return obj, doDecodeGlobals(d, obj)
}
func (*binaryClassGlobals) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeGlobals(d, obj.(*Globals))
}
func (*binaryClassGlobals) Skip(d binary.Decoder) error { return doSkipGlobals(d) }
func (*binaryClassGlobals) Schema() *schema.Class       { return schemaGlobals }

var schemaGlobals = &schema.Class{
	TypeID: binaryIDGlobals,
	Name:   "Globals",
	Fields: []schema.Field{},
}
