////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package memory

import (
	"fmt"

	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/binary/schema"
)

var Namespace = registry.NewNamespace()

func init() {
	registry.Global.AddFallbacks(Namespace)
	Namespace.Add((*Pointer)(nil).Class())
	Namespace.Add((*Range)(nil).Class())
}

type binaryClassPointer struct{}

func (*Pointer) Class() binary.Class {
	return (*binaryClassPointer)(nil)
}
func doEncodePointer(e binary.Encoder, o *Pointer) {
	e.Uint64(o.Address)
	e.Uint32(uint32(o.Pool))
}
func doDecodePointer(d binary.Decoder, o *Pointer) {
	o.Address = uint64(d.Uint64())
	o.Pool = PoolID(d.Uint32())
}
func (*binaryClassPointer) Encode(e binary.Encoder, obj binary.Object) {
	doEncodePointer(e, obj.(*Pointer))
}
func (*binaryClassPointer) Decode(d binary.Decoder) binary.Object {
	obj := &Pointer{}
	doDecodePointer(d, obj)
	return obj
}
func (*binaryClassPointer) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodePointer(d, obj.(*Pointer))
}
func (*binaryClassPointer) Schema() *binary.Entity { return schemaPointer }

var schemaPointer = &binary.Entity{
	Package:  "memory",
	Identity: "Pointer",
	Fields: []binary.Field{
		{Declared: "Address", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
		{Declared: "Pool", Type: &schema.Primitive{Name: "PoolID", Method: schema.Uint32}},
	},
}

type binaryClassRange struct{}

func (*Range) Class() binary.Class {
	return (*binaryClassRange)(nil)
}
func doEncodeRange(e binary.Encoder, o *Range) {
	e.Uint64(o.Base)
	e.Uint64(o.Size)
}
func doDecodeRange(d binary.Decoder, o *Range) {
	o.Base = uint64(d.Uint64())
	o.Size = uint64(d.Uint64())
}
func (*binaryClassRange) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeRange(e, obj.(*Range))
}
func (*binaryClassRange) Decode(d binary.Decoder) binary.Object {
	obj := &Range{}
	doDecodeRange(d, obj)
	return obj
}
func (*binaryClassRange) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeRange(d, obj.(*Range))
}
func (*binaryClassRange) Schema() *binary.Entity { return schemaRange }

var schemaRange = &binary.Entity{
	Package:  "memory",
	Identity: "Range",
	Fields: []binary.Field{
		{Declared: "Base", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
		{Declared: "Size", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
	},
}

var ConstantValues schema.Constants

var _PoolID_map = map[PoolID]string{}

func init() {
	_PoolID_map[0] = "ApplicationPool"

	ConstantValues = append(ConstantValues, schema.ConstantSet{
		Type: &schema.Primitive{Name: "PoolID", Method: schema.Uint32},
		Entries: []schema.Constant{
			{Name: "ApplicationPool", Value: uint32(0)},
		},
	})
}

func (v PoolID) String() string {
	if s, ok := _PoolID_map[v]; ok {
		return s
	}
	return fmt.Sprintf("PoolID(%d)", v)
}

func (v *PoolID) Parse(s string) error {
	for k, t := range _PoolID_map {
		if s == t {
			*v = k
			return nil
		}
	}
	return fmt.Errorf("%s not in PoolID", s)
}
