buildDir temporaryDirectory

task ndkBuild(type: Exec) {
  def cmd = 'ndk-build' + (osFamily() == 'windows' ? '.cmd' : '')
  commandLine cmd, '-C', file('android').absolutePath, 'NDK_OUT='+temporaryDirectory+'/obj',
              'NDK_APP_DST_DIR='+temporaryDirectory+'/libs/$(TARGET_ARCH_ABI)', '-s', '-j'
}

task ndkClean(type: Exec) {
  def cmd = 'ndk-build' + (osFamily() == 'windows' ? '.cmd' : '')
  commandLine cmd, '-C', file('android').absolutePath, 'NDK_OUT='+temporaryDirectory+'/obj',
              'NDK_APP_DST_DIR='+temporaryDirectory+'/libs/$(TARGET_ARCH_ABI)', '-s', 'clean'
}

task clean (dependsOn: ndkClean) << {}
