////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package service

import (
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/log"
	"android.googlesource.com/platform/tools/gpu/memory"
	"android.googlesource.com/platform/tools/gpu/multiplexer"
	"android.googlesource.com/platform/tools/gpu/rpc"
	"android.googlesource.com/platform/tools/gpu/service/path"
)

// Client is the client interface for RPC calls.
type Client interface {
	// Client exposes all the RPC interface methods.
	RPC
	// Multiplexer returns the multiplexer used for communication to the server.
	Multiplexer() *multiplexer.Multiplexer
	// Namespace returns the custom namespace used for decoding responses from the
	// server, or nil if no custom namespace has been specified.
	Namespace() *registry.Namespace
}
type client struct{ rpc.Client }

// NewClient creates a new rpc client object that uses the multiplexer m for
// communication the namespace n for decoding objects. If n is nil then the
// global namespace is used.
func NewClient(m *multiplexer.Multiplexer, n *registry.Namespace) Client {
	return client{rpc.NewClient(m, n)}
}

// Client compliance
func (c client) Follow(p path.Path, l log.Logger) (res path.Path, err error) {
	var val interface{}
	if val, err = c.Send(&callFollow{p: p}); err == nil {
		res = val.(*resultFollow).value
	} else {
		log.Errorf(l, "RPC Follow failed with error: %v", err)
	}
	return
}

func (c client) Get(p path.Path, l log.Logger) (res interface{}, err error) {
	var val interface{}
	if val, err = c.Send(&callGet{p: p}); err == nil {
		res = val.(*resultGet).value
	} else {
		log.Errorf(l, "RPC Get failed with error: %v", err)
	}
	return
}

func (c client) GetCaptures(l log.Logger) (res []*path.Capture, err error) {
	var val interface{}
	if val, err = c.Send(&callGetCaptures{}); err == nil {
		res = val.(*resultGetCaptures).value
	} else {
		log.Errorf(l, "RPC GetCaptures failed with error: %v", err)
	}
	return
}

func (c client) GetDevices(l log.Logger) (res []*path.Device, err error) {
	var val interface{}
	if val, err = c.Send(&callGetDevices{}); err == nil {
		res = val.(*resultGetDevices).value
	} else {
		log.Errorf(l, "RPC GetDevices failed with error: %v", err)
	}
	return
}

func (c client) GetFramebufferColor(device *path.Device, after *path.Atom, settings RenderSettings, l log.Logger) (res *path.ImageInfo, err error) {
	var val interface{}
	if val, err = c.Send(&callGetFramebufferColor{device: device, after: after, settings: settings}); err == nil {
		res = val.(*resultGetFramebufferColor).value
	} else {
		log.Errorf(l, "RPC GetFramebufferColor failed with error: %v", err)
	}
	return
}

func (c client) GetFramebufferDepth(device *path.Device, after *path.Atom, l log.Logger) (res *path.ImageInfo, err error) {
	var val interface{}
	if val, err = c.Send(&callGetFramebufferDepth{device: device, after: after}); err == nil {
		res = val.(*resultGetFramebufferDepth).value
	} else {
		log.Errorf(l, "RPC GetFramebufferDepth failed with error: %v", err)
	}
	return
}

func (c client) GetMemoryInfo(after *path.Atom, rng memory.Range, l log.Logger) (res *path.MemoryInfo, err error) {
	var val interface{}
	if val, err = c.Send(&callGetMemoryInfo{after: after, rng: rng}); err == nil {
		res = val.(*resultGetMemoryInfo).value
	} else {
		log.Errorf(l, "RPC GetMemoryInfo failed with error: %v", err)
	}
	return
}

func (c client) GetSchema(l log.Logger) (res Schema, err error) {
	var val interface{}
	if val, err = c.Send(&callGetSchema{}); err == nil {
		res = val.(*resultGetSchema).value
	} else {
		log.Errorf(l, "RPC GetSchema failed with error: %v", err)
	}
	return
}

func (c client) GetTimingInfo(device *path.Device, capture *path.Capture, flags TimingFlags, l log.Logger) (res *path.TimingInfo, err error) {
	var val interface{}
	if val, err = c.Send(&callGetTimingInfo{device: device, capture: capture, flags: flags}); err == nil {
		res = val.(*resultGetTimingInfo).value
	} else {
		log.Errorf(l, "RPC GetTimingInfo failed with error: %v", err)
	}
	return
}

func (c client) Import(name string, Data []uint8, l log.Logger) (res *path.Capture, err error) {
	var val interface{}
	if val, err = c.Send(&callImport{name: name, Data: Data}); err == nil {
		res = val.(*resultImport).value
	} else {
		log.Errorf(l, "RPC Import failed with error: %v", err)
	}
	return
}

func (c client) PrerenderFramebuffers(device *path.Device, capture *path.Capture, api ApiID, width uint32, height uint32, atomIDs []uint64, l log.Logger) (res *path.Blob, err error) {
	var val interface{}
	if val, err = c.Send(&callPrerenderFramebuffers{device: device, capture: capture, api: api, width: width, height: height, atomIDs: atomIDs}); err == nil {
		res = val.(*resultPrerenderFramebuffers).value
	} else {
		log.Errorf(l, "RPC PrerenderFramebuffers failed with error: %v", err)
	}
	return
}

func (c client) Set(p path.Path, v interface{}, l log.Logger) (res path.Path, err error) {
	var val interface{}
	if val, err = c.Send(&callSet{p: p, v: v}); err == nil {
		res = val.(*resultSet).value
	} else {
		log.Errorf(l, "RPC Set failed with error: %v", err)
	}
	return
}
