////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by rpcapi
////////////////////////////////////////////////////////////////////////////////

package service

import "fmt"

func (c callGet) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "Get(p: %v)",
		c.p,
	)
}
func (r resultGet) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetCaptures) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetCaptures()")
}
func (r resultGetCaptures) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetDevices) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetDevices()")
}
func (r resultGetDevices) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetFramebufferColor) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetFramebufferColor(device: %v, after: %v, settings: %v)",
		c.device, c.after, c.settings,
	)
}
func (r resultGetFramebufferColor) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetFramebufferDepth) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetFramebufferDepth(device: %v, after: %v)",
		c.device, c.after,
	)
}
func (r resultGetFramebufferDepth) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetMemoryInfo) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetMemoryInfo(after: %v, rng: %v)",
		c.after, c.rng,
	)
}
func (r resultGetMemoryInfo) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetSchema) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetSchema()")
}
func (r resultGetSchema) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callGetTimingInfo) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "GetTimingInfo(device: %v, capture: %v, flags: %v)",
		c.device, c.capture, c.flags,
	)
}
func (r resultGetTimingInfo) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callImport) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "Import(name: %v, Data: %v)",
		c.name, c.Data,
	)
}
func (r resultImport) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callPrerenderFramebuffers) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "PrerenderFramebuffers(device: %v, capture: %v, api: %v, width: %v, height: %v, atomIds: %v)",
		c.device, c.capture, c.api, c.width, c.height, c.atomIds,
	)
}
func (r resultPrerenderFramebuffers) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveAtomStream) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveAtomStream(id: %v)",
		c.id,
	)
}
func (r resultResolveAtomStream) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveBinary) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveBinary(id: %v)",
		c.id,
	)
}
func (r resultResolveBinary) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveCapture) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveCapture(id: %v)",
		c.id,
	)
}
func (r resultResolveCapture) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveDevice) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveDevice(id: %v)",
		c.id,
	)
}
func (r resultResolveDevice) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveImageInfo) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveImageInfo(id: %v)",
		c.id,
	)
}
func (r resultResolveImageInfo) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveMemoryInfo) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveMemoryInfo(id: %v)",
		c.id,
	)
}
func (r resultResolveMemoryInfo) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callResolveTimingInfo) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "ResolveTimingInfo(id: %v)",
		c.id,
	)
}
func (r resultResolveTimingInfo) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
func (c callSet) Format(f fmt.State, r rune) {
	fmt.Fprintf(f, "Set(p: %v, v: %v)",
		c.p, c.v,
	)
}
func (r resultSet) Format(f fmt.State, c rune) {
	fmt.Fprintf(f, "res: %#v", r.value)
}
