////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package service

import (
	"fmt"

	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/database"
	"android.googlesource.com/platform/tools/gpu/log"
	"android.googlesource.com/platform/tools/gpu/service/path"
)

// ResolveCapture resolves a binary.ID and then safely casts the result to a *Capture.
func ResolveCapture(id binary.ID, d database.Database, l log.Logger) (*Capture, error) {
	if v, err := database.Resolve(id, d, l); err != nil {
		return nil, err
	} else if r, ok := v.(*Capture); !ok {
		return nil, fmt.Errorf("ID %s gave %T, expected Capture", id, v)
	} else {
		return r, nil
	}
}

// GetCapture calls s.Get with p and then safely casts the result to a *Capture.
func GetCapture(p *path.Capture, s RPC, l log.Logger) (*Capture, error) {
	if v, err := s.Get(p, l); err != nil {
		return nil, err
	} else if r, ok := v.(*Capture); !ok {
		return nil, fmt.Errorf("path %s gave %T, expected Capture", p, v)
	} else {
		return r, nil
	}
}

// ResolveDevice resolves a binary.ID and then safely casts the result to a *Device.
func ResolveDevice(id binary.ID, d database.Database, l log.Logger) (*Device, error) {
	if v, err := database.Resolve(id, d, l); err != nil {
		return nil, err
	} else if r, ok := v.(*Device); !ok {
		return nil, fmt.Errorf("ID %s gave %T, expected Device", id, v)
	} else {
		return r, nil
	}
}

// GetDevice calls s.Get with p and then safely casts the result to a *Device.
func GetDevice(p *path.Device, s RPC, l log.Logger) (*Device, error) {
	if v, err := s.Get(p, l); err != nil {
		return nil, err
	} else if r, ok := v.(*Device); !ok {
		return nil, fmt.Errorf("path %s gave %T, expected Device", p, v)
	} else {
		return r, nil
	}
}

// ResolveImageInfo resolves a binary.ID and then safely casts the result to a *ImageInfo.
func ResolveImageInfo(id binary.ID, d database.Database, l log.Logger) (*ImageInfo, error) {
	if v, err := database.Resolve(id, d, l); err != nil {
		return nil, err
	} else if r, ok := v.(*ImageInfo); !ok {
		return nil, fmt.Errorf("ID %s gave %T, expected ImageInfo", id, v)
	} else {
		return r, nil
	}
}

// GetImageInfo calls s.Get with p and then safely casts the result to a *ImageInfo.
func GetImageInfo(p *path.ImageInfo, s RPC, l log.Logger) (*ImageInfo, error) {
	if v, err := s.Get(p, l); err != nil {
		return nil, err
	} else if r, ok := v.(*ImageInfo); !ok {
		return nil, fmt.Errorf("path %s gave %T, expected ImageInfo", p, v)
	} else {
		return r, nil
	}
}

// ResolveMemoryInfo resolves a binary.ID and then safely casts the result to a *MemoryInfo.
func ResolveMemoryInfo(id binary.ID, d database.Database, l log.Logger) (*MemoryInfo, error) {
	if v, err := database.Resolve(id, d, l); err != nil {
		return nil, err
	} else if r, ok := v.(*MemoryInfo); !ok {
		return nil, fmt.Errorf("ID %s gave %T, expected MemoryInfo", id, v)
	} else {
		return r, nil
	}
}

// GetMemoryInfo calls s.Get with p and then safely casts the result to a *MemoryInfo.
func GetMemoryInfo(p *path.MemoryInfo, s RPC, l log.Logger) (*MemoryInfo, error) {
	if v, err := s.Get(p, l); err != nil {
		return nil, err
	} else if r, ok := v.(*MemoryInfo); !ok {
		return nil, fmt.Errorf("path %s gave %T, expected MemoryInfo", p, v)
	} else {
		return r, nil
	}
}

// ResolveTimingInfo resolves a binary.ID and then safely casts the result to a *TimingInfo.
func ResolveTimingInfo(id binary.ID, d database.Database, l log.Logger) (*TimingInfo, error) {
	if v, err := database.Resolve(id, d, l); err != nil {
		return nil, err
	} else if r, ok := v.(*TimingInfo); !ok {
		return nil, fmt.Errorf("ID %s gave %T, expected TimingInfo", id, v)
	} else {
		return r, nil
	}
}

// GetTimingInfo calls s.Get with p and then safely casts the result to a *TimingInfo.
func GetTimingInfo(p *path.TimingInfo, s RPC, l log.Logger) (*TimingInfo, error) {
	if v, err := s.Get(p, l); err != nil {
		return nil, err
	} else if r, ok := v.(*TimingInfo); !ok {
		return nil, fmt.Errorf("path %s gave %T, expected TimingInfo", p, v)
	} else {
		return r, nil
	}
}
