import org.apache.tools.ant.taskdefs.condition.Os

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:0.+'
  }
}

def goPath = System.getenv('GOPATH')
def temporaryDirectory = file(goPath+'/pkg/build').absolutePath
def outputDirectory = file(goPath+'/bin')

buildDir temporaryDirectory

defaultTasks 'ndkBuild'

task ndkBuild(type: Exec) {
  def cmd = 'ndk-build' + (osFamily() == 'windows' ? '.cmd' : '')
  commandLine cmd, '-C', file('android').absolutePath, 'NDK_OUT='+temporaryDirectory+'/obj',
              'NDK_APP_DST_DIR='+temporaryDirectory+'/libs/$(TARGET_ARCH_ABI)', '-s'
}

task ndkClean(type: Exec) {
  def cmd = 'ndk-build' + (osFamily() == 'windows' ? '.cmd' : '')
  commandLine cmd, '-C', file('android').absolutePath, 'NDK_OUT='+temporaryDirectory+'/obj',
              'NDK_APP_DST_DIR='+temporaryDirectory+'/libs/$(TARGET_ARCH_ABI)', '-s', 'clean'
}

task clean (dependsOn: ndkClean) << {}

def osFamily() {
  if (Os.isFamily(Os.FAMILY_MAC)) return 'mac'
  if (Os.isFamily(Os.FAMILY_UNIX)) return 'linux'
  if (Os.isFamily(Os.FAMILY_WINDOWS)) return 'windows'
  return null
}
