// Copyright (C) 2015 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cc

import (
	"flag"
	"strings"

	"os"

	"android.googlesource.com/platform/tools/gpu/client/gapii"
	"android.googlesource.com/platform/tools/gpu/log"
	"android.googlesource.com/platform/tools/gpu/maker/build"
	"android.googlesource.com/platform/tools/gpu/maker/config"
	"android.googlesource.com/platform/tools/gpu/maker/cpp"
	"android.googlesource.com/platform/tools/gpu/maker/cpp/gcc"
	"android.googlesource.com/platform/tools/gpu/maker/cpp/msvc"
	"android.googlesource.com/platform/tools/gpu/maker/cpp/ndk"
)

var (
	keystore   = flag.String("keystore", GPURoot.Join("maker", "keystore", "debug.keystore").Absolute(), "The keystore used to sign APKs")
	storepass  = flag.String("storepass", "android", "The password to the keystore")
	keypass    = flag.String("keypass", "android", "The password to the keystore's key")
	keyalias   = flag.String("alias", "androiddebugkey", "The alias of the key used to sign APKs")
	logfile    = flag.String("logfile", "", "Writes logging to a file instead of stdout")
	forcebuild = flag.Bool("f", false, "All build steps will be forced")
	debug      = flag.Bool("d", false, "Generate debug binaries")
)

var (
	ExternalRoot = build.RepoRoot.Path.Join("external")
	GPURoot      = build.RepoRoot.Path.Join("tools", "gpu", "src", "android.googlesource.com", "platform", "tools", "gpu")
	BinRoot      = build.RepoRoot.Path.Join("tools", "gpu", "bin")
	CCRoot       = GPURoot.Join("cc")
	GapicRoot    = CCRoot.Join("gapic")
	GapiiRoot    = CCRoot.Join("gapii")
	GapirRoot    = CCRoot.Join("gapir")
	ReplaydRoot  = CCRoot.Join("replayd")
	GmockRoot    = ExternalRoot.Join("gmock")
	GtestRoot    = ExternalRoot.Join("gtest")
)

func getEnvironment(logger log.Logger, verbose int) build.Environment {
	return build.Environment{
		Intermediates: build.RepoRoot.Path.Join("tools", "gpu", "pkg"),
		Roots: build.RootList{
			build.Root{Name: "external", Path: ExternalRoot},
			build.Root{Name: "gpu", Path: GPURoot},
		},
		Keystore:   build.File(*keystore),
		Storepass:  *storepass,
		Keypass:    *keypass,
		Keyalias:   *keyalias,
		Logger:     logger,
		ForceBuild: *forcebuild,
		Verbose:    verbose,
	}
}

func getLogger() log.Logger {
	if len(*logfile) > 0 {
		logger, err := log.File(*logfile)
		if err != nil {
			panic(err)
		}
		return logger
	} else {
		return log.Std()
	}
}

type Target struct {
	Name        string
	SourceFiles []string
	Gtest       cpp.Config
	Gmock       cpp.Config
	Gapic       cpp.Config
	GapicTests  cpp.Config
	Gapii       cpp.Config
	Gapir       cpp.Config
	GapirTests  cpp.Config
	Spy         cpp.Config
	Replayd     cpp.Config
}

func (t Target) Extend(n Target) Target {
	return Target{
		SourceFiles: append(append([]string{}, t.SourceFiles...), n.SourceFiles...),
		Gtest:       t.Gtest.Extend(n.Gtest),
		Gmock:       t.Gmock.Extend(n.Gmock),
		Gapic:       t.Gapic.Extend(n.Gapic),
		GapicTests:  t.GapicTests.Extend(n.GapicTests),
		Gapii:       t.Gapii.Extend(n.Gapii),
		Gapir:       t.Gapir.Extend(n.Gapir),
		GapirTests:  t.GapirTests.Extend(n.GapirTests),
		Spy:         t.Spy.Extend(n.Spy),
		Replayd:     t.Replayd.Extend(n.Replayd),
	}
}

func (t Target) Build(env build.Environment) {
	env.Logger = log.Enter(log.Fork(env.Logger), t.Name)
	// Build gtest into a library
	gtestSource := GtestRoot.Join("src").Glob("gtest-all.cc", "gtest_main.cc")
	gtestLib := cpp.MakeStaticLibrary(gtestSource, t.Gtest, env, true)

	// Build gmock into a library
	gmockSource := GmockRoot.Join("src").Glob("gmock-all.cc")
	gmockLib := cpp.MakeStaticLibrary(gmockSource, t.Gmock, env, true)

	generated := build.FileSet{
		// Generated by Codergen
		GapicRoot.Join("coder/atom.cpp"),
		GapicRoot.Join("coder/gles.cpp"),
		GapicRoot.Join("coder/memory.cpp")}

	// Gather the source files for gapic
	gapicSource := GapicRoot.Glob(t.SourceFiles...).
		Append(GapicRoot.Join(t.Gapic.ABI.OS.Name).Glob(t.SourceFiles...)...).
		Exclude("*_test.cpp").Append(generated...)

	// Build the gapic static library.
	gapicLib := cpp.MakeStaticLibrary(gapicSource, t.Gapic, env, true)

	// Gather the source files for gapii
	gapiiSource := GapiiRoot.Glob(t.SourceFiles...).
		Append(GapiiRoot.Join(t.Gapii.ABI.OS.Name).Glob(t.SourceFiles...)...).
		Exclude("*_test.cpp").
		Exclude("link_interceptor.cpp"). // only need in the .so
		// Generated by APIC
		Append(GapiiRoot.Join("gles_imports.cpp")).
		Append(GapiiRoot.Join("gles_exports.cpp")).
		Append(gapicSource...)

	// Build the gapii static library.
	gapiiLib := cpp.MakeStaticLibrary(gapiiSource, t.Gapii, env, false)
	_ = gapiiLib

	// Gather the source files for gapir
	gapirSource := GapirRoot.Glob(t.SourceFiles...).
		Append(GapirRoot.Join(t.Gapir.ABI.OS.Name).Glob(t.SourceFiles...)...).
		Exclude("*_test.cpp").
		// Generated by APIC
		Append(GapirRoot.Join("gfx_api.cpp"))

	// Build the gapir static library.
	gapirLib := cpp.MakeStaticLibrary(gapirSource, t.Gapir, env, true)

	// Build the spy from the gapii static library.
	// TODO: using the static-lib strips symbol visibility from the
	// dynamic-library.
	// Investigate linker flags to use build.Files(gapiiLib)
	gapisSo := cpp.MakeDynamicLibrary("spy", gapiiSource, t.Spy, env)

	if t.Replayd.ABI.OS == config.Android {
		// Copy: bin/android-<abi>/<debug/release>/<gapis> -> bin/android-<abi>/<gapis>
		cpp.MakeCopy(gapisSo, t.Spy.OutputDir.Join("..", gapisSo.Name()), t.Spy, env)
	}

	// Build gapir from the gapir static library and Main.cpp.
	replaydSource := build.Files(ReplaydRoot.Join("main.cpp"))
	replaydInputs := replaydSource.Append(gapirLib, gapicLib)
	replayd := cpp.MakeExecutable("gapir", replaydInputs, t.Replayd, env)

	// Build tests.
	gapicTestSource := GapicRoot.Glob(t.SourceFiles...).
		Append(GapicRoot.Join(t.Gapic.ABI.OS.Name).Glob(t.SourceFiles...)...).
		Filter("*_test.cpp")
	gapicTestInputs := gapicTestSource.Append(gtestLib, gmockLib, gapicLib)
	gapicTest := cpp.MakeExecutable("gapic-tests", gapicTestInputs, t.GapicTests, env)

	gapirTestSource := GapirRoot.Glob(t.SourceFiles...).
		Append(GapirRoot.Join(t.Gapir.ABI.OS.Name).Glob(t.SourceFiles...)...).
		Filter("*_test.cpp")
	gapirTestInputs := gapirTestSource.Append(gtestLib, gmockLib, gapirLib, gapicLib)
	gapirTest := cpp.MakeExecutable("gapir-tests", gapirTestInputs, t.GapirTests, env)

	if t.Replayd.ABI.OS == config.HostOS {
		cpp.MakeRunTest(gapicTest, t.GapicTests)

		cpp.MakeRunTest(gapirTest, t.GapirTests)

		src, dst := replayd, BinRoot.Join(replayd.Name())
		cpp.MakeCopy(src, dst, t.Replayd, env)
	}
}

func base(toolchain *cpp.Toolchain, abi *config.ABI) Target {
	base := cpp.Config{
		Toolchain: toolchain,
		ABI:       abi,
		Defines: map[string]string{
			"TARGET_OS_" + strings.ToUpper(abi.OS.Name): "1",
		},
	}

	if *debug {
		base.Flavor = "debug"
		base.OptimizationLevel = cpp.NoOptimization
		base.Defines["LOG_LEVEL"] = "3" // LOG_LEVEL_DEBUG
	} else {
		base.Flavor = "release"
		base.OptimizationLevel = cpp.FullOptimization
	}

	if toolchain == gcc.GCC {
		base.LibrarySearchPaths = build.Files("/usr/local/lib")
	}

	if toolchain != msvc.MSVC {
		base.Libraries = build.Files("stdc++")
		base.CompilerArgs = []string{"-std=c++11"}
	} else {
		base.Flavor += "-msvc"
	}

	base.OutputDir = BinRoot.Join(abi.OS.Name+"-"+abi.Architecture.Name, base.Flavor)

	return Target{
		Name:        abi.Name,
		SourceFiles: []string{"*.cpp", "*.cc"},
		Gtest: base.Extend(cpp.Config{
			Name: "gtest",
			IncludeSearchPaths: build.FileSet{
				GtestRoot,
				GtestRoot.Join("include"),
			},
		}),
		Gmock: base.Extend(cpp.Config{
			Name: "gmock",
			IncludeSearchPaths: build.FileSet{
				GmockRoot,
				GmockRoot.Join("include"),
				GtestRoot,
				GtestRoot.Join("include"),
			},
		}),
		Gapic: base.Extend(cpp.Config{
			Name:               "gapic",
			IncludeSearchPaths: build.FileSet{CCRoot},
		}),
		GapicTests: base.Extend(cpp.Config{
			Name: "gapic-tests",
			IncludeSearchPaths: build.FileSet{
				CCRoot,
				GmockRoot.Join("include"),
				GtestRoot.Join("include"),
			},
		}),
		Gapii: base.Extend(cpp.Config{
			Name:               "gapii",
			IncludeSearchPaths: build.FileSet{CCRoot},
		}),
		Gapir: base.Extend(cpp.Config{
			Name:               "gapir",
			IncludeSearchPaths: build.FileSet{CCRoot},
		}),
		GapirTests: base.Extend(cpp.Config{
			Name: "gapir-tests",
			IncludeSearchPaths: build.FileSet{
				CCRoot,
				GmockRoot.Join("include"),
				GtestRoot.Join("include"),
			},
		}),
		Spy: base.Extend(cpp.Config{
			Name:               "gapii",
			IncludeSearchPaths: build.FileSet{CCRoot},
		}),
		Replayd: base.Extend(cpp.Config{
			Name: "gapir",
			IncludeSearchPaths: build.FileSet{
				CCRoot,
			},
			Permissions: []string{
				"android.permission.INTERNET",
				"android.permission.READ_EXTERNAL_STORAGE",
				"android.permission.WRITE_EXTERNAL_STORAGE",
			},
		}),
	}
}

// Generate "maker" graph for building the cpp code.
func Graph() {
	// Note this logger is captured in the build graph. There is no good place
	// to call logger.Close()
	logger := getLogger()
	env := getEnvironment(logger, config.Verbose)

	noext := ""

	switch config.TargetOS {
	case config.Linux:
		base(gcc.GCC, config.GetABI(config.Linux, config.X86_64)).Extend(Target{
			GapicTests: cpp.Config{
				Libraries: build.FileSet{"pthread"},
			},
			GapirTests: cpp.Config{
				Libraries: build.FileSet{"dl", "GL", "m", "pthread", "X11", "rt"},
			},
			Replayd: cpp.Config{
				Libraries: build.FileSet{"dl", "GL", "m", "pthread", "X11", "rt"},
			},
			Spy: cpp.Config{
				Libraries: build.FileSet{"pthread"},
			},
		}).Build(env)

	case config.OSX:
		osx := base(gcc.GCC, config.GetABI(config.OSX, config.X86_64)).Extend(Target{
			SourceFiles: []string{"*.mm"},
			Gapii: cpp.Config{
				AdditionalSources: build.FileSet{
					GapiiRoot.Join("osx", "opengl_framework_exports.cpp")}},
			Spy: cpp.Config{
				Name:      "OpenGL",
				OutputExt: &noext,
			},
			GapirTests: cpp.Config{
				LinkerArgs: []string{
					"-framework", "Cocoa",
					"-framework", "OpenGL",
				},
				Libraries: build.FileSet{"pthread"},
			},
			Replayd: cpp.Config{
				LinkerArgs: []string{
					"-framework", "Cocoa",
					"-framework", "OpenGL",
				},
				Libraries: build.FileSet{"pthread"},
			},
		})
		osx.Spy.OutputDir = osx.Spy.OutputDir.Join("OpenGL.framework", "Versions", "A")
		osx.Build(env)

	case config.Windows:
		base(gcc.GCC, config.GetABI(config.Windows, config.X86_64)).Extend(Target{
			Gapii: cpp.Config{
				AdditionalSources: build.FileSet{
					GapiiRoot.Join("windows", "opengl32_resolve.cpp")}},
			Spy: cpp.Config{
				Libraries: build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
			},
			GapirTests: cpp.Config{
				Libraries: build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
			},
			Replayd: cpp.Config{
				Libraries: build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
			},
		}).Build(env)
		if config.HostOS == config.Windows {
			base(msvc.MSVC, config.GetABI(config.Windows, config.X86_64)).Extend(Target{
				Gapii: cpp.Config{
					AdditionalSources: build.FileSet{
						GapiiRoot.Join("windows", "opengl32_resolve.cpp")}},
				Spy: cpp.Config{
					Name:              "opengl32",
					AdditionalSources: build.FileSet{GapiiRoot.Join("windows", "opengl32_x64.asm")},
					ModuleDefinition:  GapiiRoot.Join("windows", "opengl32_exports.def"),
					Libraries:         build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
				},
				GapirTests: cpp.Config{
					Libraries: build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
				},
				Replayd: cpp.Config{
					Libraries: build.FileSet{"ws2_32", "opengl32", "gdi32", "user32"},
				},
			}).Build(env)
		}
	}
	if os.Getenv("ANDROID_NDK_ROOT") != "" {
		// A bit of the Android crazy linker from the NDK. This is used to
		// relink the program to use spy interceptors on non-rooted devices.
		crazy := CCRoot.Join("ndk", "crazy_linker", "src")
		crazy_source := build.FileSet{
			crazy.Join("crazy_linker_elf_symbols.cpp"),
			crazy.Join("crazy_linker_elf_view.cpp"),
			crazy.Join("crazy_linker_error.cpp"),
			crazy.Join("linker_phdr.cpp"),
		}

		app_glue := CCRoot.Join("ndk", "native_app_glue")

		android_target := Target{
			GapicTests: cpp.Config{
				Toolchain: ndk.EXE,
				Libraries: build.FileSet{"log", "android", "z", "m"},
			},
			GapirTests: cpp.Config{
				Toolchain: ndk.EXE,
				Libraries: build.FileSet{"EGL", "log", "android", "z", "m"},
			},
			Replayd: cpp.Config{
				Libraries:          build.FileSet{"EGL", "log", "android", "z", "m"},
				IncludeSearchPaths: build.FileSet{app_glue.Join()},
				AdditionalSources:  build.FileSet{app_glue.Join("android_native_app_glue.c")},
			},
			Gapii: cpp.Config{
				Defines: map[string]string{
					"GAPII_SO_NAME": `"` + gapii.SoInstallName + `"`,
				},
			},
			Spy: cpp.Config{
				Libraries:          build.FileSet{"log", "z", "m", "dl"},
				IncludeSearchPaths: build.FileSet{crazy},
				AdditionalSources: crazy_source.Append(
					GapiiRoot.Join("android", "link_interceptor.cpp")),
			},
		}
		base(ndk.APK, config.GetABI(config.Android, config.Arm)).Extend(android_target).Build(env)
		base(ndk.APK, config.GetABI(config.Android, config.Arm64)).Extend(android_target).Build(env)
	}
}
