////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by embed
////////////////////////////////////////////////////////////////////////////////

package generate

var embedded = map[string]string{
	cpp_tmpl_file:  cpp_tmpl,
	go_tmpl_file:   go_tmpl,
	java_tmpl_file: java_tmpl,
}

const cpp_tmpl_file = `cpp.tmpl`
const cpp_tmpl = `// Copyright (C) 2014 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


{{define "Cpp.Type#bool"}}bool{{end}}
{{define "Cpp.Type#int8"}}int8_t{{end}}
{{define "Cpp.Type#uint8"}}uint8_t{{end}}
{{define "Cpp.Type#int16"}}int16_t{{end}}
{{define "Cpp.Type#uint16"}}uint16_t{{end}}
{{define "Cpp.Type#int32"}}int32_t{{end}}
{{define "Cpp.Type#uint32"}}uint32_t{{end}}
{{define "Cpp.Type#int64"}}int64_t{{end}}
{{define "Cpp.Type#uint64"}}uint64_t{{end}}
{{define "Cpp.Type#float32"}}float{{end}}
{{define "Cpp.Type#float64"}}double{{end}}
{{define "Cpp.Type#string"}}char*{{end}}
{{define "Cpp.Type#binary.ID"}}gapic::Id{{end}}
{{define "Cpp.Type.Struct"}}{{.Name | CppName}}{{end}}
{{define "Cpp.Type.Interface"}}gapic::Encodable*{{end}}
{{define "Cpp.Type.Pointer"}}{{Call "Cpp.Type" .Type}}*{{end}}
{{define "Cpp.Type.Array"}}{{Call "Cpp.Type" .ValueType}}*{{end}}
{{define "Cpp.Type.Slice"}}Array<{{Call "Cpp.Type" .ValueType}}>{{end}}
{{define "Cpp.Type.Stream"}}Array<{{Call "Cpp.Type" .ValueType}}>{{end}}
{{define "Cpp.Type.Map"}}std::unordered_map<{{Call "Cpp.Type" .KeyType}},{{Call "Cpp.Type" .ValueType}}>*{{end}}

{{define "Cpp.Method#ID"}}Id{{end}}
{{define "Cpp.Method"}}{{.}}{{end}}

{{define "Cpp.Constructor"}}»»{{.Name | CppName}}() = default;
»»{{.Name | CppName}}({{range $index, $field := .Fields}}{{if $index}}, {{end}}{{Call "Cpp.Type" $field.Type}} {{$field.Name}}{{end}}) {{range $index, $field := .Fields}}{{if $index}},{{else}}:{{end}}
»»»m{{.Name}}({{.Name}}){{end}} {}{{end}}

{{define "Cpp.ID"}}»»virtual const gapic::Id& Id() const {
»»»static gapic::Id ID{ { {{range .ID}}{{printf "0x%2.2x" .}}, {{end}} } };
»»»return ID;
»»}{{end}}

{{define "Cpp.Encoder"}}»»virtual void Encode(Encoder* e) const {
{{range .Fields}}»»»{{Call "Cpp.Encode" (Var .Type "this->m" .Name)}}
{{end}}»»}{{end}}

{{define "Cpp.Encode.Primitive"}}e->{{Call "Cpp.Method" .Type.Method}}({{.Name}});{{end}}
{{define "Cpp.Encode.Struct"}}e->Value({{.Name}});{{end}}
{{define "Cpp.Encode.Pointer"}}e->Object({{.Name}});{{end}}
{{define "Cpp.Encode.Interface"}}e->Object({{.Name}});{{end}}

{{define "Cpp.Encode#[]uint8"}}e->Uint32({{.Name}}.size());
»»»e->Data({{.Name}}.data(), {{.Name}}.size());{{end}}

{{define "Cpp.Encode.Slice"}}e->Uint32({{.Name}}.size());
»»»for (int i = 0; i < {{.Name}}.size(); i++) {
»»»»{{Call "Cpp.Encode" (Var .Type.ValueType .Name "[i]")}}
»»»}{{end}}

{{define "Cpp.Encode.Array"}}
»»»for (int i = 0; i < {{.Type.Size}}; i++) {
»»»»{{Call "Cpp.Encode" (Var .Type.ValueType .Name "[i]")}}
»»»}{{end}}

{{define "Cpp.Encode.Stream"}}GAPID_FATAL("C++ stream encoding not supported");{{end}}

{{define "Cpp.Encode.Map"}}GAPID_FATAL("C++ stream encoding not supported");{{end}}

{{define "Cpp.File"}}{{$.Copyright}}
#ifndef GAPIC_CODER_{{.Package | Upper}}_H
#define GAPIC_CODER_{{.Package | Upper}}_H

namespace gapic {

class Encodable;
class Encoder;

namespace coder {
namespace {{.Package}} {
{{range .Structs}}»class {{.Name | CppName}}: public Encodable {
»public:
{{template "Cpp.Constructor" .}}
{{template "Cpp.ID" .}}
{{template "Cpp.Encoder" .}}

{{range .Fields}}»»{{Call "Cpp.Type" .Type}} m{{.Name}};
{{end}}»};

{{end}}

} // namespace {{.Package}}
} // namespace coder
} // namespace gapic

#endif // GAPIC_CODER_{{.Package | Upper}}_H
{{end}}
`
const go_tmpl_file = `go.tmpl`
const go_tmpl = `{{/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */}}

{{define "Go.ID"}} {{.IDName}} = binary.ID{ {{range .ID}}{{printf "0x%2.2x" .}}, {{end}} } {{end}}

{{define "Go.Init"}} Namespace.Add((*{{.Name}})(nil).Class()){{end}}

{{define "Go.Class"}} type binaryClass{{.Name}} struct{}
func (*{{.Name}}) Class() binary.Class {
	return (*binaryClass{{.Name}})(nil)
}
func doEncode{{.Name}}(e binary.Encoder, o *{{.Name}}) error {
	{{range .Fields}}{{Call "Go.Encode" (Var .Type "o." .Name)}}
{{end}} return nil
}
func doDecode{{.Name}}(d binary.Decoder, o *{{.Name}}) error {
	{{range .Fields}}{{Call "Go.Decode" (Var .Type "o." .Name)}}
{{end}} return nil
}
func doSkip{{.Name}}(d binary.Decoder) error {
	{{range .Fields}}{{Call "Go.Skip" .Type}}
{{end}} return nil
}
func (*binaryClass{{.Name}}) ID() binary.ID { return {{.IDName}} }
func (*binaryClass{{.Name}}) New() binary.Object { return &{{.Name}}{} }
func (*binaryClass{{.Name}}) Encode(e binary.Encoder, obj binary.Object) error {return doEncode{{.Name}}(e, obj.(*{{.Name}})) }
func (*binaryClass{{.Name}}) Decode(d binary.Decoder) (binary.Object, error) {obj := &{{.Name}}{}; return obj, doDecode{{.Name}}(d, obj) }
func (*binaryClass{{.Name}}) DecodeTo(d binary.Decoder, obj binary.Object) error {return doDecode{{.Name}}(d, obj.(*{{.Name}})) }
func (*binaryClass{{.Name}}) Skip(d binary.Decoder) error {return doSkip{{.Name}}(d) }
{{if Directive "Schema" true}}func (*binaryClass{{.Name}}) Schema() *schema.Class { return schema{{.Name}} }
var schema{{.Name}} = &schema.Class{
	TypeID: {{.IDName}},
	Package: "{{.Package}}",
	Name: "{{.Name}}",
	Fields: []schema.Field{
		{{range .Fields}}{ Declared:"{{.Declared}}", Type:{{Call "Go.Schema" .Type}} },
	{{end}} },
}
{{end}}{{end}}

{{define "Go.Encode.Primitive"}}{{/*
*/}}{{if eq .Type.Native .Type.Name}}{{/*
*/}}if err := e.{{.Type.Method}}({{.Name}}); err != nil { return err } {{/*
*/}}{{else}}{{/*
*/}}if err := e.{{.Type.Method}}({{.Type.Native}}({{.Name}})); err != nil { return err } {{/*
*/}}{{end}}{{end}}

{{define "Go.Encode.Struct"}} if err := e.Value(&{{.Name}}); err != nil { return err } {{end}}

{{define "Go.Encode.Pointer"}} if {{.Name}} != nil {
			if err := e.Object({{.Name}}); err != nil {
				return err
			}
		} else if err := e.Object(nil); err != nil {
			return err
		} {{end}}

{{define "Go.Encode.Interface"}} if {{.Name}} != nil {
			if err := e.Object({{.Name}}); err != nil {
				return err
			}
		} else if err := e.Object(nil); err != nil {
			return err
		} {{end}}

{{define "Go.Encode.Any"}} if {{.Name}} != nil {
			var boxed binary.Object
			boxed, err := any.Box({{.Name}})
			if err != nil {
				return err
			}
			if err := e.Variant(boxed); err != nil {
				return err
			}
		} else if err := e.Variant(nil); err != nil {
			return err
		} {{end}}

{{define "Go.Encode_Length"}} if err := e.Uint32(uint32(len({{.Name}}))); err != nil {
	return err
} {{end}}

{{define "Go.Encode#[]uint8"}} {{template "Go.Encode_Length" $}}
		if err := e.Data({{.Name}}); err != nil {
			return err
		} {{end}}

{{define "Go.Encode.Slice"}} {{template "Go.Encode_Length" $}}
		for i := range {{.Name}} {
			{{Call "Go.Encode" (Var .Type.ValueType .Name "[i]")}}
		}{{end}}

{{define "Go.Encode.Array"}} for i := range {{.Name}} {
			{{Call "Go.Encode" (Var .Type.ValueType .Name "[i]")}}
		}{{end}}

{{define "Go.Encode.Stream"}}for _, o := range {{.Name}} {
			if err := e.Object(o); err != nil {
				return err
			}
		}
		if err := e.Object((*objects.Terminator)(nil)); err != nil {
			return err
		}{{end}}

{{define "Go.Encode.Map"}} {{template "Go.Encode_Length" $}}
		for k, v := range {{.Name}} {
			{{Call "Go.Encode" (Var .Type.KeyType "k")}}
			{{Call "Go.Encode" (Var .Type.ValueType "v")}}
		} {{end}}

{{define "Go.Decode.Primitive"}} if obj, err := d.{{.Type.Method}}(); err != nil {
			return err
		} else {
			{{.Name}} = {{.Type.Name}}(obj)
		} {{end}}

{{define "Go.Decode.Struct"}} if err := d.Value(&{{.Name}}); err != nil { return err } {{end}}

{{define "Go.Decode.Pointer"}} if obj, err := d.Object(); err != nil {
			return err
		} else if obj != nil {
			{{.Name}} = obj.({{.Type}})
		} else {
			{{.Name}} = nil
		} {{end}}

{{define "Go.Decode.Interface"}} if obj, err := d.Object(); err != nil {
			return err
		} else if obj != nil {
			{{.Name}} = obj.({{.Type.Name}})
		} else {
			{{.Name}} = nil
		} {{end}}

{{define "Go.Decode.Any"}} if boxed, err := d.Variant(); err != nil {
			return err
		} else if boxed != nil {
			if {{.Name}}, err = any.Unbox(boxed); err != nil {
				return err
			}
		} else {
			{{.Name}} = nil
		} {{end}}

{{define "Go.Decode_Length"}} if count, err := d.Uint32(); err != nil {
			return err
		} else {
			{{.Name}} = make({{.Type}}, count) {{end}}

{{define "Go.Decode#[]uint8"}} {{template "Go.Decode_Length" $}}
			if err := d.Data({{.Name}}); err != nil {
				return err
			}
		} {{end}}

{{define "Go.Decode.Slice"}} {{template "Go.Decode_Length" $}}
			for i := range {{.Name}} {
				{{Call "Go.Decode" (Var .Type.ValueType .Name "[i]")}}
			}
		} {{end}}

{{define "Go.Decode.Array"}} for i := range {{.Name}} {
				{{Call "Go.Decode" (Var .Type.ValueType .Name "[i]")}}
			}{{end}}

{{define "Go.Decode.Stream"}}for {
			if obj, err := d.Object(); err != nil {
				return err
			} else if _, end := obj.(*objects.Terminator); end {
				break
			} else {
				{{.Name}} = append({{.Name}}, obj.({{.Type.ValueType}}))
			}
		} {{end}}

{{define "Go.Decode.Map"}} if count, err := d.Uint32(); err != nil {
			return err
		} else {
			{{.Name}} = make({{.Type}}, count)
			m := {{.Name}}
			for i := uint32(0); i < count; i++ {
				var k {{.Type.KeyType}}
				var v {{.Type.ValueType}}
				{{Call "Go.Decode" (Var .Type.KeyType "k")}}
				{{Call "Go.Decode" (Var .Type.ValueType "v")}}
				m[k] = v
			}
		} {{end}}

{{define "Go.Skip.Primitive"}}{{if .Method.Skippable}}if err := d.Skip{{.Method}}(); err != nil {
	return err
} {{else}}if _,err := d.{{.Method}}(); err != nil {
		return err
} {{end}} {{end}}
{{define "Go.Skip.Struct"}} if err := d.SkipValue((*{{.Name}})(nil)); err != nil { return err } {{end}}
{{define "Go.Skip.Pointer"}} if _, err := d.SkipObject(); err != nil { return err } {{end}}
{{define "Go.Skip.Interface"}} if _, err := d.SkipObject(); err != nil { return err } {{end}}
{{define "Go.Skip.Any"}} if _, err := d.SkipVariant(); err != nil { return err } {{end}}

{{define "Go.Skip.Slice"}} if count, err := d.Uint32(); err != nil {
			return err
		} else {
			{{$vt := print .ValueType}}{{if or (eq $vt "uint8") (eq $vt "byte")}} if err := d.Skip(count); err != nil { return err} {{else}}{{/*
			*/}} for i := uint32(0); i < count; i++ {
			{{Call "Go.Skip" .ValueType}}
			}{{end}}
		} {{end}}

{{define "Go.Skip.Array"}}for i := uint32(0); i < {{.Size}}; i++ {
			{{Call "Go.Skip" .ValueType}}
		}{{end}}


{{define "Go.Skip.Stream"}}for {
			if id, err := d.SkipObject(); err != nil {
				return err
			} else if id == objects.TerminatorID {
				break
			}
		} {{end}}

{{define "Go.Skip.Map"}} if count, err := d.Uint32(); err != nil {
			return err
		} else {
			for i := uint32(0); i < count; i++ {
				{{Call "Go.Skip" .KeyType}}
				{{Call "Go.Skip" .ValueType}}
			}
		} {{end}}

{{define "Go.Schema.Primitive"}}&schema.Primitive{ Name: "{{.Name}}", Method: schema.{{.Method}} }{{end}}
{{define "Go.Schema.Struct"}}&schema.Struct{Name: "{{.Name}}", ID:(*{{.Name}})(nil).Class().ID()}{{end}}
{{define "Go.Schema.Pointer"}}&schema.Pointer{ Type: {{Call "Go.Schema" .Type}} }{{end}}
{{define "Go.Schema.Interface"}}&schema.Interface{ Name: "{{.Name}}"}{{end}}
{{define "Go.Schema.Any"}}&any.Any{}{{end}}
{{define "Go.Schema.Slice"}}&schema.Slice{Alias: "{{.Alias}}", ValueType: {{Call "Go.Schema" .ValueType}} }{{end}}
{{define "Go.Schema.Array"}}&schema.Array{Alias: "{{.Alias}}", ValueType: {{Call "Go.Schema" .ValueType}}, Size: {{.Size}} }{{end}}
{{define "Go.Schema.Stream"}}&schema.Stream{Alias: "{{.Alias}}", ValueType: {{Call "Go.Schema" .ValueType}} }{{end}}
{{define "Go.Schema.Map"}}&schema.Map{Alias: "{{.Alias}}", KeyType: {{Call "Go.Schema" .KeyType}}, ValueType: {{Call "Go.Schema" .ValueType}} }{{end}}

{{define "Go.Constants"}}{{if Directive (print .Type ".String") true}}{{$name := print .Type}}{{$c := Counter "Go.Constants"}}
const _{{$name}}_name = "{{range .Entries}}{{.Name}}{{end}}"
var _{{$name}}_map = map[{{.Type}}]string{ {{$c.Set 0}}{{range .Entries}}
	{{.Value}}: _{{$name}}_name[{{$c}}:{{$c.AddLen .Name}}{{$c}}],{{end}}
}

func (v {{$name}}) String() string {
	if s, ok := _{{$name}}_map[v]; ok {
		return s
	}
	return fmt.Sprintf("{{$name}}(%d)", v)
}

func (v *{{$name}}) Parse(s string) error {
	for k, t := range _{{$name}}_map {
		if s == t {
			*v = k
			return nil
		}
	}
	return fmt.Errorf("%s not in {{$name}}", s)
}
{{end}}{{end}}

{{define "Go.File"}}
{{$.Copyright}}

package {{.Package}}

import (
	"reflect"
	"android.googlesource.com/platform/tools/gpu/binary/any"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	{{range $imp, $v := .Imports}}"{{$imp}}"
{{end}})

{{if len .Structs}}{{if not .IsTest}}var Namespace = registry.NewNamespace(){{end}}
func init() {
	{{if not .IsTest}}registry.Global.AddFallbacks(Namespace)
	{{end}}{{range .Structs}}{{template "Go.Init" .}}
	{{end}} }

var (
{{range .Structs}} {{template "Go.ID" .}}
{{end}} ){{end}}

{{range .Structs}} {{template "Go.Class" .}}
{{end}}

{{range .Constants}}{{template "Go.Constants" .}}
{{end}}
{{end}}
`
const java_tmpl_file = `java.tmpl`
const java_tmpl = `{{/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */}}

{{define "Java.Enum"}}{{.Name}}Enum{{end}}
{{define "Java.ID"}}{{JavaID .Name}}ID{{end}}
{{define "Java.IDBytes"}}{{JavaID .Name}}IDBytes{{end}}

{{define "Java.Encoder"}}
»public static void encode(Encoder e, {{JavaClass .Name}} o) throws IOException {
{{range .Fields}}»»{{Call "Java.Encode" (Var .Type "o." (JavaFieldName .Name))}}
{{end}}»}{{end}}

{{define "Java.Encode.Primitive"}}e.{{Lower .Type.Method}}({{.Name}});{{end}}
{{define "Java.Encode.Struct"}}{{.Name}}.encode(e);{{end}}
{{define "Java.Encode.Pointer"}}e.object({{.Name}});{{end}}
{{define "Java.Encode.Interface"}}e.object({{.Name}});{{end}}
{{define "Java.Encode.Any"}}// TODO: Java any handling{{end}}

{{define "Java.Encode.Slice"}}e.int32({{.Name}}.length);
»»for (int i = 0; i < {{.Name}}.length; i++) {
»»»{{Call "Java.Encode" (Var .Type.ValueType .Name "[i]")}}
»»}{{end}}

{{define "Java.Encode.Array"}}
»»for (int i = 0; i < {{.Type.Size}}; i++) {
»»»{{Call "Java.Encode" (Var .Type.ValueType .Name "[i]")}}
»»}{{end}}

{{define "Java.Encode.Stream"}}TODO: Java stream handling{{end}}

{{define "Java.Encode.Map"}}TODO: Java map handling{{end}}

{{define "Java.Decoder"}}
»public static void decode(Decoder d, {{JavaClass .Name}} o) throws IOException {
{{range .Fields}}»»{{Call "Java.Decode" (Var .Type "o." (JavaFieldName .Name))}}
{{end}}»}{{end}}

{{define "Java.Decode.Primitive"}}{{.Name}} = d.{{Lower .Type.Method}}();{{end}}
{{define "Java.Decode.Struct"}}{{.Name}} = new {{.Type.Name}}(d);{{end}}
{{define "Java.Decode.Pointer"}}{{.Name}} = ({{JavaStorage .Type}})d.object();{{end}}
{{define "Java.Decode.Interface"}}{{.Name}} = ({{JavaStorage .Type}})d.object();{{end}}
{{define "Java.Decode.Any"}}// TODO: Java any handling{{end}}

{{define "Java.Decode.Slice"}}{{.Name}} = new {{JavaStorage .Type.ValueType}}[d.int32()];
»»for (int i = 0; i < {{.Name}}.length; i++) {
»»»{{Call "Java.Decode" (Var .Type.ValueType .Name "[i]")}}
»»}{{end}}

{{define "Java.Decode.Array"}}{{.Name}} = new {{JavaStorage .Type.ValueType}}[{{.Type.Size}}];
»»for (int i = 0; i < {{.Type.Size}}; i++) {
»»»{{Call "Java.Decode" (Var .Type.ValueType .Name "[i]")}}
»»}{{end}}

{{define "Java.Decode.Map"}}TODO: Java map handling{{end}}
{{define "Java.Decode.Stream"}}TODO: Java stream handling{{end}}

{{define "Java.File"}}{{$.Copyright}}package {{.Package}};

import com.android.tools.rpclib.binary.BinaryObject;
import com.android.tools.rpclib.binary.BinaryObjectCreator;
import com.android.tools.rpclib.binary.Decoder;
import com.android.tools.rpclib.binary.Encoder;
import com.android.tools.rpclib.binary.ObjectTypeID;
import java.io.IOException;

class ObjectFactory {
»public enum Entries implements BinaryObjectCreator {{"{"}}{{range .Structs}}
»»{{template "Java.Enum" .}} {
»»»@Override public BinaryObject create() {
»»»»return new {{JavaClass .Name}}();
»»»}
»»},{{end}}
»}
{{range .Structs}}
»public static byte[] {{template "Java.IDBytes" .}} = { {{range .ID}}{{ToS8 .}}, {{end}}{{"}"}};{{end}}
{{range .Structs}}
»public static ObjectTypeID {{template "Java.ID" .}} = new ObjectTypeID({{template "Java.IDBytes" .}});{{end}}

»static {{"{"}}{{range .Structs}}
»»ObjectTypeID.register({{template "Java.ID" .}}, Entries.{{template "Java.Enum" .}});{{end}}
»}{{range .Structs}}
{{template "Java.Encoder" .}}
{{template "Java.Decoder" .}}{{end}}
}
{{end}}
`
