////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package any

import (
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/binary/schema"
)

var Namespace = registry.NewNamespace()

func init() {
	registry.Global.AddFallbacks(Namespace)
	Namespace.Add((*boolSlice)(nil).Class())
	Namespace.Add((*bool_)(nil).Class())
	Namespace.Add((*float32Slice)(nil).Class())
	Namespace.Add((*float32_)(nil).Class())
	Namespace.Add((*float64Slice)(nil).Class())
	Namespace.Add((*float64_)(nil).Class())
	Namespace.Add((*int16Slice)(nil).Class())
	Namespace.Add((*int16_)(nil).Class())
	Namespace.Add((*int32Slice)(nil).Class())
	Namespace.Add((*int32_)(nil).Class())
	Namespace.Add((*int64Slice)(nil).Class())
	Namespace.Add((*int64_)(nil).Class())
	Namespace.Add((*int8Slice)(nil).Class())
	Namespace.Add((*int8_)(nil).Class())
	Namespace.Add((*intSlice)(nil).Class())
	Namespace.Add((*int_)(nil).Class())
	Namespace.Add((*objectSlice)(nil).Class())
	Namespace.Add((*object_)(nil).Class())
	Namespace.Add((*stringSlice)(nil).Class())
	Namespace.Add((*string_)(nil).Class())
	Namespace.Add((*uint16Slice)(nil).Class())
	Namespace.Add((*uint16_)(nil).Class())
	Namespace.Add((*uint32Slice)(nil).Class())
	Namespace.Add((*uint32_)(nil).Class())
	Namespace.Add((*uint64Slice)(nil).Class())
	Namespace.Add((*uint64_)(nil).Class())
	Namespace.Add((*uint8Slice)(nil).Class())
	Namespace.Add((*uint8_)(nil).Class())
}

type binaryClassboolSlice struct{}

func (*boolSlice) Class() binary.Class {
	return (*binaryClassboolSlice)(nil)
}
func doEncodeboolSlice(e binary.Encoder, o *boolSlice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Bool(o.value[i])
	}
}
func doDecodeboolSlice(d binary.Decoder, o *boolSlice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]bool, count)
		for i := range o.value {
			o.value[i] = bool(d.Bool())
		}
	}
}
func (*binaryClassboolSlice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeboolSlice(e, obj.(*boolSlice))
}
func (*binaryClassboolSlice) Decode(d binary.Decoder) binary.Object {
	obj := &boolSlice{}
	doDecodeboolSlice(d, obj)
	return obj
}
func (*binaryClassboolSlice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeboolSlice(d, obj.(*boolSlice))
}
func (*binaryClassboolSlice) Schema() *binary.Entity { return schemaboolSlice }

var schemaboolSlice = &binary.Entity{
	Package:  "any",
	Identity: "boolSlice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "bool", Method: schema.Bool}}},
	},
}

type binaryClassbool_ struct{}

func (*bool_) Class() binary.Class {
	return (*binaryClassbool_)(nil)
}
func doEncodebool_(e binary.Encoder, o *bool_) {
	e.Bool(o.value)
}
func doDecodebool_(d binary.Decoder, o *bool_) {
	o.value = bool(d.Bool())
}
func (*binaryClassbool_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodebool_(e, obj.(*bool_))
}
func (*binaryClassbool_) Decode(d binary.Decoder) binary.Object {
	obj := &bool_{}
	doDecodebool_(d, obj)
	return obj
}
func (*binaryClassbool_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodebool_(d, obj.(*bool_))
}
func (*binaryClassbool_) Schema() *binary.Entity { return schemabool_ }

var schemabool_ = &binary.Entity{
	Package:  "any",
	Identity: "bool_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "bool", Method: schema.Bool}},
	},
}

type binaryClassfloat32Slice struct{}

func (*float32Slice) Class() binary.Class {
	return (*binaryClassfloat32Slice)(nil)
}
func doEncodefloat32Slice(e binary.Encoder, o *float32Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Float32(o.value[i])
	}
}
func doDecodefloat32Slice(d binary.Decoder, o *float32Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]float32, count)
		for i := range o.value {
			o.value[i] = float32(d.Float32())
		}
	}
}
func (*binaryClassfloat32Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefloat32Slice(e, obj.(*float32Slice))
}
func (*binaryClassfloat32Slice) Decode(d binary.Decoder) binary.Object {
	obj := &float32Slice{}
	doDecodefloat32Slice(d, obj)
	return obj
}
func (*binaryClassfloat32Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefloat32Slice(d, obj.(*float32Slice))
}
func (*binaryClassfloat32Slice) Schema() *binary.Entity { return schemafloat32Slice }

var schemafloat32Slice = &binary.Entity{
	Package:  "any",
	Identity: "float32Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "float32", Method: schema.Float32}}},
	},
}

type binaryClassfloat32_ struct{}

func (*float32_) Class() binary.Class {
	return (*binaryClassfloat32_)(nil)
}
func doEncodefloat32_(e binary.Encoder, o *float32_) {
	e.Float32(o.value)
}
func doDecodefloat32_(d binary.Decoder, o *float32_) {
	o.value = float32(d.Float32())
}
func (*binaryClassfloat32_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefloat32_(e, obj.(*float32_))
}
func (*binaryClassfloat32_) Decode(d binary.Decoder) binary.Object {
	obj := &float32_{}
	doDecodefloat32_(d, obj)
	return obj
}
func (*binaryClassfloat32_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefloat32_(d, obj.(*float32_))
}
func (*binaryClassfloat32_) Schema() *binary.Entity { return schemafloat32_ }

var schemafloat32_ = &binary.Entity{
	Package:  "any",
	Identity: "float32_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "float32", Method: schema.Float32}},
	},
}

type binaryClassfloat64Slice struct{}

func (*float64Slice) Class() binary.Class {
	return (*binaryClassfloat64Slice)(nil)
}
func doEncodefloat64Slice(e binary.Encoder, o *float64Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Float64(o.value[i])
	}
}
func doDecodefloat64Slice(d binary.Decoder, o *float64Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]float64, count)
		for i := range o.value {
			o.value[i] = float64(d.Float64())
		}
	}
}
func (*binaryClassfloat64Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefloat64Slice(e, obj.(*float64Slice))
}
func (*binaryClassfloat64Slice) Decode(d binary.Decoder) binary.Object {
	obj := &float64Slice{}
	doDecodefloat64Slice(d, obj)
	return obj
}
func (*binaryClassfloat64Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefloat64Slice(d, obj.(*float64Slice))
}
func (*binaryClassfloat64Slice) Schema() *binary.Entity { return schemafloat64Slice }

var schemafloat64Slice = &binary.Entity{
	Package:  "any",
	Identity: "float64Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "float64", Method: schema.Float64}}},
	},
}

type binaryClassfloat64_ struct{}

func (*float64_) Class() binary.Class {
	return (*binaryClassfloat64_)(nil)
}
func doEncodefloat64_(e binary.Encoder, o *float64_) {
	e.Float64(o.value)
}
func doDecodefloat64_(d binary.Decoder, o *float64_) {
	o.value = float64(d.Float64())
}
func (*binaryClassfloat64_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefloat64_(e, obj.(*float64_))
}
func (*binaryClassfloat64_) Decode(d binary.Decoder) binary.Object {
	obj := &float64_{}
	doDecodefloat64_(d, obj)
	return obj
}
func (*binaryClassfloat64_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefloat64_(d, obj.(*float64_))
}
func (*binaryClassfloat64_) Schema() *binary.Entity { return schemafloat64_ }

var schemafloat64_ = &binary.Entity{
	Package:  "any",
	Identity: "float64_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "float64", Method: schema.Float64}},
	},
}

type binaryClassint16Slice struct{}

func (*int16Slice) Class() binary.Class {
	return (*binaryClassint16Slice)(nil)
}
func doEncodeint16Slice(e binary.Encoder, o *int16Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Int16(o.value[i])
	}
}
func doDecodeint16Slice(d binary.Decoder, o *int16Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]int16, count)
		for i := range o.value {
			o.value[i] = int16(d.Int16())
		}
	}
}
func (*binaryClassint16Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint16Slice(e, obj.(*int16Slice))
}
func (*binaryClassint16Slice) Decode(d binary.Decoder) binary.Object {
	obj := &int16Slice{}
	doDecodeint16Slice(d, obj)
	return obj
}
func (*binaryClassint16Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint16Slice(d, obj.(*int16Slice))
}
func (*binaryClassint16Slice) Schema() *binary.Entity { return schemaint16Slice }

var schemaint16Slice = &binary.Entity{
	Package:  "any",
	Identity: "int16Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "int16", Method: schema.Int16}}},
	},
}

type binaryClassint16_ struct{}

func (*int16_) Class() binary.Class {
	return (*binaryClassint16_)(nil)
}
func doEncodeint16_(e binary.Encoder, o *int16_) {
	e.Int16(o.value)
}
func doDecodeint16_(d binary.Decoder, o *int16_) {
	o.value = int16(d.Int16())
}
func (*binaryClassint16_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint16_(e, obj.(*int16_))
}
func (*binaryClassint16_) Decode(d binary.Decoder) binary.Object {
	obj := &int16_{}
	doDecodeint16_(d, obj)
	return obj
}
func (*binaryClassint16_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint16_(d, obj.(*int16_))
}
func (*binaryClassint16_) Schema() *binary.Entity { return schemaint16_ }

var schemaint16_ = &binary.Entity{
	Package:  "any",
	Identity: "int16_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "int16", Method: schema.Int16}},
	},
}

type binaryClassint32Slice struct{}

func (*int32Slice) Class() binary.Class {
	return (*binaryClassint32Slice)(nil)
}
func doEncodeint32Slice(e binary.Encoder, o *int32Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Int32(o.value[i])
	}
}
func doDecodeint32Slice(d binary.Decoder, o *int32Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]int32, count)
		for i := range o.value {
			o.value[i] = int32(d.Int32())
		}
	}
}
func (*binaryClassint32Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint32Slice(e, obj.(*int32Slice))
}
func (*binaryClassint32Slice) Decode(d binary.Decoder) binary.Object {
	obj := &int32Slice{}
	doDecodeint32Slice(d, obj)
	return obj
}
func (*binaryClassint32Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint32Slice(d, obj.(*int32Slice))
}
func (*binaryClassint32Slice) Schema() *binary.Entity { return schemaint32Slice }

var schemaint32Slice = &binary.Entity{
	Package:  "any",
	Identity: "int32Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "int32", Method: schema.Int32}}},
	},
}

type binaryClassint32_ struct{}

func (*int32_) Class() binary.Class {
	return (*binaryClassint32_)(nil)
}
func doEncodeint32_(e binary.Encoder, o *int32_) {
	e.Int32(o.value)
}
func doDecodeint32_(d binary.Decoder, o *int32_) {
	o.value = int32(d.Int32())
}
func (*binaryClassint32_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint32_(e, obj.(*int32_))
}
func (*binaryClassint32_) Decode(d binary.Decoder) binary.Object {
	obj := &int32_{}
	doDecodeint32_(d, obj)
	return obj
}
func (*binaryClassint32_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint32_(d, obj.(*int32_))
}
func (*binaryClassint32_) Schema() *binary.Entity { return schemaint32_ }

var schemaint32_ = &binary.Entity{
	Package:  "any",
	Identity: "int32_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "int32", Method: schema.Int32}},
	},
}

type binaryClassint64Slice struct{}

func (*int64Slice) Class() binary.Class {
	return (*binaryClassint64Slice)(nil)
}
func doEncodeint64Slice(e binary.Encoder, o *int64Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Int64(o.value[i])
	}
}
func doDecodeint64Slice(d binary.Decoder, o *int64Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]int64, count)
		for i := range o.value {
			o.value[i] = int64(d.Int64())
		}
	}
}
func (*binaryClassint64Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint64Slice(e, obj.(*int64Slice))
}
func (*binaryClassint64Slice) Decode(d binary.Decoder) binary.Object {
	obj := &int64Slice{}
	doDecodeint64Slice(d, obj)
	return obj
}
func (*binaryClassint64Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint64Slice(d, obj.(*int64Slice))
}
func (*binaryClassint64Slice) Schema() *binary.Entity { return schemaint64Slice }

var schemaint64Slice = &binary.Entity{
	Package:  "any",
	Identity: "int64Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "int64", Method: schema.Int64}}},
	},
}

type binaryClassint64_ struct{}

func (*int64_) Class() binary.Class {
	return (*binaryClassint64_)(nil)
}
func doEncodeint64_(e binary.Encoder, o *int64_) {
	e.Int64(o.value)
}
func doDecodeint64_(d binary.Decoder, o *int64_) {
	o.value = int64(d.Int64())
}
func (*binaryClassint64_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint64_(e, obj.(*int64_))
}
func (*binaryClassint64_) Decode(d binary.Decoder) binary.Object {
	obj := &int64_{}
	doDecodeint64_(d, obj)
	return obj
}
func (*binaryClassint64_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint64_(d, obj.(*int64_))
}
func (*binaryClassint64_) Schema() *binary.Entity { return schemaint64_ }

var schemaint64_ = &binary.Entity{
	Package:  "any",
	Identity: "int64_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "int64", Method: schema.Int64}},
	},
}

type binaryClassint8Slice struct{}

func (*int8Slice) Class() binary.Class {
	return (*binaryClassint8Slice)(nil)
}
func doEncodeint8Slice(e binary.Encoder, o *int8Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Int8(o.value[i])
	}
}
func doDecodeint8Slice(d binary.Decoder, o *int8Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]int8, count)
		for i := range o.value {
			o.value[i] = int8(d.Int8())
		}
	}
}
func (*binaryClassint8Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint8Slice(e, obj.(*int8Slice))
}
func (*binaryClassint8Slice) Decode(d binary.Decoder) binary.Object {
	obj := &int8Slice{}
	doDecodeint8Slice(d, obj)
	return obj
}
func (*binaryClassint8Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint8Slice(d, obj.(*int8Slice))
}
func (*binaryClassint8Slice) Schema() *binary.Entity { return schemaint8Slice }

var schemaint8Slice = &binary.Entity{
	Package:  "any",
	Identity: "int8Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "int8", Method: schema.Int8}}},
	},
}

type binaryClassint8_ struct{}

func (*int8_) Class() binary.Class {
	return (*binaryClassint8_)(nil)
}
func doEncodeint8_(e binary.Encoder, o *int8_) {
	e.Int8(o.value)
}
func doDecodeint8_(d binary.Decoder, o *int8_) {
	o.value = int8(d.Int8())
}
func (*binaryClassint8_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint8_(e, obj.(*int8_))
}
func (*binaryClassint8_) Decode(d binary.Decoder) binary.Object {
	obj := &int8_{}
	doDecodeint8_(d, obj)
	return obj
}
func (*binaryClassint8_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint8_(d, obj.(*int8_))
}
func (*binaryClassint8_) Schema() *binary.Entity { return schemaint8_ }

var schemaint8_ = &binary.Entity{
	Package:  "any",
	Identity: "int8_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "int8", Method: schema.Int8}},
	},
}

type binaryClassintSlice struct{}

func (*intSlice) Class() binary.Class {
	return (*binaryClassintSlice)(nil)
}
func doEncodeintSlice(e binary.Encoder, o *intSlice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Int32(int32(o.value[i]))
	}
}
func doDecodeintSlice(d binary.Decoder, o *intSlice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]int, count)
		for i := range o.value {
			o.value[i] = int(d.Int32())
		}
	}
}
func (*binaryClassintSlice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeintSlice(e, obj.(*intSlice))
}
func (*binaryClassintSlice) Decode(d binary.Decoder) binary.Object {
	obj := &intSlice{}
	doDecodeintSlice(d, obj)
	return obj
}
func (*binaryClassintSlice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeintSlice(d, obj.(*intSlice))
}
func (*binaryClassintSlice) Schema() *binary.Entity { return schemaintSlice }

var schemaintSlice = &binary.Entity{
	Package:  "any",
	Identity: "intSlice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "int", Method: schema.Int32}}},
	},
}

type binaryClassint_ struct{}

func (*int_) Class() binary.Class {
	return (*binaryClassint_)(nil)
}
func doEncodeint_(e binary.Encoder, o *int_) {
	e.Int32(int32(o.value))
}
func doDecodeint_(d binary.Decoder, o *int_) {
	o.value = int(d.Int32())
}
func (*binaryClassint_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeint_(e, obj.(*int_))
}
func (*binaryClassint_) Decode(d binary.Decoder) binary.Object {
	obj := &int_{}
	doDecodeint_(d, obj)
	return obj
}
func (*binaryClassint_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeint_(d, obj.(*int_))
}
func (*binaryClassint_) Schema() *binary.Entity { return schemaint_ }

var schemaint_ = &binary.Entity{
	Package:  "any",
	Identity: "int_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "int", Method: schema.Int32}},
	},
}

type binaryClassobjectSlice struct{}

func (*objectSlice) Class() binary.Class {
	return (*binaryClassobjectSlice)(nil)
}
func doEncodeobjectSlice(e binary.Encoder, o *objectSlice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Object(o.value[i])
	}
}
func doDecodeobjectSlice(d binary.Decoder, o *objectSlice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]binary.Object, count)
		for i := range o.value {
			if obj := d.Object(); obj != nil {
				o.value[i] = obj.(binary.Object)
			} else {
				o.value[i] = nil
			}
		}
	}
}
func (*binaryClassobjectSlice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeobjectSlice(e, obj.(*objectSlice))
}
func (*binaryClassobjectSlice) Decode(d binary.Decoder) binary.Object {
	obj := &objectSlice{}
	doDecodeobjectSlice(d, obj)
	return obj
}
func (*binaryClassobjectSlice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeobjectSlice(d, obj.(*objectSlice))
}
func (*binaryClassobjectSlice) Schema() *binary.Entity { return schemaobjectSlice }

var schemaobjectSlice = &binary.Entity{
	Package:  "any",
	Identity: "objectSlice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Interface{Name: "binary.Object"}}},
	},
}

type binaryClassobject_ struct{}

func (*object_) Class() binary.Class {
	return (*binaryClassobject_)(nil)
}
func doEncodeobject_(e binary.Encoder, o *object_) {
	e.Object(o.value)
}
func doDecodeobject_(d binary.Decoder, o *object_) {
	if obj := d.Object(); obj != nil {
		o.value = obj.(binary.Object)
	} else {
		o.value = nil
	}
}
func (*binaryClassobject_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeobject_(e, obj.(*object_))
}
func (*binaryClassobject_) Decode(d binary.Decoder) binary.Object {
	obj := &object_{}
	doDecodeobject_(d, obj)
	return obj
}
func (*binaryClassobject_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeobject_(d, obj.(*object_))
}
func (*binaryClassobject_) Schema() *binary.Entity { return schemaobject_ }

var schemaobject_ = &binary.Entity{
	Package:  "any",
	Identity: "object_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Interface{Name: "binary.Object"}},
	},
}

type binaryClassstringSlice struct{}

func (*stringSlice) Class() binary.Class {
	return (*binaryClassstringSlice)(nil)
}
func doEncodestringSlice(e binary.Encoder, o *stringSlice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.String(o.value[i])
	}
}
func doDecodestringSlice(d binary.Decoder, o *stringSlice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]string, count)
		for i := range o.value {
			o.value[i] = string(d.String())
		}
	}
}
func (*binaryClassstringSlice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodestringSlice(e, obj.(*stringSlice))
}
func (*binaryClassstringSlice) Decode(d binary.Decoder) binary.Object {
	obj := &stringSlice{}
	doDecodestringSlice(d, obj)
	return obj
}
func (*binaryClassstringSlice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodestringSlice(d, obj.(*stringSlice))
}
func (*binaryClassstringSlice) Schema() *binary.Entity { return schemastringSlice }

var schemastringSlice = &binary.Entity{
	Package:  "any",
	Identity: "stringSlice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "string", Method: schema.String}}},
	},
}

type binaryClassstring_ struct{}

func (*string_) Class() binary.Class {
	return (*binaryClassstring_)(nil)
}
func doEncodestring_(e binary.Encoder, o *string_) {
	e.String(o.value)
}
func doDecodestring_(d binary.Decoder, o *string_) {
	o.value = string(d.String())
}
func (*binaryClassstring_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodestring_(e, obj.(*string_))
}
func (*binaryClassstring_) Decode(d binary.Decoder) binary.Object {
	obj := &string_{}
	doDecodestring_(d, obj)
	return obj
}
func (*binaryClassstring_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodestring_(d, obj.(*string_))
}
func (*binaryClassstring_) Schema() *binary.Entity { return schemastring_ }

var schemastring_ = &binary.Entity{
	Package:  "any",
	Identity: "string_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "string", Method: schema.String}},
	},
}

type binaryClassuint16Slice struct{}

func (*uint16Slice) Class() binary.Class {
	return (*binaryClassuint16Slice)(nil)
}
func doEncodeuint16Slice(e binary.Encoder, o *uint16Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Uint16(o.value[i])
	}
}
func doDecodeuint16Slice(d binary.Decoder, o *uint16Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]uint16, count)
		for i := range o.value {
			o.value[i] = uint16(d.Uint16())
		}
	}
}
func (*binaryClassuint16Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint16Slice(e, obj.(*uint16Slice))
}
func (*binaryClassuint16Slice) Decode(d binary.Decoder) binary.Object {
	obj := &uint16Slice{}
	doDecodeuint16Slice(d, obj)
	return obj
}
func (*binaryClassuint16Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint16Slice(d, obj.(*uint16Slice))
}
func (*binaryClassuint16Slice) Schema() *binary.Entity { return schemauint16Slice }

var schemauint16Slice = &binary.Entity{
	Package:  "any",
	Identity: "uint16Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "uint16", Method: schema.Uint16}}},
	},
}

type binaryClassuint16_ struct{}

func (*uint16_) Class() binary.Class {
	return (*binaryClassuint16_)(nil)
}
func doEncodeuint16_(e binary.Encoder, o *uint16_) {
	e.Uint16(o.value)
}
func doDecodeuint16_(d binary.Decoder, o *uint16_) {
	o.value = uint16(d.Uint16())
}
func (*binaryClassuint16_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint16_(e, obj.(*uint16_))
}
func (*binaryClassuint16_) Decode(d binary.Decoder) binary.Object {
	obj := &uint16_{}
	doDecodeuint16_(d, obj)
	return obj
}
func (*binaryClassuint16_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint16_(d, obj.(*uint16_))
}
func (*binaryClassuint16_) Schema() *binary.Entity { return schemauint16_ }

var schemauint16_ = &binary.Entity{
	Package:  "any",
	Identity: "uint16_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "uint16", Method: schema.Uint16}},
	},
}

type binaryClassuint32Slice struct{}

func (*uint32Slice) Class() binary.Class {
	return (*binaryClassuint32Slice)(nil)
}
func doEncodeuint32Slice(e binary.Encoder, o *uint32Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Uint32(o.value[i])
	}
}
func doDecodeuint32Slice(d binary.Decoder, o *uint32Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]uint32, count)
		for i := range o.value {
			o.value[i] = uint32(d.Uint32())
		}
	}
}
func (*binaryClassuint32Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint32Slice(e, obj.(*uint32Slice))
}
func (*binaryClassuint32Slice) Decode(d binary.Decoder) binary.Object {
	obj := &uint32Slice{}
	doDecodeuint32Slice(d, obj)
	return obj
}
func (*binaryClassuint32Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint32Slice(d, obj.(*uint32Slice))
}
func (*binaryClassuint32Slice) Schema() *binary.Entity { return schemauint32Slice }

var schemauint32Slice = &binary.Entity{
	Package:  "any",
	Identity: "uint32Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "uint32", Method: schema.Uint32}}},
	},
}

type binaryClassuint32_ struct{}

func (*uint32_) Class() binary.Class {
	return (*binaryClassuint32_)(nil)
}
func doEncodeuint32_(e binary.Encoder, o *uint32_) {
	e.Uint32(o.value)
}
func doDecodeuint32_(d binary.Decoder, o *uint32_) {
	o.value = uint32(d.Uint32())
}
func (*binaryClassuint32_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint32_(e, obj.(*uint32_))
}
func (*binaryClassuint32_) Decode(d binary.Decoder) binary.Object {
	obj := &uint32_{}
	doDecodeuint32_(d, obj)
	return obj
}
func (*binaryClassuint32_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint32_(d, obj.(*uint32_))
}
func (*binaryClassuint32_) Schema() *binary.Entity { return schemauint32_ }

var schemauint32_ = &binary.Entity{
	Package:  "any",
	Identity: "uint32_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
	},
}

type binaryClassuint64Slice struct{}

func (*uint64Slice) Class() binary.Class {
	return (*binaryClassuint64Slice)(nil)
}
func doEncodeuint64Slice(e binary.Encoder, o *uint64Slice) {
	e.Uint32(uint32(len(o.value)))
	for i := range o.value {
		e.Uint64(o.value[i])
	}
}
func doDecodeuint64Slice(d binary.Decoder, o *uint64Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]uint64, count)
		for i := range o.value {
			o.value[i] = uint64(d.Uint64())
		}
	}
}
func (*binaryClassuint64Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint64Slice(e, obj.(*uint64Slice))
}
func (*binaryClassuint64Slice) Decode(d binary.Decoder) binary.Object {
	obj := &uint64Slice{}
	doDecodeuint64Slice(d, obj)
	return obj
}
func (*binaryClassuint64Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint64Slice(d, obj.(*uint64Slice))
}
func (*binaryClassuint64Slice) Schema() *binary.Entity { return schemauint64Slice }

var schemauint64Slice = &binary.Entity{
	Package:  "any",
	Identity: "uint64Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "uint64", Method: schema.Uint64}}},
	},
}

type binaryClassuint64_ struct{}

func (*uint64_) Class() binary.Class {
	return (*binaryClassuint64_)(nil)
}
func doEncodeuint64_(e binary.Encoder, o *uint64_) {
	e.Uint64(o.value)
}
func doDecodeuint64_(d binary.Decoder, o *uint64_) {
	o.value = uint64(d.Uint64())
}
func (*binaryClassuint64_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint64_(e, obj.(*uint64_))
}
func (*binaryClassuint64_) Decode(d binary.Decoder) binary.Object {
	obj := &uint64_{}
	doDecodeuint64_(d, obj)
	return obj
}
func (*binaryClassuint64_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint64_(d, obj.(*uint64_))
}
func (*binaryClassuint64_) Schema() *binary.Entity { return schemauint64_ }

var schemauint64_ = &binary.Entity{
	Package:  "any",
	Identity: "uint64_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "uint64", Method: schema.Uint64}},
	},
}

type binaryClassuint8Slice struct{}

func (*uint8Slice) Class() binary.Class {
	return (*binaryClassuint8Slice)(nil)
}
func doEncodeuint8Slice(e binary.Encoder, o *uint8Slice) {
	e.Uint32(uint32(len(o.value)))
	e.Data(o.value)
}
func doDecodeuint8Slice(d binary.Decoder, o *uint8Slice) {
	if count := d.Uint32(); count > 0 {
		o.value = make([]uint8, count)
		d.Data(o.value)
	}
}
func (*binaryClassuint8Slice) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint8Slice(e, obj.(*uint8Slice))
}
func (*binaryClassuint8Slice) Decode(d binary.Decoder) binary.Object {
	obj := &uint8Slice{}
	doDecodeuint8Slice(d, obj)
	return obj
}
func (*binaryClassuint8Slice) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint8Slice(d, obj.(*uint8Slice))
}
func (*binaryClassuint8Slice) Schema() *binary.Entity { return schemauint8Slice }

var schemauint8Slice = &binary.Entity{
	Package:  "any",
	Identity: "uint8Slice",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "uint8", Method: schema.Uint8}}},
	},
}

type binaryClassuint8_ struct{}

func (*uint8_) Class() binary.Class {
	return (*binaryClassuint8_)(nil)
}
func doEncodeuint8_(e binary.Encoder, o *uint8_) {
	e.Uint8(o.value)
}
func doDecodeuint8_(d binary.Decoder, o *uint8_) {
	o.value = uint8(d.Uint8())
}
func (*binaryClassuint8_) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeuint8_(e, obj.(*uint8_))
}
func (*binaryClassuint8_) Decode(d binary.Decoder) binary.Object {
	obj := &uint8_{}
	doDecodeuint8_(d, obj)
	return obj
}
func (*binaryClassuint8_) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeuint8_(d, obj.(*uint8_))
}
func (*binaryClassuint8_) Schema() *binary.Entity { return schemauint8_ }

var schemauint8_ = &binary.Entity{
	Package:  "any",
	Identity: "uint8_",
	Fields: []binary.Field{
		{Declared: "value", Type: &schema.Primitive{Name: "uint8", Method: schema.Uint8}},
	},
}
