////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by rpcapi
////////////////////////////////////////////////////////////////////////////////

package test

// Call Add
type callAdd struct {
	a uint32
	b uint32
}

// Result Add
type resultAdd struct {
	value uint32
}

// Call EnumToString
type callEnumToString struct {
	e Enum
}

// Result EnumToString
type resultEnumToString struct {
	value string
}

// Call GetStruct
type callGetStruct struct {
}

// Result GetStruct
type resultGetStruct struct {
	value Struct
}

// Call SetStruct
type callSetStruct struct {
	s Struct
}

// Result SetStruct
type resultSetStruct struct {
}

// Call GetResource
type callGetResource struct {
}

// Result GetResource
type resultGetResource struct {
	value ResourceId
}

// Call UseResource
type callUseResource struct {
	r ResourceId
}

// Result UseResource
type resultUseResource struct {
}

// Call ResolveResource
type callResolveResource struct {
	r ResourceId
}

// Result ResolveResource
type resultResolveResource struct {
	value Resource
}

// Call GetSingleListNode
type callGetSingleListNode struct {
}

// Result GetSingleListNode
type resultGetSingleListNode struct {
	value *ListNode
}

// Call GetListNodeChain
type callGetListNodeChain struct {
}

// Result GetListNodeChain
type resultGetListNodeChain struct {
	value *ListNode
}

// Call GetListNodeChainArray
type callGetListNodeChainArray struct {
}

// Result GetListNodeChainArray
type resultGetListNodeChainArray struct {
	value ListNodeArray
}

// Call GetBase
type callGetBase struct {
}

// Result GetBase
type resultGetBase struct {
	value Base
}

// Call GetDerived
type callGetDerived struct {
}

// Result GetDerived
type resultGetDerived struct {
	value Base
}
