////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package replay

import (
	"fmt"

	"android.googlesource.com/platform/tools/gpu/binary/schema"
)

var ConstantValues schema.Constants

const _WireframeMode_name = "NoWireframeWireframeOverlayAllWireframe"

var _WireframeMode_map = map[WireframeMode]string{}

func init() {
	_WireframeMode_map[0] = _WireframeMode_name[0:11]
	_WireframeMode_map[1] = _WireframeMode_name[11:27]
	_WireframeMode_map[2] = _WireframeMode_name[27:39]

	ConstantValues = append(ConstantValues, schema.ConstantSet{
		Type: &schema.Primitive{Name: "WireframeMode", Method: schema.Int32},
		Entries: []schema.Constant{
			{Name: _WireframeMode_name[0:11], Value: int32(0)},
			{Name: _WireframeMode_name[11:27], Value: int32(1)},
			{Name: _WireframeMode_name[27:39], Value: int32(2)},
		},
	})
}

func (v WireframeMode) String() string {
	if s, ok := _WireframeMode_map[v]; ok {
		return s
	}
	return fmt.Sprintf("WireframeMode(%d)", v)
}

func (v *WireframeMode) Parse(s string) error {
	for k, t := range _WireframeMode_map {
		if s == t {
			*v = k
			return nil
		}
	}
	return fmt.Errorf("%s not in WireframeMode", s)
}
