////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package builder

import (
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/schema"
	"android.googlesource.com/platform/tools/gpu/gfxapi"
)

func init() {
	Namespace.Add((*testStruct)(nil).Class())
	Namespace.Add((*testAtom)(nil).Class())
}

var (
	binaryIDtestStruct = binary.ID{0x93, 0x39, 0x46, 0x5d, 0x2e, 0x91, 0x59, 0x69, 0x3a, 0x17, 0x8d, 0x2f, 0xc2, 0x43, 0xb7, 0x33, 0x93, 0xcc, 0xb3, 0x4a}
	binaryIDtestAtom   = binary.ID{0x71, 0x4f, 0xb5, 0x0a, 0x96, 0x6a, 0x28, 0xb8, 0xc0, 0xd5, 0x05, 0x8a, 0x90, 0x9f, 0x37, 0x61, 0x15, 0xa5, 0xb0, 0x22}
)

type binaryClasstestStruct struct{}

func (*testStruct) Class() binary.Class {
	return (*binaryClasstestStruct)(nil)
}
func doEncodetestStruct(e binary.Encoder, o *testStruct) {
	e.String(o.Str)
	if o.Ptr != nil {
		e.Object(o.Ptr)
	} else {
		e.Object(nil)
	}
}
func doDecodetestStruct(d binary.Decoder, o *testStruct) {
	o.Str = string(d.String())
	if obj := d.Object(); obj != nil {
		o.Ptr = obj.(*testStruct)
	} else {
		o.Ptr = nil
	}
}
func (*binaryClasstestStruct) ID() binary.ID      { return binaryIDtestStruct }
func (*binaryClasstestStruct) New() binary.Object { return &testStruct{} }
func (*binaryClasstestStruct) Encode(e binary.Encoder, obj binary.Object) {
	doEncodetestStruct(e, obj.(*testStruct))
}
func (*binaryClasstestStruct) Decode(d binary.Decoder) binary.Object {
	obj := &testStruct{}
	doDecodetestStruct(d, obj)
	return obj
}
func (*binaryClasstestStruct) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodetestStruct(d, obj.(*testStruct))
}
func (*binaryClasstestStruct) Schema() *schema.Entity { return schematestStruct }

var schematestStruct = &schema.Entity{
	TypeID:  binaryIDtestStruct,
	Package: "builder",
	Name:    "testStruct",
	Fields: []schema.Field{
		{Declared: "Str", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		{Declared: "Ptr", Type: &schema.Pointer{Type: &schema.Struct{Name: "testStruct", ID: (*testStruct)(nil).Class().ID()}}},
	},
}

type binaryClasstestAtom struct{}

func (*testAtom) Class() binary.Class {
	return (*binaryClasstestAtom)(nil)
}
func doEncodetestAtom(e binary.Encoder, o *testAtom) {
	e.ID(binary.ID(o.api))
	e.String(o.Str)
	e.Uint32(uint32(len(o.Sli)))
	for i := range o.Sli {
		e.Bool(o.Sli[i])
	}
	schema.Any{}.Encode(e, o.Any)
	if o.Ptr != nil {
		e.Object(o.Ptr)
	} else {
		e.Object(nil)
	}
	e.Uint32(uint32(len(o.Map)))
	for k, v := range o.Map {
		e.String(k)
		e.String(v)
	}
}
func doDecodetestAtom(d binary.Decoder, o *testAtom) {
	o.api = gfxapi.ID(d.ID())
	o.Str = string(d.String())
	if count := d.Uint32(); count > 0 {
		o.Sli = make([]bool, count)
		for i := range o.Sli {
			o.Sli[i] = bool(d.Bool())
		}
	}
	o.Any = schema.Any{}.Decode(d)
	if obj := d.Object(); obj != nil {
		o.Ptr = obj.(*testStruct)
	} else {
		o.Ptr = nil
	}
	if count := d.Uint32(); count > 0 {
		o.Map = make(map[string]string, count)
		m := o.Map
		for i := uint32(0); i < count; i++ {
			var k string
			var v string
			k = string(d.String())
			v = string(d.String())
			m[k] = v
		}
	}
}
func (*binaryClasstestAtom) ID() binary.ID      { return binaryIDtestAtom }
func (*binaryClasstestAtom) New() binary.Object { return &testAtom{} }
func (*binaryClasstestAtom) Encode(e binary.Encoder, obj binary.Object) {
	doEncodetestAtom(e, obj.(*testAtom))
}
func (*binaryClasstestAtom) Decode(d binary.Decoder) binary.Object {
	obj := &testAtom{}
	doDecodetestAtom(d, obj)
	return obj
}
func (*binaryClasstestAtom) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodetestAtom(d, obj.(*testAtom))
}
func (*binaryClasstestAtom) Schema() *schema.Entity { return schematestAtom }

var schematestAtom = &schema.Entity{
	TypeID:  binaryIDtestAtom,
	Package: "builder",
	Name:    "testAtom",
	Fields: []schema.Field{
		{Declared: "api", Type: &schema.Primitive{Name: "gfxapi.ID", Method: schema.ID}},
		{Declared: "Str", Type: &schema.Primitive{Name: "string", Method: schema.String}},
		{Declared: "Sli", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "bool", Method: schema.Bool}}},
		{Declared: "Any", Type: &schema.Any{}},
		{Declared: "Ptr", Type: &schema.Pointer{Type: &schema.Struct{Name: "testStruct", ID: (*testStruct)(nil).Class().ID()}}},
		{Declared: "Map", Type: &schema.Map{Alias: "", KeyType: &schema.Primitive{Name: "string", Method: schema.String}, ValueType: &schema.Primitive{Name: "string", Method: schema.String}}},
	},
}
