////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen -go
////////////////////////////////////////////////////////////////////////////////

package atom

import (
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/memory"
)

func init() {
	registry.Add((*Range)(nil).Class())
	registry.Add((*Group)(nil).Class())
	registry.Add((*Observation)(nil).Class())
	registry.Add((*Resource)(nil).Class())
}

var (
	binaryIDRange       = binary.ID{0x6f, 0xbb, 0x0f, 0x69, 0x4c, 0x19, 0xdb, 0x86, 0x34, 0x4f, 0x63, 0xc3, 0x04, 0xaf, 0x06, 0x89, 0xda, 0x0f, 0xb3, 0x0a}
	binaryIDGroup       = binary.ID{0x1d, 0x80, 0xcc, 0xfa, 0xe5, 0xba, 0x0e, 0x88, 0x3f, 0x11, 0x3b, 0xd5, 0x07, 0x16, 0x56, 0x13, 0xf5, 0x43, 0x42, 0xeb}
	binaryIDObservation = binary.ID{0x13, 0xd2, 0xf1, 0x8d, 0x80, 0x44, 0x62, 0x8c, 0x9f, 0x37, 0x28, 0xce, 0xc3, 0x13, 0x8b, 0xdf, 0x48, 0x50, 0xec, 0x49}
	binaryIDResource    = binary.ID{0xb8, 0x93, 0xdf, 0x90, 0x52, 0x2e, 0x33, 0x0b, 0x84, 0x00, 0x06, 0x1e, 0xca, 0x2d, 0xb0, 0x0a, 0xd6, 0x7c, 0x65, 0x25}
)

type binaryClassRange struct{}

func (*Range) Class() binary.Class {
	return (*binaryClassRange)(nil)
}
func doEncodeRange(e binary.Encoder, o *Range) error {
	if err := e.Uint64(uint64(o.Start)); err != nil {
		return err
	}
	if err := e.Uint64(uint64(o.End)); err != nil {
		return err
	}
	return nil
}
func doDecodeRange(d binary.Decoder, o *Range) error {
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.Start = ID(obj)
	}
	if obj, err := d.Uint64(); err != nil {
		return err
	} else {
		o.End = ID(obj)
	}
	return nil
}
func doSkipRange(d binary.Decoder) error {
	if _, err := d.Uint64(); err != nil {
		return err
	}
	if _, err := d.Uint64(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassRange) ID() binary.ID      { return binaryIDRange }
func (*binaryClassRange) New() binary.Object { return &Range{} }
func (*binaryClassRange) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeRange(e, obj.(*Range))
}
func (*binaryClassRange) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &Range{}
	return obj, doDecodeRange(d, obj)
}
func (*binaryClassRange) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeRange(d, obj.(*Range))
}
func (*binaryClassRange) Skip(d binary.Decoder) error { return doSkipRange(d) }

type binaryClassGroup struct{}

func (*Group) Class() binary.Class {
	return (*binaryClassGroup)(nil)
}
func doEncodeGroup(e binary.Encoder, o *Group) error {
	if err := e.String(o.Name); err != nil {
		return err
	}
	if err := e.Value(&o.Range); err != nil {
		return err
	}
	if err := e.Uint32(uint32(len(o.SubGroups))); err != nil {
		return err
	}
	for i := range o.SubGroups {
		if err := e.Value(&o.SubGroups[i]); err != nil {
			return err
		}
	}
	return nil
}
func doDecodeGroup(d binary.Decoder, o *Group) error {
	if obj, err := d.String(); err != nil {
		return err
	} else {
		o.Name = string(obj)
	}
	if err := d.Value(&o.Range); err != nil {
		return err
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.SubGroups = make(GroupList, count)
		for i := range o.SubGroups {
			if err := d.Value(&o.SubGroups[i]); err != nil {
				return err
			}
		}
	}
	return nil
}
func doSkipGroup(d binary.Decoder) error {
	if err := d.SkipString(); err != nil {
		return err
	}
	if err := d.SkipValue((*Range)(nil)); err != nil {
		return err
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		for i := uint32(0); i < count; i++ {
			if err := d.SkipValue((*Group)(nil)); err != nil {
				return err
			}
		}
	}
	return nil
}
func (*binaryClassGroup) ID() binary.ID      { return binaryIDGroup }
func (*binaryClassGroup) New() binary.Object { return &Group{} }
func (*binaryClassGroup) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeGroup(e, obj.(*Group))
}
func (*binaryClassGroup) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &Group{}
	return obj, doDecodeGroup(d, obj)
}
func (*binaryClassGroup) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeGroup(d, obj.(*Group))
}
func (*binaryClassGroup) Skip(d binary.Decoder) error { return doSkipGroup(d) }

type binaryClassObservation struct{}

func (*Observation) Class() binary.Class {
	return (*binaryClassObservation)(nil)
}
func doEncodeObservation(e binary.Encoder, o *Observation) error {
	if err := e.Value(&o.Range); err != nil {
		return err
	}
	if err := e.ID(o.ResourceID); err != nil {
		return err
	}
	return nil
}
func doDecodeObservation(d binary.Decoder, o *Observation) error {
	if err := d.Value(&o.Range); err != nil {
		return err
	}
	if obj, err := d.ID(); err != nil {
		return err
	} else {
		o.ResourceID = binary.ID(obj)
	}
	return nil
}
func doSkipObservation(d binary.Decoder) error {
	if err := d.SkipValue((*memory.Range)(nil)); err != nil {
		return err
	}
	if err := d.SkipID(); err != nil {
		return err
	}
	return nil
}
func (*binaryClassObservation) ID() binary.ID      { return binaryIDObservation }
func (*binaryClassObservation) New() binary.Object { return &Observation{} }
func (*binaryClassObservation) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeObservation(e, obj.(*Observation))
}
func (*binaryClassObservation) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &Observation{}
	return obj, doDecodeObservation(d, obj)
}
func (*binaryClassObservation) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeObservation(d, obj.(*Observation))
}
func (*binaryClassObservation) Skip(d binary.Decoder) error { return doSkipObservation(d) }

type binaryClassResource struct{}

func (*Resource) Class() binary.Class {
	return (*binaryClassResource)(nil)
}
func doEncodeResource(e binary.Encoder, o *Resource) error {
	if err := e.ID(o.ResourceID); err != nil {
		return err
	}
	if err := e.Uint32(uint32(len(o.Data))); err != nil {
		return err
	}
	if err := e.Data(o.Data); err != nil {
		return err
	}
	return nil
}
func doDecodeResource(d binary.Decoder, o *Resource) error {
	if obj, err := d.ID(); err != nil {
		return err
	} else {
		o.ResourceID = binary.ID(obj)
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		o.Data = make([]byte, count)
		if err := d.Data(o.Data); err != nil {
			return err
		}
	}
	return nil
}
func doSkipResource(d binary.Decoder) error {
	if err := d.SkipID(); err != nil {
		return err
	}
	if count, err := d.Uint32(); err != nil {
		return err
	} else {
		if err := d.Skip(count); err != nil {
			return err
		}
	}
	return nil
}
func (*binaryClassResource) ID() binary.ID      { return binaryIDResource }
func (*binaryClassResource) New() binary.Object { return &Resource{} }
func (*binaryClassResource) Encode(e binary.Encoder, obj binary.Object) error {
	return doEncodeResource(e, obj.(*Resource))
}
func (*binaryClassResource) Decode(d binary.Decoder) (binary.Object, error) {
	obj := &Resource{}
	return obj, doDecodeResource(d, obj)
}
func (*binaryClassResource) DecodeTo(d binary.Decoder, obj binary.Object) error {
	return doDecodeResource(d, obj.(*Resource))
}
func (*binaryClassResource) Skip(d binary.Decoder) error { return doSkipResource(d) }
