////////////////////////////////////////////////////////////////////////////////
// Do not modify!
// Generated by codergen
////////////////////////////////////////////////////////////////////////////////

package image

import (
	"android.googlesource.com/platform/tools/gpu/binary"
	"android.googlesource.com/platform/tools/gpu/binary/registry"
	"android.googlesource.com/platform/tools/gpu/binary/schema"
	"android.googlesource.com/platform/tools/gpu/service/path"
)

var Namespace = registry.NewNamespace()

func init() {
	registry.Global.AddFallbacks(Namespace)
	Namespace.Add((*Image)(nil).Class())
	Namespace.Add((*Info)(nil).Class())
	Namespace.Add((*LazyConverter)(nil).Class())
	Namespace.Add((*LazyResizer)(nil).Class())
	Namespace.Add((*fmtATC_RGBA_EXPLICIT_ALPHA_AMD)(nil).Class())
	Namespace.Add((*fmtATC_RGB_AMD)(nil).Class())
	Namespace.Add((*fmtAlpha)(nil).Class())
	Namespace.Add((*fmtETC1_RGB8_OES)(nil).Class())
	Namespace.Add((*fmtFloat32)(nil).Class())
	Namespace.Add((*fmtLuminance)(nil).Class())
	Namespace.Add((*fmtLuminanceAlpha)(nil).Class())
	Namespace.Add((*fmtPNG)(nil).Class())
	Namespace.Add((*fmtRGB)(nil).Class())
	Namespace.Add((*fmtRGB565)(nil).Class())
	Namespace.Add((*fmtRGBA)(nil).Class())
	Namespace.Add((*fmtRGBAF32)(nil).Class())
}

type binaryClassImage struct{}

func (*Image) Class() binary.Class {
	return (*binaryClassImage)(nil)
}
func doEncodeImage(e binary.Encoder, o *Image) {
	e.Object(o.Format)
	e.Uint32(o.Width)
	e.Uint32(o.Height)
	e.Uint32(uint32(len(o.Data)))
	e.Data(o.Data)
}
func doDecodeImage(d binary.Decoder, o *Image) {
	if obj := d.Object(); obj != nil {
		o.Format = obj.(Format)
	} else {
		o.Format = nil
	}
	o.Width = uint32(d.Uint32())
	o.Height = uint32(d.Uint32())
	if count := d.Uint32(); count > 0 {
		o.Data = make([]byte, count)
		d.Data(o.Data)
	}
}
func (*binaryClassImage) New() binary.Object { return &Image{} }
func (*binaryClassImage) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeImage(e, obj.(*Image))
}
func (*binaryClassImage) Decode(d binary.Decoder) binary.Object {
	obj := &Image{}
	doDecodeImage(d, obj)
	return obj
}
func (*binaryClassImage) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeImage(d, obj.(*Image))
}
func (*binaryClassImage) Schema() *binary.Entity { return schemaImage }

var schemaImage = &binary.Entity{
	Package:  "image",
	Identity: "Image",
	Fields: []binary.Field{
		{Declared: "Format", Type: &schema.Interface{Name: "Format"}},
		{Declared: "Width", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "Height", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "Data", Type: &schema.Slice{Alias: "", ValueType: &schema.Primitive{Name: "byte", Method: schema.Uint8}}},
	},
}

type binaryClassInfo struct{}

func (*Info) Class() binary.Class {
	return (*binaryClassInfo)(nil)
}
func doEncodeInfo(e binary.Encoder, o *Info) {
	e.Object(o.Format)
	e.Uint32(o.Width)
	e.Uint32(o.Height)
	if o.Data != nil {
		e.Object(o.Data)
	} else {
		e.Object(nil)
	}
}
func doDecodeInfo(d binary.Decoder, o *Info) {
	if obj := d.Object(); obj != nil {
		o.Format = obj.(Format)
	} else {
		o.Format = nil
	}
	o.Width = uint32(d.Uint32())
	o.Height = uint32(d.Uint32())
	if obj := d.Object(); obj != nil {
		o.Data = obj.(*path.Blob)
	} else {
		o.Data = nil
	}
}
func (*binaryClassInfo) New() binary.Object { return &Info{} }
func (*binaryClassInfo) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeInfo(e, obj.(*Info))
}
func (*binaryClassInfo) Decode(d binary.Decoder) binary.Object {
	obj := &Info{}
	doDecodeInfo(d, obj)
	return obj
}
func (*binaryClassInfo) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeInfo(d, obj.(*Info))
}
func (*binaryClassInfo) Schema() *binary.Entity { return schemaInfo }

var schemaInfo = &binary.Entity{
	Package:  "image",
	Identity: "Info",
	Fields: []binary.Field{
		{Declared: "Format", Type: &schema.Interface{Name: "Format"}},
		{Declared: "Width", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "Height", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "Data", Type: &schema.Pointer{Type: &schema.Struct{Entity: (*path.Blob)(nil).Class().Schema()}}},
	},
}

type binaryClassLazyConverter struct{}

func (*LazyConverter) Class() binary.Class {
	return (*binaryClassLazyConverter)(nil)
}
func doEncodeLazyConverter(e binary.Encoder, o *LazyConverter) {
	e.ID(o.Data)
	e.Uint32(o.Width)
	e.Uint32(o.Height)
	e.Object(o.FormatFrom)
	e.Object(o.FormatTo)
	e.Int32(int32(o.StrideFrom))
}
func doDecodeLazyConverter(d binary.Decoder, o *LazyConverter) {
	o.Data = binary.ID(d.ID())
	o.Width = uint32(d.Uint32())
	o.Height = uint32(d.Uint32())
	if obj := d.Object(); obj != nil {
		o.FormatFrom = obj.(Format)
	} else {
		o.FormatFrom = nil
	}
	if obj := d.Object(); obj != nil {
		o.FormatTo = obj.(Format)
	} else {
		o.FormatTo = nil
	}
	o.StrideFrom = int(d.Int32())
}
func (*binaryClassLazyConverter) New() binary.Object { return &LazyConverter{} }
func (*binaryClassLazyConverter) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeLazyConverter(e, obj.(*LazyConverter))
}
func (*binaryClassLazyConverter) Decode(d binary.Decoder) binary.Object {
	obj := &LazyConverter{}
	doDecodeLazyConverter(d, obj)
	return obj
}
func (*binaryClassLazyConverter) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeLazyConverter(d, obj.(*LazyConverter))
}
func (*binaryClassLazyConverter) Schema() *binary.Entity { return schemaLazyConverter }

var schemaLazyConverter = &binary.Entity{
	Package:  "image",
	Identity: "LazyConverter",
	Fields: []binary.Field{
		{Declared: "Data", Type: &schema.Primitive{Name: "binary.ID", Method: schema.ID}},
		{Declared: "Width", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "Height", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "FormatFrom", Type: &schema.Interface{Name: "Format"}},
		{Declared: "FormatTo", Type: &schema.Interface{Name: "Format"}},
		{Declared: "StrideFrom", Type: &schema.Primitive{Name: "int", Method: schema.Int32}},
	},
}

type binaryClassLazyResizer struct{}

func (*LazyResizer) Class() binary.Class {
	return (*binaryClassLazyResizer)(nil)
}
func doEncodeLazyResizer(e binary.Encoder, o *LazyResizer) {
	e.ID(o.Data)
	e.Object(o.Format)
	e.Uint32(o.SrcWidth)
	e.Uint32(o.SrcHeight)
	e.Uint32(o.DstWidth)
	e.Uint32(o.DstHeight)
}
func doDecodeLazyResizer(d binary.Decoder, o *LazyResizer) {
	o.Data = binary.ID(d.ID())
	if obj := d.Object(); obj != nil {
		o.Format = obj.(Format)
	} else {
		o.Format = nil
	}
	o.SrcWidth = uint32(d.Uint32())
	o.SrcHeight = uint32(d.Uint32())
	o.DstWidth = uint32(d.Uint32())
	o.DstHeight = uint32(d.Uint32())
}
func (*binaryClassLazyResizer) New() binary.Object { return &LazyResizer{} }
func (*binaryClassLazyResizer) Encode(e binary.Encoder, obj binary.Object) {
	doEncodeLazyResizer(e, obj.(*LazyResizer))
}
func (*binaryClassLazyResizer) Decode(d binary.Decoder) binary.Object {
	obj := &LazyResizer{}
	doDecodeLazyResizer(d, obj)
	return obj
}
func (*binaryClassLazyResizer) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodeLazyResizer(d, obj.(*LazyResizer))
}
func (*binaryClassLazyResizer) Schema() *binary.Entity { return schemaLazyResizer }

var schemaLazyResizer = &binary.Entity{
	Package:  "image",
	Identity: "LazyResizer",
	Fields: []binary.Field{
		{Declared: "Data", Type: &schema.Primitive{Name: "binary.ID", Method: schema.ID}},
		{Declared: "Format", Type: &schema.Interface{Name: "Format"}},
		{Declared: "SrcWidth", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "SrcHeight", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "DstWidth", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
		{Declared: "DstHeight", Type: &schema.Primitive{Name: "uint32", Method: schema.Uint32}},
	},
}

type binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD struct{}

func (*fmtATC_RGBA_EXPLICIT_ALPHA_AMD) Class() binary.Class {
	return (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD)(nil)
}
func doEncodefmtATC_RGBA_EXPLICIT_ALPHA_AMD(e binary.Encoder, o *fmtATC_RGBA_EXPLICIT_ALPHA_AMD) {
}
func doDecodefmtATC_RGBA_EXPLICIT_ALPHA_AMD(d binary.Decoder, o *fmtATC_RGBA_EXPLICIT_ALPHA_AMD) {
}
func (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD) New() binary.Object {
	return &fmtATC_RGBA_EXPLICIT_ALPHA_AMD{}
}
func (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtATC_RGBA_EXPLICIT_ALPHA_AMD(e, obj.(*fmtATC_RGBA_EXPLICIT_ALPHA_AMD))
}
func (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD) Decode(d binary.Decoder) binary.Object {
	obj := &fmtATC_RGBA_EXPLICIT_ALPHA_AMD{}
	doDecodefmtATC_RGBA_EXPLICIT_ALPHA_AMD(d, obj)
	return obj
}
func (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtATC_RGBA_EXPLICIT_ALPHA_AMD(d, obj.(*fmtATC_RGBA_EXPLICIT_ALPHA_AMD))
}
func (*binaryClassfmtATC_RGBA_EXPLICIT_ALPHA_AMD) Schema() *binary.Entity {
	return schemafmtATC_RGBA_EXPLICIT_ALPHA_AMD
}

var schemafmtATC_RGBA_EXPLICIT_ALPHA_AMD = &binary.Entity{
	Package:  "image",
	Identity: "fmtATC_RGBA_EXPLICIT_ALPHA_AMD",
	Fields:   []binary.Field{},
}

type binaryClassfmtATC_RGB_AMD struct{}

func (*fmtATC_RGB_AMD) Class() binary.Class {
	return (*binaryClassfmtATC_RGB_AMD)(nil)
}
func doEncodefmtATC_RGB_AMD(e binary.Encoder, o *fmtATC_RGB_AMD) {
}
func doDecodefmtATC_RGB_AMD(d binary.Decoder, o *fmtATC_RGB_AMD) {
}
func (*binaryClassfmtATC_RGB_AMD) New() binary.Object { return &fmtATC_RGB_AMD{} }
func (*binaryClassfmtATC_RGB_AMD) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtATC_RGB_AMD(e, obj.(*fmtATC_RGB_AMD))
}
func (*binaryClassfmtATC_RGB_AMD) Decode(d binary.Decoder) binary.Object {
	obj := &fmtATC_RGB_AMD{}
	doDecodefmtATC_RGB_AMD(d, obj)
	return obj
}
func (*binaryClassfmtATC_RGB_AMD) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtATC_RGB_AMD(d, obj.(*fmtATC_RGB_AMD))
}
func (*binaryClassfmtATC_RGB_AMD) Schema() *binary.Entity { return schemafmtATC_RGB_AMD }

var schemafmtATC_RGB_AMD = &binary.Entity{
	Package:  "image",
	Identity: "fmtATC_RGB_AMD",
	Fields:   []binary.Field{},
}

type binaryClassfmtAlpha struct{}

func (*fmtAlpha) Class() binary.Class {
	return (*binaryClassfmtAlpha)(nil)
}
func doEncodefmtAlpha(e binary.Encoder, o *fmtAlpha) {
}
func doDecodefmtAlpha(d binary.Decoder, o *fmtAlpha) {
}
func (*binaryClassfmtAlpha) New() binary.Object { return &fmtAlpha{} }
func (*binaryClassfmtAlpha) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtAlpha(e, obj.(*fmtAlpha))
}
func (*binaryClassfmtAlpha) Decode(d binary.Decoder) binary.Object {
	obj := &fmtAlpha{}
	doDecodefmtAlpha(d, obj)
	return obj
}
func (*binaryClassfmtAlpha) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtAlpha(d, obj.(*fmtAlpha))
}
func (*binaryClassfmtAlpha) Schema() *binary.Entity { return schemafmtAlpha }

var schemafmtAlpha = &binary.Entity{
	Package:  "image",
	Identity: "fmtAlpha",
	Fields:   []binary.Field{},
}

type binaryClassfmtETC1_RGB8_OES struct{}

func (*fmtETC1_RGB8_OES) Class() binary.Class {
	return (*binaryClassfmtETC1_RGB8_OES)(nil)
}
func doEncodefmtETC1_RGB8_OES(e binary.Encoder, o *fmtETC1_RGB8_OES) {
}
func doDecodefmtETC1_RGB8_OES(d binary.Decoder, o *fmtETC1_RGB8_OES) {
}
func (*binaryClassfmtETC1_RGB8_OES) New() binary.Object { return &fmtETC1_RGB8_OES{} }
func (*binaryClassfmtETC1_RGB8_OES) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtETC1_RGB8_OES(e, obj.(*fmtETC1_RGB8_OES))
}
func (*binaryClassfmtETC1_RGB8_OES) Decode(d binary.Decoder) binary.Object {
	obj := &fmtETC1_RGB8_OES{}
	doDecodefmtETC1_RGB8_OES(d, obj)
	return obj
}
func (*binaryClassfmtETC1_RGB8_OES) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtETC1_RGB8_OES(d, obj.(*fmtETC1_RGB8_OES))
}
func (*binaryClassfmtETC1_RGB8_OES) Schema() *binary.Entity { return schemafmtETC1_RGB8_OES }

var schemafmtETC1_RGB8_OES = &binary.Entity{
	Package:  "image",
	Identity: "fmtETC1_RGB8_OES",
	Fields:   []binary.Field{},
}

type binaryClassfmtFloat32 struct{}

func (*fmtFloat32) Class() binary.Class {
	return (*binaryClassfmtFloat32)(nil)
}
func doEncodefmtFloat32(e binary.Encoder, o *fmtFloat32) {
}
func doDecodefmtFloat32(d binary.Decoder, o *fmtFloat32) {
}
func (*binaryClassfmtFloat32) New() binary.Object { return &fmtFloat32{} }
func (*binaryClassfmtFloat32) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtFloat32(e, obj.(*fmtFloat32))
}
func (*binaryClassfmtFloat32) Decode(d binary.Decoder) binary.Object {
	obj := &fmtFloat32{}
	doDecodefmtFloat32(d, obj)
	return obj
}
func (*binaryClassfmtFloat32) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtFloat32(d, obj.(*fmtFloat32))
}
func (*binaryClassfmtFloat32) Schema() *binary.Entity { return schemafmtFloat32 }

var schemafmtFloat32 = &binary.Entity{
	Package:  "image",
	Identity: "fmtFloat32",
	Fields:   []binary.Field{},
}

type binaryClassfmtLuminance struct{}

func (*fmtLuminance) Class() binary.Class {
	return (*binaryClassfmtLuminance)(nil)
}
func doEncodefmtLuminance(e binary.Encoder, o *fmtLuminance) {
}
func doDecodefmtLuminance(d binary.Decoder, o *fmtLuminance) {
}
func (*binaryClassfmtLuminance) New() binary.Object { return &fmtLuminance{} }
func (*binaryClassfmtLuminance) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtLuminance(e, obj.(*fmtLuminance))
}
func (*binaryClassfmtLuminance) Decode(d binary.Decoder) binary.Object {
	obj := &fmtLuminance{}
	doDecodefmtLuminance(d, obj)
	return obj
}
func (*binaryClassfmtLuminance) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtLuminance(d, obj.(*fmtLuminance))
}
func (*binaryClassfmtLuminance) Schema() *binary.Entity { return schemafmtLuminance }

var schemafmtLuminance = &binary.Entity{
	Package:  "image",
	Identity: "fmtLuminance",
	Fields:   []binary.Field{},
}

type binaryClassfmtLuminanceAlpha struct{}

func (*fmtLuminanceAlpha) Class() binary.Class {
	return (*binaryClassfmtLuminanceAlpha)(nil)
}
func doEncodefmtLuminanceAlpha(e binary.Encoder, o *fmtLuminanceAlpha) {
}
func doDecodefmtLuminanceAlpha(d binary.Decoder, o *fmtLuminanceAlpha) {
}
func (*binaryClassfmtLuminanceAlpha) New() binary.Object { return &fmtLuminanceAlpha{} }
func (*binaryClassfmtLuminanceAlpha) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtLuminanceAlpha(e, obj.(*fmtLuminanceAlpha))
}
func (*binaryClassfmtLuminanceAlpha) Decode(d binary.Decoder) binary.Object {
	obj := &fmtLuminanceAlpha{}
	doDecodefmtLuminanceAlpha(d, obj)
	return obj
}
func (*binaryClassfmtLuminanceAlpha) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtLuminanceAlpha(d, obj.(*fmtLuminanceAlpha))
}
func (*binaryClassfmtLuminanceAlpha) Schema() *binary.Entity { return schemafmtLuminanceAlpha }

var schemafmtLuminanceAlpha = &binary.Entity{
	Package:  "image",
	Identity: "fmtLuminanceAlpha",
	Fields:   []binary.Field{},
}

type binaryClassfmtPNG struct{}

func (*fmtPNG) Class() binary.Class {
	return (*binaryClassfmtPNG)(nil)
}
func doEncodefmtPNG(e binary.Encoder, o *fmtPNG) {
}
func doDecodefmtPNG(d binary.Decoder, o *fmtPNG) {
}
func (*binaryClassfmtPNG) New() binary.Object { return &fmtPNG{} }
func (*binaryClassfmtPNG) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtPNG(e, obj.(*fmtPNG))
}
func (*binaryClassfmtPNG) Decode(d binary.Decoder) binary.Object {
	obj := &fmtPNG{}
	doDecodefmtPNG(d, obj)
	return obj
}
func (*binaryClassfmtPNG) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtPNG(d, obj.(*fmtPNG))
}
func (*binaryClassfmtPNG) Schema() *binary.Entity { return schemafmtPNG }

var schemafmtPNG = &binary.Entity{
	Package:  "image",
	Identity: "fmtPNG",
	Fields:   []binary.Field{},
}

type binaryClassfmtRGB struct{}

func (*fmtRGB) Class() binary.Class {
	return (*binaryClassfmtRGB)(nil)
}
func doEncodefmtRGB(e binary.Encoder, o *fmtRGB) {
}
func doDecodefmtRGB(d binary.Decoder, o *fmtRGB) {
}
func (*binaryClassfmtRGB) New() binary.Object { return &fmtRGB{} }
func (*binaryClassfmtRGB) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtRGB(e, obj.(*fmtRGB))
}
func (*binaryClassfmtRGB) Decode(d binary.Decoder) binary.Object {
	obj := &fmtRGB{}
	doDecodefmtRGB(d, obj)
	return obj
}
func (*binaryClassfmtRGB) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtRGB(d, obj.(*fmtRGB))
}
func (*binaryClassfmtRGB) Schema() *binary.Entity { return schemafmtRGB }

var schemafmtRGB = &binary.Entity{
	Package:  "image",
	Identity: "fmtRGB",
	Fields:   []binary.Field{},
}

type binaryClassfmtRGB565 struct{}

func (*fmtRGB565) Class() binary.Class {
	return (*binaryClassfmtRGB565)(nil)
}
func doEncodefmtRGB565(e binary.Encoder, o *fmtRGB565) {
}
func doDecodefmtRGB565(d binary.Decoder, o *fmtRGB565) {
}
func (*binaryClassfmtRGB565) New() binary.Object { return &fmtRGB565{} }
func (*binaryClassfmtRGB565) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtRGB565(e, obj.(*fmtRGB565))
}
func (*binaryClassfmtRGB565) Decode(d binary.Decoder) binary.Object {
	obj := &fmtRGB565{}
	doDecodefmtRGB565(d, obj)
	return obj
}
func (*binaryClassfmtRGB565) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtRGB565(d, obj.(*fmtRGB565))
}
func (*binaryClassfmtRGB565) Schema() *binary.Entity { return schemafmtRGB565 }

var schemafmtRGB565 = &binary.Entity{
	Package:  "image",
	Identity: "fmtRGB565",
	Fields:   []binary.Field{},
}

type binaryClassfmtRGBA struct{}

func (*fmtRGBA) Class() binary.Class {
	return (*binaryClassfmtRGBA)(nil)
}
func doEncodefmtRGBA(e binary.Encoder, o *fmtRGBA) {
}
func doDecodefmtRGBA(d binary.Decoder, o *fmtRGBA) {
}
func (*binaryClassfmtRGBA) New() binary.Object { return &fmtRGBA{} }
func (*binaryClassfmtRGBA) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtRGBA(e, obj.(*fmtRGBA))
}
func (*binaryClassfmtRGBA) Decode(d binary.Decoder) binary.Object {
	obj := &fmtRGBA{}
	doDecodefmtRGBA(d, obj)
	return obj
}
func (*binaryClassfmtRGBA) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtRGBA(d, obj.(*fmtRGBA))
}
func (*binaryClassfmtRGBA) Schema() *binary.Entity { return schemafmtRGBA }

var schemafmtRGBA = &binary.Entity{
	Package:  "image",
	Identity: "fmtRGBA",
	Fields:   []binary.Field{},
}

type binaryClassfmtRGBAF32 struct{}

func (*fmtRGBAF32) Class() binary.Class {
	return (*binaryClassfmtRGBAF32)(nil)
}
func doEncodefmtRGBAF32(e binary.Encoder, o *fmtRGBAF32) {
}
func doDecodefmtRGBAF32(d binary.Decoder, o *fmtRGBAF32) {
}
func (*binaryClassfmtRGBAF32) New() binary.Object { return &fmtRGBAF32{} }
func (*binaryClassfmtRGBAF32) Encode(e binary.Encoder, obj binary.Object) {
	doEncodefmtRGBAF32(e, obj.(*fmtRGBAF32))
}
func (*binaryClassfmtRGBAF32) Decode(d binary.Decoder) binary.Object {
	obj := &fmtRGBAF32{}
	doDecodefmtRGBAF32(d, obj)
	return obj
}
func (*binaryClassfmtRGBAF32) DecodeTo(d binary.Decoder, obj binary.Object) {
	doDecodefmtRGBAF32(d, obj.(*fmtRGBAF32))
}
func (*binaryClassfmtRGBAF32) Schema() *binary.Entity { return schemafmtRGBAF32 }

var schemafmtRGBAF32 = &binary.Entity{
	Package:  "image",
	Identity: "fmtRGBAF32",
	Fields:   []binary.Field{},
}
